### PR TITLE
test: Ensure we get error messages back on creation failure

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@sameo We want to ensure that we don't break this. This does match the output from runc. We could make these tests runc specific and add another set that just tests failure. WDYT?

**Comment by sameo** [comment]
@mrunalp Yes, fine with me. I assume runc does not provide any relevant `$?` ?

Also, I think we want a separated config file for that (and not an embedded python script ;)), just to be explicit on what we're trying to do.

**Comment by runcom** [comment]
LGTM

**Comment by mrunalp** [comment]
@sameo runc does return a non-zero exit code and check that status is not 0. With this test we want to make sure that our code is capturing and bubbling up container creation errors from the container runtime.

**Comment by sameo** [comment]
LGTM

**Pull request merged**
