### PR TITLE
[release-1.0] We need to release the SELinux label when we destroy the sandbox

### PR DESCRIPTION
**Pull request by runcom**
Closes #1051

@mrunalp @rhatdan PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
:+1:

**Comment by mrunalp** [comment]
Test failures here may be related

**Comment by rhatdan** [comment]
My latest patch uses the built in levels rather then add a new function

selinux.NewContext(ProcessLabel)["level"]

**Comment by rhatdan** [comment]
https://github.com/kubernetes-incubator/cri-o/pull/1051 is merged which does the equivalent of this patch.

**Pull request closed without merging**
