### PR TITLE
Add "image list/remove/status" to the client

### PR DESCRIPTION
**Pull request by nalind**
This patch adds "image list", "image status", and "image remove" subcommands to the client, most of it boilerplate stuff.

### CODE REVIEW

**Comment by runcom** [comment]
I'm ok with this if this will ease the work in #28

**Comment by nalind** [comment]
It's probably going to be needed for integration testing, though at the moment I have no such tests written.

**Comment by rhatdan** [comment]
@runcom if the code looks ok, we can just add a comment that we need someone to write tests for it.

**Comment by nalind** [comment]
I can work up a few, but they're going to have to wait for #28, where we're going to be fleshing out the server stubs.

**Comment by rhatdan** [comment]
So we have a chicken and egg then.  We need this patch to be merged to make merging https://github.com/kubernetes-incubator/cri-o/pull/28 easier, and then we can additional tests for this patch?

**Comment by nalind** [comment]
The main benefit is that it's this many lines of code that we won't have to review as part of a larger PR for #28.

**Comment by mrunalp** [comment]
No objections getting this in. But we should add tests when for the server changes when they are ready.

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
