### PR TITLE
vendor: containers/storage update

### PR DESCRIPTION
**Pull request by vbatts**
For cross-platform fixes

**- What I did**
update to containers/storage HEAD.

**- How I did it**
vndr

**- How to verify it**
`make`

**- Description for the changelog**

### CODE REVIEW

**Comment by rhatdan** [comment]
I already have a PR to pull this in.  But we have to fix the kata containers testing to get this in.  Basically this storage no longer allows loop back device by default.

**Comment by vbatts** [comment]
ah, i see #1574 now, but it also looks to update several vendored packages together

**Comment by rhatdan** [comment]
Yes but containers/image and containers/storage and the ones they require.

**Comment by vbatts** [comment]
right on. I'll track yours instead.

**Pull request closed without merging**
