### PR TITLE
server: make more things configurable

### PR DESCRIPTION
**Pull request by cyphar**
This PR just cleans up some of the hardcoding we had lying around inside ocid.

Signed-off-by: Aleksa Sarai asarai@suse.de

### CODE REVIEW

**Comment by runcom** [comment]
LGTM (still having CLA issue)

**Comment by mikebrow** [comment]
LGTM

**Comment by cyphar** [comment]
CLA has been fixed (and this PR rebased). I'll merge this in a second after rebasing my other PRs.

**Comment by cyphar** [comment]
Yeah, I forgot to merge it. Whoops. :smile_cat:

**Pull request merged**
