### PR TITLE
Add badge for Go Report Card

### PR DESCRIPTION
**Pull request by jawnsy**
This also changes the badges to be flat, and moves them down to
allow more room for future badges.

Signed-off-by: Jonathan Yu <jawnsy@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
Cool, LGTM

**Comment by mrunalp** [comment]
I am happy with the A ;)

**Comment by runcom** [comment]
I wouldn't have merged it if it wasn't an A haha

**Comment by rhatdan** [comment]
Yet again I feel like an old man.  

[We don't need no stinking badges.](https://www.youtube.com/watch?v=VqomZQMZQCQ)

**Pull request merged**
