### PR TITLE
contrib: test: switch node-e2e to e2e

### PR DESCRIPTION
**Pull request by runcom**
ref: https://github.com/kubernetes-incubator/cri-o/issues/533

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
RHEL is having OOM issues actually:

```
 _____________
< TASK [Make] >
 -------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [redacted]: FAILED! => {"ansible_job_id": "878718883690.4857", "changed": false, "cmd": "/usr/bin/make", "failed": true, "finished": 1, "msg": "# k8s.io/kubernetes/cmd/hyperkube\n/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory\n\n!!! [0827 17:56:25] Call tree:\n!!! [0827 17:56:25]  1: /root/src/k8s.io/kubernetes/hack/lib/golang.sh:710 kube::golang::build_binaries_for_platform(...)\n!!! [0827 17:56:25]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)\n!!! [0827 17:56:25] Call tree:\n!!! [0827 17:56:25]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)\n!!! [0827 17:56:25] Call tree:\n!!! [0827 17:56:25]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)\nmake: *** [all] Error 1", "rc": 2, "stderr": "# k8s.io/kubernetes/cmd/hyperkube\n/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory\n\n!!! [0827 17:56:25] Call tree:\n!!! [0827 17:56:25]  1: /root/src/k8s.io/kubernetes/hack/lib/golang.sh:710 kube::golang::build_binaries_for_platform(...)\n!!! [0827 17:56:25]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)\n!!! [0827 17:56:25] Call tree:\n!!! [0827 17:56:25]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)\n!!! [0827 17:56:25] Call tree:\n!!! [0827 17:56:25]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)\nmake: *** [all] Error 1\n", "stderr_lines": ["# k8s.io/kubernetes/cmd/hyperkube", "/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory", "", "!!! [0827 17:56:25] Call tree:", "!!! [0827 17:56:25]  1: /root/src/k8s.io/kubernetes/hack/lib/golang.sh:710 kube::golang::build_binaries_for_platform(...)", "!!! [0827 17:56:25]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)", "!!! [0827 17:56:25] Call tree:", "!!! [0827 17:56:25]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)", "!!! [0827 17:56:25] Call tree:", "!!! [0827 17:56:25]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)", "make: *** [all] Error 1"], "stdout": "+++ [0827 17:53:46] Building the toolchain targets:\n    k8s.io/kubernetes/hack/cmd/teststale\n    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata\n+++ [0827 17:53:46] Generating bindata:\n    test/e2e/generated/gobindata_util.go\n~/src/k8s.io/kubernetes ~/src/k8s.io/kubernetes/test/e2e/generated\n~/src/k8s.io/kubernetes/test/e2e/generated\n+++ [0827 17:53:46] Building go targets for linux/amd64:\n    cmd/kube-proxy\n    cmd/kube-apiserver\n    cmd/kube-controller-manager\n    cmd/cloud-controller-manager\n    cmd/kubelet\n    cmd/kubeadm\n    cmd/hyperkube\n    vendor/k8s.io/kube-aggregator\n    vendor/k8s.io/apiextensions-apiserver\n    plugin/cmd/kube-scheduler\n    cmd/kubectl\n    federation/cmd/kubefed\n    cmd/gendocs\n    cmd/genkubedocs\n    cmd/genman\n    cmd/genyaml\n    cmd/mungedocs\n    cmd/genswaggertypedocs\n    cmd/linkcheck\n    federation/cmd/genfeddocs\n    vendor/github.com/onsi/ginkgo/ginkgo\n    test/e2e/e2e.test\n    cmd/kubemark\n    vendor/github.com/onsi/ginkgo/ginkgo\n    test/e2e_node/e2e_node.test\n    cmd/gke-certificates-controller\n", "stdout_lines": ["+++ [0827 17:53:46] Building the toolchain targets:", "    k8s.io/kubernetes/hack/cmd/teststale", "    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata", "+++ [0827 17:53:46] Generating bindata:", "    test/e2e/generated/gobindata_util.go", "~/src/k8s.io/kubernetes ~/src/k8s.io/kubernetes/test/e2e/generated", "~/src/k8s.io/kubernetes/test/e2e/generated", "+++ [0827 17:53:46] Building go targets for linux/amd64:", "    cmd/kube-proxy", "    cmd/kube-apiserver", "    cmd/kube-controller-manager", "    cmd/cloud-controller-manager", "    cmd/kubelet", "    cmd/kubeadm", "    cmd/hyperkube", "    vendor/k8s.io/kube-aggregator", "    vendor/k8s.io/apiextensions-apiserver", "    plugin/cmd/kube-scheduler", "    cmd/kubectl", "    federation/cmd/kubefed", "    cmd/gendocs", "    cmd/genkubedocs", "    cmd/genman", "    cmd/genyaml", "    cmd/mungedocs", "    cmd/genswaggertypedocs", "    cmd/linkcheck", "    federation/cmd/genfeddocs", "    vendor/github.com/onsi/ginkgo/ginkgo", "    test/e2e/e2e.test", "    cmd/kubemark", "    vendor/github.com/onsi/ginkgo/ginkgo", "    test/e2e_node/e2e_node.test", "    cmd/gke-certificates-controller"]}
        to retry, use: --limit @/home/amurdaca/go/src/github.com/kubernetes-incubator/cri-o/contrib/test/crio-integration-playbook.retry
```

**Comment by runcom** [comment]
nada, can't `make` kubernetes at all in the CI :confused:

**Comment by runcom** [comment]
Pushed @cevich's commits here (squashed them), let's see how it goes and if we can compile kube (after I'll take care of actually make tests run)

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
we might need something like this https://github.com/kubernetes-incubator/cri-containerd/commit/e6332a7d7f136f85211a7cabee99809ccc11bc41 - leaving here for future reference as I'm re-working this PR

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
(no worry, it's not the CI not reporting, it's me cancelling the build in the CI once I see they do not work :smile: )

**Comment by cevich** [comment]
> (no worry, it's not the CI not reporting

Good on you for doing it that way, it reduces resource-consumption.  Just pay attention the 'teardown' of VMs happens, otherwise they get "orphaned".  Let me know if you don't know how to spot that in the logs.

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
:tada: :tada: :tada: 

So, here is the thing with `149/152`: the tests ran and passed are 149, 0 failed, but the CI has a `grep` which is failing to find the failed number and is adding +3 because it finds 3 "Failure" string. I'm fixing that as we speak and I'll merge this meanwhile :)

**Pull request merged**
