### PR TITLE
Apply working dir and env from image config

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mpatel@redhat.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
This should fix #411 
@nalind @runcom @sameo PTAL

**Comment by runcom** [comment]
LGTM (though we might have the same issue as in #395 for v2s1 images)

**Comment by mrunalp** [comment]
@runcom Yeah, sounds good.

**Comment by sameo** [comment]
LGTM

**Pull request merged**
