### PR TITLE
Move remaining server state to libkpod

### PR DESCRIPTION
**Pull request by mheon**
This moves sandbox-related state from the server package into libkpod. It removes remaining server state locking as well.

### CODE REVIEW

**Comment by mheon** [comment]
This needs to be merged before #677 to make sure that we don't have two locks to move to disk

**Comment by mheon** [comment]
@mrunalp PTAL

**Comment by mrunalp** [comment]
LGTM
@14rcole @runcom PTAL

**Comment by 14rcole** [comment]
LGTM

**Pull request merged**
