### PR TITLE
Vendor in latest go-selinux so that it supports non linux builds

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by rhatdan** [comment]
@mrunalp @runcom @wking PTAL

**Comment by giuseppe** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Pull request merged**
