### PR TITLE
Release version 0.2

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom @sameo @cyphar @rhatdan PTAL

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM :+1:

**Comment by cyphar** [comment]
LGTM

**Comment by cyphar** [comment]
Would you be interested in something like `umoci`'s `release.sh` script (which generates signed git archives, ready for uploading to GitHub so distributions can pull signed archives).

**Comment by mrunalp** [comment]
@cyphar Yes, that will be great.

**Comment by cyphar** [comment]
Alright, I'll modify my script for `cri-o`.

**Comment by mrunalp** [comment]
@cyphar I will cut the release. Can you upload the binaries to it with your script?

**Comment by cyphar** [comment]
Sure. I'll upload the binaries and also the signed archive. I'll also make a PR with the required patches to make `release.sh` nice. Unfortunately you can't statically compile `ocid`. :cry:

**Comment by mrunalp** [comment]
@cyphar Will leave it in your hands then https://github.com/kubernetes-incubator/cri-o/releases/tag/v0.2 :)
Let me know once you are done uploading. I will send out email.

**Pull request merged**
