### PR TITLE
Fix Typo in cri-o Tutorial

### PR DESCRIPTION
**Pull request by mbssaiakhil**

### CODE REVIEW

**Comment by rhatdan** [comment]
You need to sign your pull request.

**Comment by mbssaiakhil** [comment]
Thanks @rhatdan, I have signed my commit, kindly review and merge.

**Comment by rhatdan** [comment]
LGTM
@runcom Please merge, no reason to run tests.

**Comment by rhatdan** [comment]
@mrunalp  Please merge, no reason to run tests.

**Pull request merged**
