### PR TITLE
WIP: conmon: Increase size of buffers

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by wking** [comment]
These bumps seem unique to 1.9 (at least, I don't see them in master yet).  Can you share your motivation for the bumps?

**Comment by mrunalp** [comment]
The purpose of this is to tune to get good defaults. We have a perf team looking at this. Once we get results from them, we can finalize the values. I'll amend the commit and change title to WIP.

**Comment by rhatdan** [comment]
@mrunalp is this still something we are interested in?

**Comment by mrunalp** [comment]
I think we can close this for now.

**Pull request closed without merging**
