### PR TITLE
conmon: Use glib mainloop instead of epoll

### PR DESCRIPTION
**Pull request by alexlarsson**
This drops the custom epoll code from conmon, and used a glib mainloop instead.

This is the first step in cleaning this code up. Once this is in I think we can fix the FIXME in the code that does the terminal accept.

Note, i have not really tested this in a full kubernetes instance. Having issues getting kube to run atm. Lets see what the CI says about this :)

### CODE REVIEW

**Comment by mrunalp** [comment]
@alexlarsson Nice! :)
btw, you can try using this branch for testing with kubernetes https://github.com/runcom/kubernetes/tree/custom-RHEL-node-e2e

**Comment by mrunalp** [comment]
Travis is happy, will wait for Jenkins next :)

**Comment by alexlarsson** [comment]
Updated to latest master and fixed some issues

**Comment by alexlarsson** [comment]
Forgot to sign off :/

**Comment by mrunalp** [comment]
Travis passed :tada: Waiting for e2e again.

**Comment by runcom** [comment]
LGTM

**Pull request merged**
