### PR TITLE
restore pod annotations when restart ocid

### PR DESCRIPTION
**Pull request by Crazykev**
fix https://github.com/kubernetes-incubator/cri-o/pull/179#issuecomment-257492326

Signed-off-by: Crazykev <crazykev@zju.edu.cn>

### CODE REVIEW

**Comment by runcom** [comment]
Would be nice to add a test

**Comment by Crazykev** [comment]
@runcom test case in #179 will test this.

**Comment by runcom** [comment]
I see, can you move that here since it's clearly testing a regression in this code path?

**Comment by Crazykev** [comment]
Er... Currently, pod name can't be restored from restart because metadata isn't stored. If I just move code in `restore.bats` here, it will fail due to missing field `Name` after restart ocid.

**Comment by runcom** [comment]
I meant to have a basic test which tests that annotation are restored (somehow). I guess it's ok if this is not feasible, ping @mrunalp

**Comment by mrunalp** [comment]
We can merge this. LGTM.

**Pull request merged**
