### PR TITLE
lint: Exit and give instructions when linter missing

### PR DESCRIPTION
**Pull request by ashcrow**

### CODE REVIEW

**Comment by mheon** [comment]
LGTM pending tests

**Comment by mheon** [comment]
Travis is complaining your commit is missing a signoff

**Comment by ashcrow** [comment]
@mheon added signoff.

**Comment by mheon** [comment]
@ashcrow Thanks! Hopefully that should make Travis happy

**Comment by mheon** [comment]
Travis is green, and this shouldn't affect the Jenkins build. @mrunalp @rhatdan can we get this merged?

**Comment by rhatdan** [comment]
Lets Merge.

**Pull request merged**
