### PR TITLE
Use formatter for C code

### PR DESCRIPTION
**Pull request by mrunalp**
**- What I did**
Added clang format support.

**- How I did it**
Added a .clang-format style file

**- How to verify it**
Look at the beautifully formatted code ;)

**- Description for the changelog**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM 
We need to get this merged quickly since it changes conmon, so much that every PR will cause rebases.

**Comment by wking** [comment]
Can we get, either in this PR or in follow-up work, docs for this in `CONTRIBUTING.md`?  A note about installing and calling [`clang-format`][1] would be nice.  And we may want to add a `fmt` target to the main `Makefile`:

```makefile
fmt: cfmt gofmt

cfmt:
  find . '(' -name '*.h' -o -name '*.c' ')' -exec clang-format -i {} \+
  git diff --exit-code
```

I'm not quite sure what the `clang-format` invocation should look like; the one above may still need changes.  With that in the `Makefile`, the `CONTRIBUTING.md` docs could just suggest installing `clang-format` and running `make fmt`.

[1]: https://clang.llvm.org/docs/ClangFormat.html

**Comment by mrunalp** [comment]
@wking Yeah I was planning to add the invocation to the Makefile in this PR.

**Comment by mrunalp** [comment]
Added makefile changes. We can create follow-on for other changes.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
