### PR TITLE
Bump 1.8.5

### PR DESCRIPTION
**Pull request by runcom**
**- What I did**

bump to v1.8.5 to take care of the socket listen flag in 1.8.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
@mrunalp @rhatdan PTAL this is so gree :)

**Comment by rhatdan** [comment]
LGTM
Merging.

**Comment by rhatdan** [comment]
Can you tag a release, so we can build it for OpenShift.

**Comment by runcom** [comment]
Yup, doing that as we speak Dan.

**Pull request merged**
