### PR TITLE
server: fix race between container create and cadvisor asking for info

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

same as #1616 but for master

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by giuseppe** [comment]
LGTM

**Comment by runcom** [comment]
> /test kata-containers

@rhatdan kata is broken at the moment, we were notified on IRC

**Comment by rhatdan** [comment]
Ignoring Kata Errors, until they fix it.  Merging anyways.

**Pull request merged**
