### PR TITLE
.travis.yml: add go1.8

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by jawnsy** [comment]
LGTM. However, and this is probably my fault, we should use versions like:

```yaml
 go:
    - 1.6.x
    - 1.7.x
    - 1.8.x
```

if we mean "1.8 or later." Otherwise it will always download 1.7.0, 1.8.0, etc.

**Comment by runcom** [comment]
> if we mean "1.8 or later." Otherwise it will always download 1.7.0, 1.8.0, etc.

I was 100% it was going to download the patch release :confounded:

**Comment by runcom** [comment]
@jawnsy updated with `.x` suffixes

**Comment by mikebrow** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM

**Pull request merged**
