### PR TITLE
image: Add lock around image cache access

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom @nalind PTAL

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by nalind** [comment]
LGTM

**Comment by redbaron** [comment]
Just curios, why not all accesses to imageCache are guarded by lock?

https://github.com/mrunalp/cri-o/blob/859109b42010a3bde374848c52f25f9dd42ea3cf/pkg/storage/image.go#L190

**Comment by runcom** [comment]
> Just curios, why not all accesses to imageCache are guarded by lock?
> 
> https://github.com/mrunalp/cri-o/blob/859109b42010a3bde374848c52f25f9dd42ea3cf/pkg/storage/image.go#L190

we probably have missed that, thanks for reporting, would you be interested in submitting a patch to fix that?

**Comment by redbaron** [comment]
yes, I'll do that. Should I pull imageCache into it's own type with internal lock? So there is no way to miss it again?

**Comment by runcom** [comment]
@redbaron let's fix it the easy way for now, you might follow up with another PR to change that in its own type with internal locking :)

**Comment by redbaron** [comment]
@runcom, submitted https://github.com/kubernetes-incubator/cri-o/pull/1415

**Pull request merged**
