### PR TITLE
[DO NOT MERGE] k8s v1.6.1 branch

### PR DESCRIPTION
**Pull request by runcom**
@sameo @mrunalp here's the k8s v1.6.1 branch.

This branch isn't meant to be merged into master. Just tracking and experimenting.

~~Origin PR to track 1.6.1 rebase is here https://github.com/openshift/origin/pull/13653 if anyone is brave enough to test it out :)~~

~~To test origin + cri-o you need to setup CRI flags in kubelet via https://docs.openshift.com/container-platform/3.5/admin_guide/manage_nodes.html#configuring-node-resources~~

### CODE REVIEW

**Comment by runcom** [comment]
> remove s.Update() calls that were causing a silly panic while running k8s tests

nope this isn't related, something is causing the following panic with this branch:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x63d06d]

goroutine 7455 [running]:
panic(0xbb9380, 0xc4200100c0)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/kubernetes-incubator/cri-o/oci.(*Runtime).UpdateStatus(0xc42024a0e0, 0x0, 0x0, 0x0)
        /home/amurdaca/go/src/github.com/kubernetes-incubator/cri-o/oci/oci.go:481 +0x6d
github.com/kubernetes-incubator/cri-o/server.(*Server).PodSandboxStatus(0xc4200a6280, 0x7f94cb2086f0, 0xc42091e840, 0xc420765470, 0x0, 0x42, 0x42)
        /home/amurdaca/go/src/github.com/kubernetes-incubator/cri-o/server/sandbox_status.go:20 +0x114
github.com/kubernetes-incubator/cri-o/vendor/k8s.io/kubernetes/pkg/kubelet/api/v1alpha1/runtime._RuntimeService_PodSandboxStatus_Handler(0xc8a520, 0xc4200a6280, 0x7f94cb2086f0, 0xc42091e840, 0xc4207733b0, 0x0, 0x0, 0x0, 0x6f7774656e2d646f, 0x2d747365742d6b72)
        /home/amurdaca/go/src/github.com/kubernetes-incubator/cri-o/vendor/k8s.io/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2354 +0x27d
```

**Comment by runcom** [comment]
I didn't encounter the panic above with the latest two commits here and overlayfs - I'm re-testing with devmapper (which was where I was getting that panic :confused:)

**Comment by runcom** [comment]
devmapper has all sort of issues when running tests. At some point, something gets stuck and tests start to fail :confused: @mrunalp was the idea to drop devmapper for cri-o? :angel:

**Comment by mrunalp** [comment]
Do the e2e tests pass on this?

**Comment by runcom** [comment]
Yes, with overlay

**Comment by mrunalp** [comment]
@runcom Cool, can you push this branch directly then?

**Comment by runcom** [comment]
@mrunalp it's already pushed to origin set to this repo :)

**Comment by runcom** [comment]
Let's leave this PR opened for a while to cherry pick stuff and have an history of the conversation though

**Comment by mrunalp** [comment]
@runcom Ahh, my bad. Cool :+1:  :)

**Comment by runcom** [comment]
I'm going to rebase this on latest master - hopefully the exec stuff doesn't conflict with k8s 1.6.1

**Comment by runcom** [comment]
rebased on latest CRI-O master (with some hassles about vendoring) - will run k8s's e2e now (API it's still kube 1.6.1, we might want to go to 1.6.2 soon-ish)

**Comment by runcom** [comment]
In case someone wants to try out k8s's e2e tests from kube upstream v1.6.1 tag, you need to cherry-pick the following commit in order to prepull images with the CRI: https://github.com/kubernetes/kubernetes/pull/40804/commits/2634f57f7f48ac1ae0388e906d32855d79bd1de8

**Comment by runcom** [comment]
100% k8s tests passing :tada:

**Comment by runcom** [comment]
alright, closing this, branch is pushed to origin as `kube-1.6.x` (we'll have `kube-1.7.x` soon, while `master` tracks latest kube master)

**Pull request closed without merging**
