### PR TITLE
kpod version

### PR DESCRIPTION
**Pull request by umohnani8**
Pulled in the changes from https://github.com/kubernetes-incubator/cri-o/pull/861 and updated the version for kpod.

### CODE REVIEW

**Comment by mrunalp** [comment]
Let us use a different KPOD_VERSION file here.

**Comment by umohnani8** [comment]
okay, what should the version be in the KPOD_VERSION file?

**Comment by mheon** [comment]
I think kpod is still alpha quality. @mrunalp @rhatdan Thoughts?

**Comment by mrunalp** [comment]
We could start at 0.1

**Comment by umohnani8** [comment]
@mheon PTAL.

**Comment by mheon** [comment]
LGTM pending tests

**Comment by TomSweeneyRedHat** [comment]
Code LGTM, but Travis isn't happy.

**Comment by umohnani8** [comment]
Rebased

**Comment by umohnani8** [comment]
[retest]

**Comment by rhatdan** [comment]
Definitely alpha, we need RUN/EXEC/CREATE before we can consider this beta.

**Comment by rhatdan** [comment]
LGTM

**Comment by umohnani8** [comment]
Travis is failing on `not ok 26 run ctr with image with Config.Volumes`. Any reason why?

**Comment by rhatdan** [comment]
Could be a flake?  Retrying.

**Comment by rhatdan** [comment]
Passes now.

**Comment by rhatdan** [comment]
@umohnani8 Needs rebase.

**Comment by umohnani8** [comment]
Rebased

**Comment by rhatdan** [comment]
[retest]

**Comment by rhatdan** [comment]
Merging.

**Pull request merged**
