### PR TITLE
Create OCID_LINK for both ocic and ocid

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Dan Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes requested for https://github.com/kubernetes-incubator/cri-o/pull/145

**Comment by rhatdan** [comment]
@cyphar PTAL

**Comment by cyphar** [comment]
This is fine, but I already included it in #149. Unfortunately, I'm still waiting on the CLA stuff being cleared up.

**Comment by rhatdan** [comment]
Ok I will close and wait for yours.

**Pull request closed without merging**
