### PR TITLE
crio: abstract the selinux call

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by wking** [comment]
Is it worth upstreaming this and #1383?  I imagine all go-selinux consumers would want similar no-ops on non-Linux platforms.

**Comment by vbatts** [comment]
maybe, though selinux is linux only, so it seems to me that owness is on
the caller to that library to work on their own platform independence.

**Comment by wking** [comment]
Then maybe add our own `pkg/selinux` wrapper?  That makes it easy to push upstream or reuse in other projects that also need SELinux if and only if they're building on Linux.

**Comment by rhatdan** [comment]
I think this is fine for now, but having a pkg/selinux is probably not a bad idea.
/test all

**Comment by rhatdan** [comment]
Green tests.  Merging.

**Pull request merged**
