### PR TITLE
allow update running/created container.

### PR DESCRIPTION
**Pull request by sak0**
allow update running/created container.

Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
is there any reason to check for status? afaict, the proto isn't saying anything about that https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto#L64

@feiskyer @Random-Liu what do you think?

**Comment by rhatdan** [comment]
Is this going to effect performance also?

**Comment by feiskyer** [comment]
@runcom I think UpdateContainerResources only works for pending (just created) or running containers. It seems no meanings to update resources for exited containers.

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
@sak0 Please rebase.

**Comment by sak0** [comment]
@runcom thanks for review. squashed.

**Pull request merged**
