### PR TITLE
Add operation lock for containers

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom @sameo PTAL. See if this helps with races during tests.

Signed-off-by: Mrunal Patel <mpatel@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@feiskyer @jjlakis PTAL as well when integrating k8s

**Comment by runcom** [comment]
BTW, tests still fails with `wait: no child processes` for instance https://paste.fedoraproject.org/506082/
```
# time="2016-12-14T10:25:31+01:00" level=fatal msg="listing pod sandboxes failed: rpc error: code = 2 desc = error getting container state for redhat.test.ocid-podsandbox1-1-infra: wait: no child processes
[...]
```

**Comment by Crazykev** [comment]
@runcom I don't think this kind of race could be solved in ocid by adding lock like this way, this maybe a problem that we did't use `cmd.Run/Start/Wait` correctly.

**Comment by runcom** [comment]
> @runcom I don't think this kind of race could be solved in ocid by adding lock like this way, this maybe a problem that we did't use cmd.Run/Start/Wait correctly.

right, indeed, we're still getting that error - ignoring it like that isn't really helping either

**Comment by Crazykev** [comment]
@runcom Yep,I forgot add a warning for that, and sure that's not a long term solution, just make sure it won't block our way on testing or running. I'm also finding a way to fix that.

**Comment by runcom** [comment]
I believe having a container operation lock makes sense anyway, going to merge this one as it won't likely cause any issue as is.

**Pull request merged**
