### PR TITLE
[release-1.0] Makefile: output binaries under bin/

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Is this something we want to get into 1.0.2?

**Comment by runcom** [comment]
> Is this something we want to get into 1.0.2?

nope, this can just wait till 1.0.3

**Comment by runcom** [comment]
mmm not sure why the same PR is ok on master but it's on here in release-1.0 branch

**Comment by runcom** [comment]
wtf

**Comment by runcom** [comment]
figured, there were missing commits from master actually, we need to keep attention on backporting stuff.

**Comment by runcom** [comment]
ping @mrunalp @rhatdan

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
Since this is passing tests, I am merging.

LGTM

**Pull request merged**
