### PR TITLE
Bump up to beta1

### LINKED ISSUE #825: add commit information to version output
It would be helpful to see HEAD's SHA included in --version output for crio(ctl).

This became apparent when looking @ latest drop of kubernetes-the-hardway and wanting to know what branch/release matches 'v1.0.0-beta.0.'  Looking at the sources, there is a matching TAG for this in release-1.6 branch (and master), though the version updated in the source tree (app.Version) was updated considerably later in the source tree.

Having a SHA would make these all very clear.

Let me know what you all think.  If you agree I can put this on my to-do-list.

### PR DESCRIPTION
**Pull request by mrunalp**
Fixes #825
We also add support for displaying commit in --version.

Wait for #860 to be merged before merging this.

@runcom @rhatdan

### CODE REVIEW

**Comment by mrunalp** [comment]
[retest]

**Comment by rhatdan** [comment]
@umohnani8 We need this to be added to kpod version and kpod info.

**Comment by rhatdan** [comment]
LGTM,  Don't stop update Beta waiting for kpod to include it.

**Comment by umohnani8** [comment]
Working on it!

**Comment by umohnani8** [comment]
@mrunalp oh okay, I thought we wanted them to match. I created the pull request https://github.com/kubernetes-incubator/cri-o/pull/863.
We can discuss there.

**Comment by mheon** [comment]
Agree with not tying kpod to cri-o for versioning - they're two very different tools that are maturing at different speeds.

**Comment by runcom** [comment]
Yeah no kpod version == cri-o version.

LGTM

**Comment by mrunalp** [comment]
[retest]

**Comment by mrunalp** [comment]
Rebased.

**Comment by mrunalp** [comment]
[retest]

**Comment by rhatdan** [comment]
Sure I have no problem with the versions mismatch, but the github reference stuff should be the same.

**Comment by rhatdan** [comment]
@mrunalp BTW I think we should refer to this as RC1, rather then Beta1.

**Comment by mrunalp** [comment]
sure, I'll change it.

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
> [retest]

there wasn't any job triggered actually

**Pull request closed without merging**
