### PR TITLE
Make logging to syslog optional

### LINKED ISSUE #1604: Double logging to syslog and stdout/stderr?
Why are conmon logs written to both stdout/stderr and syslog?  When run via systemd, won't this result in double the log output?

https://github.com/kubernetes-incubator/cri-o/blob/master/conmon/conmon.c#L142

### PR DESCRIPTION
**Pull request by mrunalp**
Fixes #1604 

@runcom @rhatdan @giuseppe PTAL

**- What I did**
Made logging to syslog optional.

**- How I did it**
Added a --syslog flag to conmon.

**- How to verify it**
We don't see double logging while using systemd cgroups.

**- Description for the changelog**
Add a --syslog flag to conmon.

### CODE REVIEW

**Comment by mheon** [comment]
I think we'll still want this for libpod/podman, at least initially. We lose the stdout/stderr streams across the double-fork so the only way of debugging some issues is syslog.

**Comment by mheon** [comment]
(Nothing against adding the flag, just tagging this so I can make appropriate changes in libpod once this lands)

**Comment by giuseppe** [comment]
LGTM

**Comment by mrunalp** [comment]
@portante Thanks for the review!

**Comment by rhatdan** [comment]
LGTM
Is Kata still broken?

**Comment by runcom** [comment]
looks so, LGTM

**Pull request merged**
