### PR TITLE
Fix propagation test

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom This fixes the mount propagation tests. Cherry pick into #947.

### CODE REVIEW

**Comment by runcom** [comment]
Fo we need this for 1.0 though?

**Comment by runcom** [comment]
*do

**Comment by runcom** [comment]
pushed to 1.8 PR - I'll leave this open, maybe we need it in master/1.0

**Comment by mrunalp** [comment]
Yeah we can get in whatever still applies to 1.7.x

**Comment by mrunalp** [comment]
This doesn't apply to 1.0 branch so closing it.

**Comment by mrunalp** [comment]
Closing this as it doesn't apply to `release-1.0` branch.

**Pull request closed without merging**
