### PR TITLE
remove kpod-push.1.md from wrong directory.

### PR DESCRIPTION
**Pull request by rhatdan**
Their is a kpod-push.1.md man page in docs directory.
This is a bogus location.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Something is broken in the test suite.  This patch should definitely not break anything.

**Comment by mheon** [comment]
Looks like unrelated flakes in Travis - errors fetching packages from the Debian repos.

**Comment by mrunalp** [comment]
I have restarted the flakes.

**Comment by rhatdan** [comment]
@mrunalp Still broken.  :^(

**Comment by mrunalp** [comment]
Restarted. I guess we will have to keep on kicking this till travis networking issues are resolved.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
