### PR TITLE
move kpod logic into libkpod/image

### PR DESCRIPTION
**Pull request by 14rcole**
Move all of the image-related logic for the kpod commands that have been merged into master thus far and move them into libkpod/image package.  This way the functions can be used not only by other kpod commands, but by other tools

### CODE REVIEW

**Comment by rhatdan** [comment]
@14rcole Rebase again...

**Comment by rhatdan** [comment]
Fails to compile.

**Comment by mrunalp** [comment]
This looks fine. @runcom PTAL.

**Comment by runcom** [comment]
LGTM but needs rebase

**Comment by rhatdan** [comment]
@14rcole Another rebase.

**Comment by 14rcole** [comment]
I ended up going back and redoing the refactor because I reached a point in which I was making the code buggier and harder to understand.  This should be fixed now

**Comment by 14rcole** [comment]
@rhatdan @runcom @mrunalp Two things are currently failing.  One is a lint check in the libkpod/image package saying I should rename the ImageData struct to Data.  However, this struct has a counterpart called ContainerData in libkpod (both are used for inspecting containers/images).  If I change the name to follow the linting procedures, these two won't be as clearly linked?  Should I change the name?  If so, should I change the name of ContainerData to Data as well, despite the ambiguity this would cause?  OR should I do something else?

**Comment by rhatdan** [comment]
@nalind @mrunalp WDYT?

Could we just call them Image and Container?

**Comment by mheon** [comment]
Container is a really bad name, considering we already have a Container struct in the OCI package. I'm not really convinced that the original names are bad, either - my vote would be in favor of ignoring the golint warnings, and possibly even disabling that category of warning.

**Comment by rhatdan** [comment]
I am fine with that, is there a way to tell lint to ignore warnings for a specify .go file?  Or for a specific name?  Or do we need to disable the check altogether?

**Comment by mheon** [comment]
There is no way to do a per-file or single instance ignore in Golint right now, so it looks like we'd need to disable the package name duplication check.

**Comment by mrunalp** [comment]
I have seen directives in other projects for disabling lint on specific lines. I'll take a look to see if we can do something similar.

**Comment by mrunalp** [comment]
Try adding a comment similar to:
```
your code // nolint: errcheck
```

**Comment by mrunalp** [comment]
For a declaration the syntax seems to be:
```
// nolint
--
type myType struct {

```

**Comment by rhatdan** [comment]
Nice.

**Comment by mrunalp** [comment]
Needs rebase now

**Comment by mrunalp** [comment]
Also, there is another lint error:
```
 make lint
checking lint
libkpod/common/common.go:80:5:warning: should use !strings.Contains(creds, ":") instead (S1003) (megacheck)
```

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
@runcom PTAL

**Comment by runcom** [comment]
LGTM

**Pull request merged**
