### PR TITLE
Vendor in latest containers/storage

### PR DESCRIPTION
**Pull request by umohnani8**
Fixes store.lock issue comming up when using store.Names

Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@rhatdan @nalind @mrunalp PTAL

**Comment by rhatdan** [comment]
I think we need this patch to fix this issue.

https://github.com/containers/storage/pull/105

**Comment by rhatdan** [comment]
@umohnani8 Merged in fixes to containers/storage, could you update this pull request?

**Comment by umohnani8** [comment]
updated

**Comment by umohnani8** [comment]
[retest]

**Comment by umohnani8** [comment]
[retest]

**Comment by umohnani8** [comment]
@rhatdan tests passed!

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
