### PR TITLE
pkg: storage: image: get size from image ID

### PR DESCRIPTION
**Pull request by mrunalp**
Closes #859 
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by mrunalp** [comment]
[retest]

**Comment by mrunalp** [comment]
@runcom RHEL test failed with 
```
# time="2017-09-07 15:23:07.906801289-04:00" level=debug msg="failed to drop cap CAP_audit_read: CAP_CAP_AUDIT_READ is not supported on the current host" 
```
We need https://github.com/opencontainers/runtime-tools/pull/466 for that.

**Comment by mrunalp** [comment]
[retest]

**Comment by mrunalp** [comment]
Rebased.

**Comment by mrunalp** [comment]
[retest]

**Pull request merged**
