### PR TITLE
Add Initial networking BATs

### LINKED ISSUE #238: need a way to test CNI networks
Can't do that right now because we run tests locally only and w/o docker. We should be able to setup a docker container to run out tests on and mess with `/etc/cni|/opt/cni`. We should also be able to configure those paths (in order to test other stuff maybe).

### LINKED ISSUE #266: Missing networking functional tests
We currently do not test networking at all with bats. We'd like to at least test the following use cases:

* Host network: verify that we're living in the right namespace when using the host network.
* Create a temporary CNI bridge plugin configuration and verify that:
   * We get an eth0 interface in the networking namespace, set with the correct IP
   * We can ping the host network back

And in order to do that we need to be able to pass a CNI configuration file directory to `ocicni` so that we can create temporary CNI files for the purpose of network testing.

### PR DESCRIPTION
**Pull request by sameo**
This PR includes 2 changes:

1. Add `--cni-config-dir` and `--config-plugin-dir` options to ocid, in order to specify where the CNI configuration and plugin binaries live. This is needed so that we can run BATs with temporarily created CNI configuration files.

2. Add 2 initial networking BATs where we test that the netns interface is using a valid CIDR and can be pinged from the host netns.

Next step is to add host networking tests, so that we can close #266.

### CODE REVIEW

**Comment by mrunalp** [comment]
Testing this now.

**Comment by runcom** [comment]
LGTM - tests run fine on my end.

**Comment by mrunalp** [comment]
@sameo This looks good! Was there anything else you wanted to add as part of this PR? Otherwise we can merge this and do follow-on PRs.

**Comment by sameo** [comment]
@runcom @mrunalp thanks for the review. I just rebased this PR. I was planning to add host networking tests and a couple more of netns related tests (Testing if 2 pods can ping each others, inter container ping, etc...).
I may push a new PR tomorrow, but I'm not sure yet. If you're happy with the current code, please go ahead and merge.

**Comment by runcom** [comment]
I'm fine merging this if you didn't have other commits ready, we'll add the rest in a follow-up I guess :+1:

**Pull request merged**
