### PR TITLE
[release-1.9] vendor: fix deps for release-1.9

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

Fix vendor.conf to use deps from upstream kube 1.9 release branch

**- How I did it**

vim & vndr

**- How to verify it**

check them out lol

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
@mrunalp PTAL

**Comment by mrunalp** [comment]
Looks fine. Will wait for tests :+1:

**Comment by rhatdan** [comment]
If this is final, will need to build a new package from Rawhide.

**Comment by runcom** [comment]
> If this is final, will need to build a new package from Rawhide.

not final yet, just following what kube does (branched out for 1.9 from master, master now tracks 1.10)

**Pull request merged**
