### PR TITLE
server: set golang runtime max threads

### PR DESCRIPTION
**Pull request by runcom**
SetMaxThreads from runtime/debug in Golang is called to set max threads
value to 90% of /proc/sys/kernel/threads-max
Should really help performance. Same setting as in Docker.

@mrunalp @rhatdan PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
Asked Sebastian to do a perf run on this.

**Comment by runcom** [comment]
Awesome, regardless, I think we should get this in

**Comment by runcom** [comment]
:tada:

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
