### PR TITLE
Add information on kpod login/logout

### PR DESCRIPTION
**Pull request by rhatdan**
Add video for kpod-export

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@umohnani8 @mheon PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
Since this is just changes to docs and man pages, I am merging without E2E tests.

**Pull request merged**
