### PR TITLE
serve grpc and http on the same socket

### PR DESCRIPTION
**Pull request by runcom**
it wasn't actually possible to serve grpc and http on the same socket. This patch modifies code to make it possible.

@mrunalp PTAL, needed by cadvisor handler

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
This should go in asap

**Comment by runcom** [comment]
This https://github.com/google/cadvisor/pull/1741 is now based on this, so please merge

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
