### PR TITLE
test: Test for OOM condition in a loop

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
oom is still failing.  :^(

**Comment by runcom** [comment]
It passed in #1054

**Comment by TomSweeneyRedHat** [comment]
With happy tests, LGTM

**Comment by mrunalp** [comment]
@stevekuznetsov Did we by any chance either change the base of RHEL ami or change the type of instances that we run the tests on? Reason for asking is that OOM test is not completing in even 10 minutes when it used to 100 seconds last tim e we bumped up the timeout for it.

**Comment by stevekuznetsov** [comment]
The size of the instances has not changed. The AMI jobs are here: https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_crio/

Can you constrain how much memory is available using `cgroups` or similar so you don't worry about what system you're running on?

**Comment by rhatdan** [comment]
Is this problem caused by the swap patch that @cevich added?  And we are just swapping?

**Comment by mrunalp** [comment]
@rhatdan Let me look into that. That could explain this.

**Comment by mrunalp** [comment]
@rhatdan Created #1058 to check.

**Pull request merged**
