### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
recompessing -> recompressing

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
As an aside, the existence of this file seems to disagree with the top-level README of this project, which claims that "Building, signing and *pushing* images to various image storages" (emphasis mine) is out of scope.

**Comment by rhatdan** [comment]
@jonjohnsonjr You need to sign the agreement and your contribution.  I think the statement on focus should emphasize "building", we leave that the to eh Buildah project.
https://github.com/projectatomic/buildah

**Comment by jonjohnsonjr** [comment]
Eh, too much red tape to fix a typo ;)

Cheers

**Comment by rhatdan** [comment]
@jimmidyson Sorry about that, I encorporated your fix into a different pull request.  Thanks for reporting it.

**Pull request closed without merging**
