### PR TITLE
Fix SELINUXOPT handling

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://github.com/kubernetes-incubator/cri-o/pull/1363

**Comment by wking** [comment]
Wasn't this already fixed by #1367?

**Comment by rhatdan** [comment]
Nope the command -v was causing /sbin/selinuxenabled to be added to the commands.

**Comment by wking** [comment]
> Nope the command -v was causing /sbin/selinuxenabled to be added to the commands.

But #1367 added redirection to `/dev/null`, and that redirection works for me:

```console
$ command -v sh >/dev/null 2>&1
```

So #1363 added the `command -v` without redirection, which was buggy, and #1367 fixed that by adding `/dev/null` redirection.  I don't think we need anything more, but if we do, can you provide a command to reproduce your issue on master?

**Comment by rhatdan** [comment]
My understanding is 
command selinuxenabled
Will execute selinux enabled if it exists and will exit with failure if it does not.  It will print an error which is removed by 2>/dev/null
No reason to run selinuxenabled a second time.
@runcom shows in the other PR that that PR was blowing things up.

**Comment by runcom** [comment]
I've also fixed that, the build now goes well even without this PR

**Comment by wking** [comment]
> No reason to run selinuxenabled a second time.

Ah, that's reasonable.  Currently master is only running `command -v …` once and `selinuxenabled` once, but I agree that we can just fire `selinuxenabled` and ignore any “command not found” errors.  I don't think we need to [suppress shell function lookup][1] with `command selinuxenabled`, though.  How about:

```makefile
SELINUXOPT ?= $(shell selinuxenabled 2>/dev/null && echo -Z)
```

[1]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html

**Comment by rhatdan** [comment]
Yes that works best.  Lets get this merged and move on.

**Comment by runcom** [comment]
LGTM

**Pull request merged**
