### PR TITLE
[DO NOT MERGE, JUST TESTING]*: update kube vendor to v1.7

### PR DESCRIPTION
**Pull request by runcom**
This PR is just meant for CI testing.

This PR stands on a `release-1.7` branch here in CRI-O's repo for anyone to test :)

(missing this commit from old #510 but we don't need it now https://github.com/kubernetes-incubator/cri-o/pull/510/commits/3ec20bd5ca9829d4b1881c02a93eed07c5933c38)

@mrunalp @rhatdan PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
we'll also need this commit at some point https://github.com/kubernetes-incubator/cri-o/pull/511/commits/fe8442be1acd2eb02ee2cfe570aa87efe4db001d along with implementing `ContainerStats` and `ListContainerStats` APIs

**Comment by runcom** [comment]
retest

**Comment by runcom** [comment]
alright tests passed in CI - the Fedora failure is unrelated plus the 120/121 is a known issue for which we should carry a patch (and we do it on master) :)

**Comment by mrunalp** [comment]
Nice! :)

**Comment by runcom** [comment]
retest

**Comment by runcom** [comment]
mmm fedora failure seems related actually

**Comment by runcom** [comment]
retest

**Pull request closed without merging**
