### PR TITLE
Tell oci-umount where to remove mountpoints inside container

### PR DESCRIPTION
**Pull request by rhatdan**
This patch set add crio-umount.conf file which tells oci-umount plugin
to look for leaked mount points in /var/lib/containers/storage/* and
/var/run/containers/*

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
This patch should not go in, until https://github.com/projectatomic/oci-umount/pull/19 is approved.

**Comment by mrunalp** [comment]
Looks fine. @rhvgoyal PTAL.

**Comment by rhatdan** [comment]
@mrunalp @runcom The oci-umount was updated, this should go into rc3.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
