### PR TITLE
bump to 1.8

### LINKED ISSUE #879: Update to kube 1.8
Tracking changes from upstream kube 1.8 release branch https://github.com/kubernetes/kubernetes/commits/release-1.8/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto (and look also what's happening in the dockershim https://github.com/kubernetes/kubernetes/commits/release-1.8/pkg/kubelet/dockershim):

- ~~no_new_privs https://github.com/kubernetes-incubator/cri-o/issues/869~~
- ~~localhost seccomp profile https://github.com/kubernetes-incubator/cri-o/issues/202~~
- ~~update container resources~~
- ~~mount propagation~~
- ~~**container stats, imagefs info?** probably 1.9? we have cadvisor for now~~
- ~~correctly stop the streaming server https://github.com/kubernetes-incubator/cri-o/pull/852/files#diff-702431da3a2e35392cf253955d15f774R145~~
- ???

### PR DESCRIPTION
**Pull request by runcom**
Initial PR to test out 1.8 :)

Tackling #879 - not everything from there has been implemented yet though!

Close #879
Close https://github.com/kubernetes-incubator/cri-o/issues/869
Close https://github.com/kubernetes-incubator/cri-o/issues/202

Do not merge this, I'll create a separate branch on origin once this is finished.

@mrunalp PTAL :)

### CODE REVIEW

**Comment by runcom** [comment]
alrighty, moved tests to kube 1.8 as well

**Comment by runcom** [comment]
@mrunalp this is finished now :tada: PTAL commit by commit

**Comment by runcom** [comment]
is RHEL still busted for integration and e2e?

Fedora integration works fine, I see guestbook (2) tests failing on Fedora and other 2 I'm fixing. @mrunalp are the guestbook tests known issue right?

**Comment by mrunalp** [comment]
We can rebase and run the ami test on this now.

**Comment by runcom** [comment]
@mrunalp rebased

**Comment by runcom** [comment]
This is now tracking upstream v1.8.0 :)

**Comment by runcom** [comment]
integration tests are failing because they don't use the correct `crictl` version as found in `contrib/test/integration/build/cri-tools.yml`, @mrunalp how do I update the tests to use that? /test ami?

**Comment by runcom** [comment]
rebased

**Comment by runcom** [comment]
and also updated to kube 1.8.1

**Comment by rhatdan** [comment]
Yes lets get this merged.

**Comment by runcom** [comment]
removed DO NOT MERGE, let's get this merged now that we have a `release-1.0` branch

**Comment by runcom** [comment]
so this is blocked on #1016 as well

**Comment by runcom** [comment]
Ami isn't going to work before #1016

**Comment by rhatdan** [comment]
@runcom does this need to be rebased?

**Comment by runcom** [comment]
> @runcom does this need to be rebased?

not sure, but I've just force pushed after a rebase

**Comment by runcom** [comment]
@mrunalp it seems that the stuff failing are still because amis aren't using the fix froom #1016

**Comment by runcom** [comment]
wtf, ami_fedora is failing with:
```
2017/10/19 02:46:14 e2e.go:77: Calling kubetest --test -test_args=-host=https://172.18.3.51:6443 --ginkgo.focus=\[Conformance\] --report-dir=/tmp/artifacts...
unknown shorthand flag: 't' in -test_args=-host=https://172.18.3.51:6443 --ginkgo.focus=\[Conformance\] --report-dir=/tmp/artifacts
```
when trying to run e2e ...

**Comment by runcom** [comment]
nevermind, should be fixed now :)

**Comment by runcom** [comment]
@mrunalp looks like this is ready now :tada:

**Comment by runcom** [comment]
Looks like integration tests for sysctl must be fixed

**Comment by runcom** [comment]
We should now merge this one and continue 1.0 development on the `release-1.0` branch This is rebased and potentially ready to merge guys.

**Comment by runcom** [comment]
> We should now merge this one and continue 1.0 development on the release-1.0 branch This is rebased and potentially ready to merge guys.

oh well, but AMIs....

**Comment by mrunalp** [comment]
LGTM

**Comment by runcom** [comment]
we can merge this now :)

**Comment by runcom** [comment]
> we can merge this now :)

oh already done lol

**Comment by rhatdan** [comment]
So should we build cri-o 1.8 for Rawhide now?  And Ubuntu?

**Comment by runcom** [comment]
We'll tag cri-o 1.8 tomorrow, afterwards we'll build packages for ubuntu and rawhide

**Pull request merged**
