### PR TITLE
read image config from docker v2s1 manifests

### LINKED ISSUE #395: image: Image config is empty for gcr.io/google_containers/pause-amd64
When running `kubeadm` 1.7 on top of CRI-O, as a test for kubeadm tries to start a `dummy` pod where the pod is made of one single container. The latter is suppose to run the `gcr.io/google_containers/pause-amd64:3.0` image which happens to be a pause one:

```
ocic image status -id ff37f71df8d20abd11690fa791d3e29742a319caa3dc0e0d9d3fc1b976df73df
ID: ff37f71df8d20abd11690fa791d3e29742a319caa3dc0e0d9d3fc1b976df73df
Tag: gcr.io/google_containers/pause-amd64:latest
Tag: gcr.io/google_containers/pause-amd64:3.0
Tag: gcr.io/google_containers/pause-amd64
Size: 751477
```

Unfortunately, `pkg/storage/runtime:createContainerOrPodSandbox()` gets an empty blob for that image. When adding some debug to [createContainerOrPodSandbox](https://github.com/kubernetes-incubator/cri-o/blob/master/pkg/storage/runtime.go#L218), we see that `len(configBlob)` is 0 for that specific image.

`docker inspect` on a `gcr.io/google_containers/pause-amd64` gives:

```
[
    {
        "Id": "sha256:99e59f495ffaa222bfeb67580213e8c28c1e885f1d245ab2bbe3b1b1ec3bd0b2",
        "RepoTags": [
            "gcr.io/google_containers/pause-amd64:3.0"
        ],
        "RepoDigests": [
            "gcr.io/google_containers/pause-amd64@sha256:163ac025575b775d1c0f9bf0bdd0f086883171eb475b5068e7defa4ca9e76516"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2016-05-04T06:26:41.522308365Z",
        "Container": "a9873535145fe72b464d3055efbac36aab70d059914e221cbbd7fe3cac53ef6b",
        "ContainerConfig": {
            "Hostname": "95722352e41d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ENTRYPOINT \u0026{[\"/pause\"]}"
            ],
            "Image": "f8e2eec424cf985b4e41d6423991433fb7a93c90f9acc73a5e7bee213b789c52",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/pause"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "1.9.1",
        "Author": "",
        "Config": {
            "Hostname": "95722352e41d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "f8e2eec424cf985b4e41d6423991433fb7a93c90f9acc73a5e7bee213b789c52",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/pause"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 746888,
        "VirtualSize": 746888,
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:41ff149e94f22c52b8f36c59cafe7538b70ea771e62d9fc6922dedac25392fdf",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"
            ]
        }
    }
]

```

### PR DESCRIPTION
**Pull request by runcom**
Fix #395 

@sameo could you test this patch out and see if it fixes the issue for you? This is still blocked on containers/image#259

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by sameo** [comment]
@runcom Will test it today, sorry for the lag.

**Comment by sameo** [comment]
@runcom with this PR and the following patch:

https://gist.github.com/sameo/dbb86800472f57f5333c31acfc07dcb0

I can deploy my k8s cluster and the pause image config no longer seems to be empty.
So this PR fixes #395 for me.

**Comment by runcom** [comment]
@sameo PTAL at the latest commit (maybe re-testing everything out if it's not an hassle for you)

**Comment by sameo** [comment]
@runcom Re-tested with the 2 commits from your branch and it still works fine.

**Comment by sameo** [comment]
LGTM

**Comment by runcom** [comment]
This is ready to review and merge @mrunalp

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
