### PR TITLE
[release-1.9] oci: avoid race on container stop

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

@sboeuf @mrunalp PTAL

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
@rhatdan @mrunalp this is green

**Comment by rhatdan** [comment]
LGTM

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
