### PR TITLE
vendor: update containers/image to HEAD

### PR DESCRIPTION
**Pull request by vbatts**
fixes needed for cross-platform are now in containers/image HEAD

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
is this supposed to be merged Vincent? I see vendor: DELETEME commits

**Comment by vbatts** [comment]
yes merge please. I have a commit that is for _me_ to delete from my branch, once this is merged! :grimacing:

**Comment by rhatdan** [comment]
All Green.

**Pull request merged**
