### PR TITLE
[wip] Vendor in latest container/storage

### PR DESCRIPTION
**Pull request by rhatdan**
This container/storage will mount /run/containers/storage as a
private mount so that cri-o stops leaking shm mountpoints in to the
hosts namespace.  Will also fix issues with oci-umount cleaning up
mount points.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
:+1: will wait for tests.

**Comment by runcom** [comment]
:+1: but Travis failing

**Comment by rhatdan** [comment]
@nalind What do you think. I think the issue here is the bind mount on /run/containers/storage is still active.

**Comment by rhatdan** [comment]
@nalind I think we should ignore the error for unmount, or at least ignore it if you get an ebusy?

**Comment by rhatdan** [comment]
@nalind Any idea why rename is failing?

**Comment by rhatdan** [comment]
The reason this is WIP, is that we are umounting /run/containers/storage even if we did not mount it.  Not sure what is the best way to handle this.
One option was not to umount it, this would mean you would always have /run/containers/storage mounted even if no tools are using it.
Another option is to add a storage flag to clean it up.  This would allow us to pass the CRI-O Tests that are going to blow up since there is a mount point left over if we did not umount it.

**Comment by rhatdan** [comment]
[retest]

**Comment by rhatdan** [comment]
@nalind Looks like this passed the tests.  Now we need to investigate if we can clean up the leaked mount points.

**Comment by rhatdan** [comment]
No longer needed.

**Pull request closed without merging**
