### PR TITLE
oci: fixes to properly handle container stop action

### PR DESCRIPTION
**Pull request by runcom**
@mrunalp PTAL follow-up of #1010 

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
This failure is new to me:
```
# time="2017-10-16 05:56:47.695518849Z" level=error msg="Container creation error: container_linux.go:295: starting container process caused "two checks on same syscall argument"
```
@mrunalp @rhatdan @sameo have you ever seen that?

**Comment by cyphar** [comment]
"device or resource busy" on a memcg write can be caused by a variety of things. I believe trying to set a memory limit after processes have already joined a cgroup that didn't have memory limits before will trigger it (but I might be mistaken).

**Comment by mheon** [comment]
@runcom I think that was me - https://github.com/opencontainers/runc/pull/1424 just merged last night, assuming you're running runc master. Your Seccomp profile has a clause in it somewhere that checks a syscall argument more than once in a single rule. This never worked right, and now it's reporting that fact. Could probably do with making the error messages a bit better, though.

**Comment by mheon** [comment]
No idea about the RHEL one, though. Pretty sure that wasn't me.

**Comment by runcom** [comment]
@mheon the CI is failing and it must not use runc master so I can't see how your PR broke us from runc master, @mrunalp @cevich are we using runc master in CI?

**Comment by mheon** [comment]
@runcom 99% sure that error message is not possible before my PR landed, though

**Comment by runcom** [comment]
> @runcom 99% sure that error message is not possible before my PR landed, though

then we must be doing something wrong in the CI :)

**Comment by runcom** [comment]
Damn :) https://github.com/kubernetes-incubator/cri-o/blob/master/contrib/test/integration/build/runc.yml we arent' using a fixed version. I'll fix that.

**Comment by runcom** [comment]
> Damn :) https://github.com/kubernetes-incubator/cri-o/blob/master/contrib/test/integration/build/runc.yml we arent' using a fixed version. I'll fix that.

@mheon can you work to fix that error with runc master meanwhile?

**Comment by mheon** [comment]
@runcom Sure, I think it can safely be turned into a warning. Should also look into fixing the profile (I think we source from Docker?) - if it does that it's never worked as advertised.

**Comment by runcom** [comment]
opened #1016

**Comment by runcom** [comment]
THis is also not using the new amis :confused: /cc @mrunalp

**Comment by cevich** [comment]
FWIW: slash-test ami will rebuild the imges, then run both e2e and integration tests.  Doing slash-test <something else> will not (it'll use the "old" cached AMIs).  The cached AMI's get rebuild daily from master, though it should also rebuild every time master changes - I've got on my list to work with steve on this.  Until then, I also have the power to rebuild the AMI's (from master), on demand, so just ping me.

**Comment by mrunalp** [comment]
@cevich Can you rebuild the amis from master and mark them ready?

**Comment by cevich** [comment]
@mrunalp I hit the "build" button.  Jobs running:

https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_crio/45/

https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_fedora_crio/33/

**Comment by cevich** [comment]
@mrunalp okay, I think I got it.  ami-b49f4fce and ami-38835342 are both marked ready (Though the RHEL one failed to do so automatically for some reason?)

**Comment by mrunalp** [comment]
@runcom Once this passes, we should also create a PR for the release-1.0 branch.

**Comment by mrunalp** [comment]
LGTM

**Comment by runcom** [comment]
> @runcom Once this passes, we should also create a PR for the release-1.0 branch.

https://github.com/kubernetes-incubator/cri-o/pull/1033

**Pull request merged**
