### PR TITLE
Add HOSTNAME env var to container

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

- What I did
Added HOSTNAME to container env variables.

- How to verify it
Start a pod and env | grep HOSTNAME

- Description for the changelog
Add HOSTNAME environment variable to containers in the pod.

### CODE REVIEW

**Comment by runcom** [comment]
LGTM, worth an integration test!

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mrunalp** [comment]
Added test.

**Comment by rhatdan** [comment]
LGTM if this is required.
/test all

**Pull request merged**
