### PR TITLE
dep: Update containers/image to 1c202c5d85d2ee531acb1e91740144410066d19e

### PR DESCRIPTION
**Pull request by mrunalp**
@nalind @runcom PTAL

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
Cool, thanks @mrunalp

**Comment by mrunalp** [comment]
Still seeing an issue with local tests. I have opened #354 for that.

**Comment by runcom** [comment]
Alright, should we merge this though?

**Comment by mrunalp** [comment]
@runcom Yes, because it definitely improves over status quo.

**Pull request merged**
