### PR TITLE
contrib: test: integration: enable more e2e kube tests

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
The only real test failing is just:
```
[Fail] [sig-cli] Kubectl client [k8s.io] Simple pod [It] should support inline execution and attach
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:512
```
which can be easily reproduced with local-up-cluster and:
```
echo abcd1234 | k run test-4 --image=busybox --restart=OnFailure --attach=true --leave-stdin-open=true --stdin -- sh -c "cat && echo 'stdin closed'"
```
The command above should not print `stdin closed` so maybe a bug in conmon @mrunalp

**Comment by runcom** [comment]
note to self, we need to switch release-1.7, release-1.8 and release-1.9 once we merge this

**Comment by runcom** [comment]
This should just fail on #1217 now :)

**Comment by runcom** [comment]
Just one failure indeed :tada:

**Comment by runcom** [comment]
As said, we will be at full coverage after #1217

**Comment by runcom** [comment]
we can merge this once tests are green :)

**Comment by runcom** [comment]
seems like the openshift CI is down :( https://ci.openshift.redhat.com/jenkins/job/test_pull_request_crio_e2e_rhel/

**Comment by runcom** [comment]
pulled https://github.com/kubernetes-incubator/cri-o/pull/1229 to understand what's going on

**Comment by runcom** [comment]
Wtf

**Comment by runcom** [comment]
lemme re-run e2e again, seems like #1229 is actually helping here @mrunalp

**Comment by runcom** [comment]
One more time :) and we're good to go

**Comment by mrunalp** [comment]
Is this ready to merge?

**Comment by runcom** [comment]
@mrunalp yes, this is good to go now!

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
@runcom We should port the deadlock fix to 1.8.

**Comment by runcom** [comment]
> @runcom We should port the deadlock fix to 1.8.

backported to 1.8, 1.9 and 1.7

**Pull request merged**
