### PR TITLE
[release-1.9] vendor: update c/image to handle text/plain from registries

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

re-vendor c/image to pull in the fix about registries serving (wrongly) text/plain
This also bump to 1.9.6

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
@mrunalp PTAL this bump to 1.9.6 as well.

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
unit test failed in travis.

**Comment by runcom** [comment]
Looking

**Comment by runcom** [comment]
All green here again @mrunalp, let's get this merged to tag

**Pull request merged**
