### PR TITLE
Update vendored files for containers/image

### PR DESCRIPTION
**Pull request by 14rcole**
#656 Didn't update subpackages in containers/image, so these are the updates corresponding to the change in the vendor.conf file.

### CODE REVIEW

**Comment by runcom** [comment]
mmm what does this mean?

**Comment by runcom** [comment]
mmm you just have to `vndr github.com/containers/image`, didn't you?

**Comment by 14rcole** [comment]
When I submitted #656, I ran govendor instead of vndr, and it didn't update subpackages of containers/image such as containers/image/transport..  I ran vndr and this is a PR with the updated files

**Comment by runcom** [comment]
Tests fail though

**Comment by 14rcole** [comment]
It looks like the updated containers/image repo introduced a dependency on ostreedev/ostree-go, which requires the PKG_CONFIG_PATH to be set.  Now I'm getting the error

```
# pkg-config --cflags ostree-1 ostree-1 ostree-1 ostree-1 ostree-1 ostree-1
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
pkg-config: exit status 1
```
When I run `make integration`.  How do I resolve this?

**Comment by rhatdan** [comment]
You need ostree-devel installed.  I think this needs to be added to .travis.yml

**Comment by rhatdan** [comment]
Also need to add it to Dockerfile and the README.md

**Comment by rhatdan** [comment]
I just searched for where libdevemapper-devel was used.

```
 grep -r libdevmapper-dev .
./.travis.yml:  - sudo apt-get -qq install btrfs-tools libdevmapper-dev libgpgme11-dev libapparmor-dev libseccomp-dev
./Dockerfile:    libdevmapper-dev \
./README.md:  libdevmapper-dev \
```

**Comment by rhatdan** [comment]
@nalind is attempting to deal with these same issues in https://github.com/kubernetes-incubator/cri-o/pull/654

**Pull request closed without merging**
