### PR TITLE
Makefile: fix the creation of man5

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by vbatts** [comment]
I signed it!

**Comment by mrunalp** [comment]
LGTM

**Comment by vbatts** [comment]
(pushed again to try an kick the travis build...)

**Comment by runcom** [comment]
```

not ok 22 ocic runtimeversion
# (from function `ocic' in file ./helpers.bash, line 59,
#  in test file ./runtimeversion.bats, line 11)
#   `ocic runtimeversion' failed
# time="2016-12-08T20:13:04Z" level=warning msg="default configuration file does not exist: /etc/ocid/ocid.conf" 
# time="2016-12-08 20:13:04.453108806Z" level=info msg="Starting reaper" 
# E1208 20:13:04.453653    2044 ocicni.go:136] error updating cni config: No networks found in /etc/cni/net.d
# time="2016-12-08 20:13:04.455096799Z" level=debug msg="sandboxes: map[]" 
# time="2016-12-08 20:13:04.455134116Z" level=debug msg="containers: &{map[] {{0 0} 0 0 0 0}}" 
# time="2016-12-08 20:13:04.534617916Z" level=debug msg="Reaped process with pid 2164, exited with status 0" 
# time="2016-12-08T20:13:04Z" level=fatal msg="Getting the runtime version failed: rpc error: code = 2 desc = `/usr/local/bin/runc -v` failed:  (wait: no child processes)" 
```
flaky test is flaky (somehow) - merging

**Pull request merged**
