### PR TITLE
Add HOSTNAME env var to container

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

**- What I did**
Added HOSTNAME to container env variables.

**- How to verify it**
Start a pod and env | grep HOSTNAME

**- Description for the changelog**
Add HOSTNAME environment variable to containers in the pod.

### CODE REVIEW

**Comment by mrunalp** [comment]
@runcom @rhatdan PTAL

**Comment by runcom** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
Does Kubernetes require HOSTNAME environment variable to be set?  Or is this a Docker thing?

**Comment by mrunalp** [comment]
@rhatdan Just matching what docker does. QE had a test for it.

**Comment by mrunalp** [comment]
We are hitting the issue with go tip gofmt complaining :/

**Comment by mrunalp** [comment]
Pushed a fix for the tests.

**Pull request merged**
