### PR TITLE
restore lost cni-plugin option

### PR DESCRIPTION
**Pull request by edsantiago**
Commit d5b5028c undid part of my pr#953 (cni plugin path). Restore it.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
I cannot diagnose these failures. `e2e_fedora` seems to be failing in `hack/e2e.go` but its stdout/stderr (logged to `/tmp/artifacts/e2e.log`) are nowhere to be found. `integration_fedora`, I have no idea. It looks like a timeout, but if so I can't tell where. Am I looking at oh-yeah-those-are-known-problems, or have I really introduced a bug?

**Comment by rhatdan** [comment]
I don't think you introduced this bug.

**Comment by rhatdan** [comment]
This is the bad version of runc error @mrunalp 
http://www.the60sofficialsite.com/images/antenna%20-%20My%20Favorite%20Martian.jpg

**Comment by rhatdan** [comment]
@edsantiago I find the output bu going to the Details screen, then clicking jenkens artifacts and finding it on s3.

**Comment by edsantiago** [comment]
AHA! Thanks, @rhatdan , the key was "S3". For benefit of the next poor soul (probably me again) who can't find it:

    Details
        > View job in Jenkins (near top center, white link on black background)
            > S3 Artifacts (left-hand column in Jenkins view)

The e2e error log helpfully tells me `main.go:260: Something went wrong` :-/

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
