### PR TITLE
Add missing steps in README

### PR DESCRIPTION
**Pull request by WeiZhang555**
The guideline in README doesn't work, one important step `#make` is
missing, so fix it.

Signed-off-by: Zhang Wei <zhangwei555@huawei.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
make install 

Should cause the make to happen. I thought we cleaned up make enough to fix this.

@cyphar @mrunalp @runcom Any reason not to?

**Comment by runcom** [comment]
@rhatdan that behavior has been removed with https://github.com/kubernetes-incubator/cri-o/commit/bb15f27eaec3913e45ede4ee4b99a375665e6bd1#diff-b67911656ef5d18c4ae36cb6741b7965 because I think I've explicitly asked to have `make install` not dependent on `make` and people should just use `make && sudo make install`. Reason being `make install` could require privileges.

**Comment by WeiZhang555** [comment]
Agree with @runcom , I also prefer `make install` not dependent on `make`, we can do `make` explicitly.

**Comment by rhatdan** [comment]
Ok I loose.   :^)

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
