### PR TITLE
enable RHEL k8s node-e2e tests

### PR DESCRIPTION
**Pull request by runcom**
@mrunalp PTAL

### CODE REVIEW

**Comment by mrunalp** [comment]
Seems to be an additional failure in Fedora now.
Also why only 67 tests ran on RHEL?

**Comment by runcom** [comment]
> Seems to be an additional failure in Fedora now.

```
  [1mshould test kubelet managed /etc/hosts file [Conformance][0m
  [37m/root/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/kubelet_etc_hosts.go:55[0m
[BeforeEach] [k8s.io] KubeletManagedEtcHosts
  /root/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:120
[1mSTEP[0m: Creating a kubernetes client
[1mSTEP[0m: Building a namespace api object
May 19 11:52:42.930: INFO: Skipping waiting for service account
[It] should test kubelet managed /etc/hosts file [Conformance]
  /root/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/kubelet_etc_hosts.go:55
[1mSTEP[0m: Setting up the test
[1mSTEP[0m: Creating hostNetwork=false pod
[1mSTEP[0m: Creating hostNetwork=true pod
[1mSTEP[0m: Running the test
[1mSTEP[0m: Verifying /etc/hosts of container is kubelet-managed for pod with hostNetwork=false
May 19 11:52:46.945: INFO: ExecWithOptions {Command:[cat /etc/hosts] Namespace:e2e-tests-e2e-kubelet-etc-hosts-td8bx PodName:test-pod ContainerName:busybox-1 Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
May 19 11:52:47.055: INFO: Exec stderr: ""
May 19 11:52:47.055: INFO: ExecWithOptions {Command:[cat /etc/hosts] Namespace:e2e-tests-e2e-kubelet-etc-hosts-td8bx PodName:test-pod ContainerName:busybox-2 Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
May 19 11:52:47.132: INFO: Exec stderr: ""
[AfterEach] [k8s.io] KubeletManagedEtcHosts
  /root/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:121
[1mSTEP[0m: Collecting events from namespace "e2e-tests-e2e-kubelet-etc-hosts-td8bx".
[1mSTEP[0m: Found 12 events.
May 19 11:52:47.135: INFO: At 2017-05-19 11:52:43 +0000 UTC - event for test-pod: {kubelet crio-int-prs-fedora-5nrbc.localdomain} Created: Created container with id 94b21b3a6d25202388709f19cccbe050650fb09c4e642d0636fe1446a1fe0310
May 19 11:52:47.135: INFO: At 2017-05-19 11:52:43 +0000 UTC - event for test-pod: {kubelet crio-int-prs-fedora-5nrbc.localdomain} Started: Started container with id 94b21b3a6d25202388709f19cccbe050650fb09c4e642d0636fe1446a1fe0310
May 19 11:52:47.135: INFO: At 2017-05-19 11:52:43 +0000 UTC - event for test-pod: {kubelet crio-int-prs-fedora-5nrbc.localdomain} Created: Created container with id 1836077a956ad4021b1c129950cbfa6b6b41a12473113673d681593434e1d665
May 19 11:52:47.135: INFO: At 2017-05-19 11:52:43 +0000 UTC - event for test-pod: {kubelet crio-int-prs-fedora-5nrbc.localdomain} Started: Started container with id 1836077a956ad4021b1c129950cbfa6b6b41a12473113673d681593434e1d665
May 19 11:52:47.135: INFO: At 2017-05-19 11:52:43 +0000 UTC - event for test-pod: {kubelet crio-int-prs-fedora-5nrbc.localdomain} Pulled: Container image "gcr.io/google_containers/netexec:1.7" already present on machine
May 19 11:52:47.135: INFO: At 2017-05-19 11:52:44 +0000 UTC - event for test-pod: {kubelet crio-int-prs-fedora-5nrbc.localdomain} Created: Created container with id 8fe79c2c062742338b2610bab767d948b9a02a4b668dd00969210bb37d25c90e
May 19 11:52:47.135: INFO: At 2017-05-19 11:52:44 +0000 UTC - event for test-pod: {kubelet crio-int-prs-fedora-5nrbc.localdomain} Started: Started container with id 8fe79c2c062742338b2610bab767d948b9a02a4b668dd00969210bb37d25c90e
May 19 11:52:47.135: INFO: At 2017-05-19 11:52:45 +0000 UTC - event for test-host-network-pod: {kubelet crio-int-prs-fedora-5nrbc.localdomain} Pulled: Container image "gcr.io/google_containers/netexec:1.7" already present on machine
May 19 11:52:47.135: INFO: At 2017-05-19 11:52:45 +0000 UTC - event for test-host-network-pod: {kubelet crio-int-prs-fedora-5nrbc.localdomain} Created: Created container with id 1c1baaec64d928747643727efb08006a8ee639055c4b303a4e3c5164889b7c35
May 19 11:52:47.135: INFO: At 2017-05-19 11:52:45 +0000 UTC - event for test-host-network-pod: {kubelet crio-int-prs-fedora-5nrbc.localdomain} Started: Started container with id 1c1baaec64d928747643727efb08006a8ee639055c4b303a4e3c5164889b7c35
May 19 11:52:47.135: INFO: At 2017-05-19 11:52:45 +0000 UTC - event for test-host-network-pod: {kubelet crio-int-prs-fedora-5nrbc.localdomain} Created: Created container with id b8ed3f9158e08d3a9b2c4f3194f33d23f46796e70dcfb51694d1920637730e1e
May 19 11:52:47.135: INFO: At 2017-05-19 11:52:45 +0000 UTC - event for test-host-network-pod: {kubelet crio-int-prs-fedora-5nrbc.localdomain} Started: Started container with id b8ed3f9158e08d3a9b2c4f3194f33d23f46796e70dcfb51694d1920637730e1e
May 19 11:52:47.137: INFO: POD                    NODE                                   PHASE    GRACE  CONDITIONS
May 19 11:52:47.137: INFO: test-host-network-pod  crio-int-prs-fedora-5nrbc.localdomain  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-05-19 11:52:44 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-05-19 11:52:46 +0000 UTC  }]
May 19 11:52:47.137: INFO: test-pod               crio-int-prs-fedora-5nrbc.localdomain  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-05-19 11:52:42 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-05-19 11:52:44 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-05-19 11:52:44 +0000 UTC  }]
May 19 11:52:47.137: INFO: 
May 19 11:52:47.138: INFO: 
Logging node info for node crio-int-prs-fedora-5nrbc.localdomain
May 19 11:52:47.139: INFO: Node Info: &Node{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:crio-int-prs-fedora-5nrbc.localdomain,GenerateName:,Namespace:,SelfLink:/api/v1/nodescrio-int-prs-fedora-5nrbc.localdomain,UID:672b14f5-3c89-11e7-b537-fa163e9df4ba,ResourceVersion:175,Generation:0,CreationTimestamp:2017-05-19 11:50:49 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{beta.kubernetes.io/arch: amd64,beta.kubernetes.io/os: linux,kubernetes.io/hostname: crio-int-prs-fedora-5nrbc.localdomain,},Annotations:map[string]string{volumes.kubernetes.io/controller-managed-attach-detach: true,},OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:NodeSpec{PodCIDR:,ExternalID:crio-int-prs-fedora-5nrbc.localdomain,ProviderID:,Unschedulable:false,Taints:[],},Status:NodeStatus{Capacity:ResourceList{cpu: {{4 0} {<nil>} 4 DecimalSI},memory: {{8371507200 0} {<nil>} 8175300Ki BinarySI},pods: {{110 0} {<nil>} 110 DecimalSI},},Allocatable:ResourceList{cpu: {{4 0} {<nil>} 4 DecimalSI},memory: {{8109363200 0} {<nil>} 7919300Ki BinarySI},pods: {{110 0} {<nil>} 110 DecimalSI},},Phase:,Conditions:[{OutOfDisk False 2017-05-19 11:52:39 +0000 UTC 2017-05-19 11:50:49 +0000 UTC KubeletHasSufficientDisk kubelet has sufficient disk space available} {MemoryPressure False 2017-05-19 11:52:39 +0000 UTC 2017-05-19 11:50:49 +0000 UTC KubeletHasSufficientMemory kubelet has sufficient memory available} {DiskPressure False 2017-05-19 11:52:39 +0000 UTC 2017-05-19 11:50:49 +0000 UTC KubeletHasNoDiskPressure kubelet has no disk pressure} {Ready True 2017-05-19 11:52:39 +0000 UTC 2017-05-19 11:50:49 +0000 UTC KubeletReady kubelet is posting ready status}],Addresses:[{LegacyHostIP 172.16.69.133} {InternalIP 172.16.69.133} {Hostname crio-int-prs-fedora-5nrbc.localdomain}],DaemonEndpoints:NodeDaemonEndpoints{KubeletEndpoint:DaemonEndpoint{Port:10250,},},NodeInfo:NodeSystemInfo{MachineID:744c760eb7614f95b774a2f066a4bf2c,SystemUUID:744C760E-B761-4F95-B774-A2F066A4BF2C,BootID:0f73f759-28f9-4f36-8773-edf07021f1f3,KernelVersion:4.8.6-300.fc25.x86_64,OSImage:Fedora 25 (Cloud Edition),ContainerRuntimeVersion:runc://1.0.0-rc3,KubeletVersion:v1.7.0-alpha.1.224+2899f47bc86695-dirty,KubeProxyVersion:v1.7.0-alpha.1.224+2899f47bc86695-dirty,OperatingSystem:linux,Architecture:amd64,},Images:[{[gcr.io/google-containers/stress:v1] 0} {[gcr.io/google_containers/busybox:1.24] 0} {[gcr.io/google_containers/busybox:latest] 0} {[gcr.io/google_containers/eptest:0.1] 0} {[gcr.io/google_containers/hostexec:1.2] 0} {[gcr.io/google_containers/liveness:e2e] 0} {[gcr.io/google_containers/mounttest-user:0.5] 0} {[gcr.io/google_containers/mounttest:0.8] 0} {[gcr.io/google_containers/netexec:1.4] 0} {[gcr.io/google_containers/netexec:1.5] 0} {[gcr.io/google_containers/netexec:1.7] 0} {[gcr.io/google_containers/nginx-slim:0.7] 0} {[gcr.io/google_containers/node-problem-detector:v0.3.0] 0} {[gcr.io/google_containers/pause-amd64:3.0] 0} {[gcr.io/google_containers/serve_hostname:v1.4] 0} {[gcr.io/google_containers/test-webserver:e2e] 0} {[gcr.io/google_containers/volume-gluster:0.2] 0} {[gcr.io/google_containers/volume-nfs:0.8] 0} {[docker.io/google/cadvisor:latest] 0} {[docker.io/kubernetes/pause:latest] 0}],VolumesInUse:[],VolumesAttached:[],},}
May 19 11:52:47.139: INFO: 
Logging kubelet events for node crio-int-prs-fedora-5nrbc.localdomain
May 19 11:52:47.139: INFO: 
Logging pods the kubelet thinks is on node crio-int-prs-fedora-5nrbc.localdomain
May 19 11:52:47.143: INFO: test-pod started at 2017-05-19 11:52:42 +0000 UTC (0+3 container statuses recorded)
May 19 11:52:47.143: INFO: 	Container busybox-1 ready: true, restart count 0
May 19 11:52:47.143: INFO: 	Container busybox-2 ready: true, restart count 0
May 19 11:52:47.143: INFO: 	Container busybox-3 ready: true, restart count 0
May 19 11:52:47.143: INFO: test-host-network-pod started at 2017-05-19 11:52:44 +0000 UTC (0+2 container statuses recorded)
May 19 11:52:47.143: INFO: 	Container busybox-1 ready: true, restart count 0
May 19 11:52:47.143: INFO: 	Container busybox-2 ready: true, restart count 0
W0519 11:52:47.144466    9541 metrics_grabber.go:74] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
May 19 11:52:47.237: INFO: 
Latency metrics for node crio-int-prs-fedora-5nrbc.localdomain
[1mSTEP[0m: Dumping a list of prepulled images on each node
May 19 11:52:47.238: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
[1mSTEP[0m: Destroying namespace "e2e-tests-e2e-kubelet-etc-hosts-td8bx" for this suite.
May 19 11:54:02.261: INFO: namespace: e2e-tests-e2e-kubelet-etc-hosts-td8bx, resource: bindings, ignored listing per whitelist

[91m[1mâ€¢ Failure [79.340 seconds][0m
[k8s.io] KubeletManagedEtcHosts
[90m/root/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:656[0m
  [91m[1mshould test kubelet managed /etc/hosts file [Conformance] [It][0m
  [90m/root/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/kubelet_etc_hosts.go:55[0m

  [91mfailed to execute command in pod test-pod, container busybox-2: unable to upgrade connection: rpc error: code = 2 desc = error getting container state for e2e-tests-projected-2zsj5-annotationupdate8da957ba-3c89-11e7-8b30-fa163e9df4ba-0-client-container-0: exit status 1: "container \"e2e-tests-projected-2zsj5-annotationupdate8da957ba-3c89-11e7-8b30-fa163e9df4ba-0-client-container-0\" does not exist
"
  Expected error:
      <*errors.errorString | 0xc42118a690>: {
          s: "unable to upgrade connection: rpc error: code = 2 desc = error getting container state for e2e-tests-projected-2zsj5-annotationupdate8da957ba-3c89-11e7-8b30-fa163e9df4ba-0-client-container-0: exit status 1: \"container \\"e2e-tests-projected-2zsj5-annotationupdate8da957ba-3c89-11e7-8b30-fa163e9df4ba-0-client-container-0\\" does not exist\n\"",
      }
      unable to upgrade connection: rpc error: code = 2 desc = error getting container state for e2e-tests-projected-2zsj5-annotationupdate8da957ba-3c89-11e7-8b30-fa163e9df4ba-0-client-container-0: exit status 1: "container \"e2e-tests-projected-2zsj5-annotationupdate8da957ba-3c89-11e7-8b30-fa163e9df4ba-0-client-container-0\" does not exist
"
  not to have occurred[0m

  /root/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/exec_util.go:107
```
seems a race, the other is the well known projection API test which always fail

> Also why only 67 tests ran on RHEL?

ran just 67 because RHEL isn't fixed yet and times out

**Comment by runcom** [comment]
retest

**Comment by runcom** [comment]
narrowed the issue on node-e2e on RHEL down to a mount issue in RHEL itself.

**Comment by runcom** [comment]
alright, it seems it was a bug in kube actually https://github.com/kubernetes/kubernetes/issues/43534 which has been fixed by https://github.com/kubernetes/kubernetes/pull/43878/commits/d223c4be3735c652a33970fec385b7ef3d60c072. I'm re-kicking node-e2e now.

**Comment by runcom** [comment]
alright, the fix in kube https://github.com/kubernetes/kubernetes/commit/d223c4be3735c652a33970fec385b7ef3d60c072 isn't available at the point we're right now and we can't go to master because of #510 - I'm going to create a custom kube branch for testing at the point we're not plus the fix at https://github.com/kubernetes/kubernetes/commit/d223c4be3735c652a33970fec385b7ef3d60c072

after we merge #510 - everything should be in order and tests passing on RHEL as well :)

**Comment by runcom** [comment]
alright, node-e2e tests run fine on RHEL (even if there are some failures I'll take care of in a follow up)

@mrunalp please do review and merge this as it's done now
@sameo PTAL if you want also :)

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
