### PR TITLE
Update to the latest upstream API

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mpatel@redhat.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@runcom @feiskyer PTAL

**Comment by feiskyer** [comment]
LGTM in general, just a nit: it's better to split vendor and code in different commits.

**Comment by mrunalp** [comment]
@feiskyer That breaks tests and git bisect. Hence I have clubbed everything into the same commit.

**Comment by feiskyer** [comment]
@mrunalp Reasonable. LGTM

**Comment by mrunalp** [comment]
@runcom ping

**Comment by runcom** [comment]
LGTM

**Pull request merged**
