### PR TITLE
Bump up go versions in travis

### PR DESCRIPTION
**Pull request by mrunalp**
k8s master builds off go 1.9.x so we run
all tests for 1.9.x and build on 1.9.x, 1.10.x and tip.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but 1.10 has lint issues....

**Comment by wking** [comment]
On Wed, Jan 31, 2018 at 12:31:42AM +0000, Tom Sweeney wrote:
> Changes LGTM, but 1.10 has lint issues....

Those look like more than lint issues.  For example [1]:

  vendor/k8s.io/apimachinery/pkg/util/net/http.go:279:
  req.URL.Hostname undefined (type *url.URL has no field or method
  Hostname)

That looks more like “Travis' Go 1.10 is very broken” ;).

https://travis-ci.org/kubernetes-incubator/cri-o/jobs/335398015#L1122

**Comment by mrunalp** [comment]
Yeah, I am going to skip the 1.10 update for now and switch integration tests to 1.9.x. We can handle 1.10 separately.

**Comment by mrunalp** [comment]
Updated.

**Comment by rhatdan** [comment]
If travis passes we can merge without running E2E tests.

**Comment by mrunalp** [comment]
Passed. Merging.

**Pull request merged**
