### PR TITLE
fix typo for transfer.md

### PR DESCRIPTION
**Pull request by mdshuai**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mdshuai .  Thanks for catching this and fixing it.  The change itself LGTM, but Travis isn't happy.  It looks like some kind of spacing issue, but I'm not spotting it.  @runcom do you know what's up?

**Comment by rhatdan** [comment]
No we don't have a kpod cp, we only have kpod mount followed by copy in and out of the container.
Maybe we could put more text into the transfer.md man page.

man kpod cp
```
kpod(1)                                                                                    General Commands Manual                                                                                    kpod(1)

kpod-cp 1 August 2017 kpod
NAME
       kpod-cp - Copy files/folders between a container and the local filesystem.

Description
       We chose not to implement this feature in kpod even though the upstream docker project has it. We have a much stronger capability.  Using standard kpod-mount and kpod-umount, we can take advantage
       of the entire linux tool chain, rather then just cp.

       If a user wants to copy contents out of a container or into a container, they can execute a few simple commands.

       You can copy from the container's file system to the local machine or the reverse, from the local filesystem to the container.

       If you want to copy the /etc/foobar directory out of a container and onto /tmp on the host, you could execute the following commands:

              mnt=$(kpod mount CONTAINERID)
              cp -R ${mnt}/etc/foobar /tmp
              kpod umount CONTAINERID

       If you want to untar a tar ball into a container, you can execute these commands:

              mnt=$(kpod mount CONTAINERID)
              tar xf content.tgz -C ${mnt}
              kpod umount CONTAINERID

       One last example, if you want to install a package into a container that does not have dnf installed, you could execute something like:

              mnt=$(kpod mount CONTAINERID)
              dnf install --installroot=${mnt} httpd
              chroot ${mnt} rm -rf /var/log/dnf /var/cache/dnf
              kpod umount CONTAINERID

       This shows that using kpod mount and kpod umount you can use all of the standard linux tools for moving files into and out of containers, not just the cp command.

SEE ALSO
       kpod(1), kpod-mount(1), kpod-umount(1)

Dan Walsh                                                             kpod-cp - Copy content between container's file system and the host   
```

**Comment by TomSweeneyRedHat** [comment]
@rhatdan oh shoot, I forgot about that.  I'll touch up the transfer.md to strengthen that.  Perhaps that will help me remember next time.  I'm still curios why Travis wasn't happy with the change though.

**Comment by mdshuai** [comment]
@rhatdan As we don't have a kpod cp command, need we remove if from https://github.com/kubernetes-incubator/cri-o#commands ?

**Comment by rhatdan** [comment]
We have a man page, we should change the wording here to something like

kpod does not implement the `cp` command, but you can use the `mount` command which is much more powerful.  Man page describes the use.

**Comment by rhatdan** [comment]
https://github.com/kubernetes-incubator/cri-o/pull/936

**Comment by rhatdan** [comment]
@mdshuai updated the README, does that satisfy your issue?

**Comment by mdshuai** [comment]
@rhatdan The change looks better. thanks for your update.

**Pull request closed without merging**
