### PR TITLE
container_create: fixes

### PR DESCRIPTION
**Pull request by runcom**
**- What I did**

Various fixes, see commits

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by rhatdan** [comment]
Kubernetes does not allow a privileged container within a non privileged sandbox?  Does this prevent a user run running a privileged sidecar to monitor the primary container?

**Comment by runcom** [comment]
Last commit is fixing this BZ https://bugzilla.redhat.com/show_bug.cgi?id=1590733

**Comment by runcom** [comment]
> Kubernetes does not allow a privileged container within a non privileged sandbox? Does this prevent a user run running a privileged sidecar to monitor the primary container?

CRI doesn't allow that, the sandbox must be privileged to run any privileged contianers, see https://github.com/verb/kubernetes/blob/master/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L249-L250

**Comment by giuseppe** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM, assuming happy tests

**Comment by mrunalp** [comment]
we need port to 1.10.

**Pull request merged**
