### PR TITLE
sandbox_stop: Call CNI stop before stopping pod infra container

### PR DESCRIPTION
**Pull request by mrunalp**
#1425 ported to master.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@rhatdan this doesn't fix the kernel issue :/

**Comment by mrunalp** [comment]
I meant workaround :)

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
All Green.
Merging.

**Pull request merged**
