### PR TITLE
system_containers: Update mounts

### PR DESCRIPTION
**Pull request by mrunalp**
Make /var/lib rslave, add /var, add /opt and update mount propagations on other mounts.

@rhatdan @runcom @giuseppe PTAL

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM after Giuseppes comment

**Comment by rhatdan** [comment]
Do we need to do that now, or could we do this in a separate PR?  This PR Fixed the problem OpenShift had with the hang on evacuation of the node.  I would like to get this committed so we can continue testing, and then fix it up more in later PRs.

I actually believe that all of the subdirs of /var should be removed and only share /var rbind, rslave.  But we should do that in a later PR.  For now we want to change little to keep the OpenShift testing moving along.

**Comment by mrunalp** [comment]
Updated to remove OPT_CNI from manifest.json.

**Comment by giuseppe** [comment]
LGTM

**Pull request merged**
