### PR TITLE
Update containers/image

### PR DESCRIPTION
**Pull request by mtrmac**
... and include a new dependency, github.com/ulikunitz/xz .

This primarily includes a fix for storing schema1 images ( https://github.com/containers/image/pull/472 ), hopefully fixing #1725.

**- What I did**

Updated the version of containers/image

**- How I did it**

Edited the commit version of c/image in `vendor.conf`, and added a `github.com/ulikunitz/xz` line. Then I ran `vndr $thePackage` for both.

**NOTE**: The `vendor` subdirectory seems to be fairly out of sync with `vendor.conf` (e.g. CNI has a commit saying “update to 0.6”, but `vendor.conf` says 0.4).  I didn’t touch any of that; this PR changes the two listed packages only.

**- How to verify it**

I expect CRI-O test suite to validate this. `containers/image` has its own tests, of course;.

While this is targeted at #1725, it is not yet clear that this fixes it (#1725 does not contain enough information to tell for sure).

**- Description for the changelog**
Updated the containers/image library to fix inconsistencies in how schema1 and schema2 images are stored.

### CODE REVIEW

**Comment by mtrmac** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

Signed in as a Red Hat employee.

**Comment by jakolehm** [comment]
@mtrmac seems to fix #1725 👍

**Comment by mtrmac** [comment]
> @mtrmac seems to fix #1725 👍

Great, thanks for the confirmation.

**Comment by rhatdan** [comment]
Passes tests. Merging.

**Pull request merged**
