### PR TITLE
vendor: upgrade containers/storage

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM Thanks @runcom

**Comment by mrunalp** [comment]
Let us also run e2e node conformance on this one.

**Comment by runcom** [comment]
Alright, need to run `gofmt` - I'll fix this in a moment

**Comment by runcom** [comment]
But CI passes :tada:

**Comment by mrunalp** [comment]
k8s e2e passed.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
