### PR TITLE
split files under server/

### PR DESCRIPTION
**Pull request by runcom**
just moving files and functions around for better mental sanity..

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
pls, do not merge yet.

**Comment by runcom** [comment]
@mrunalp could you ack on the direction of this PR before I go further with `image.go` and `sandbox.go`

**Comment by mrunalp** [comment]
@runcom Looks good :+1:

**Comment by rhatdan** [comment]
Should you create a subdir of server/containers/*.go for all of the containers_*.go?  Then you could just have list.go, run.go ...

**Comment by runcom** [comment]
We could, I'd rather keep this in the same directory for without incurring
in any potential circular dependency though (and go will complain).

**Comment by runcom** [comment]
Dan, also, it makes little sense to create new packages (created with each subdirectory) since the CRI is a flat API right now and I'm just separating the API calls here (the rest is well separated under top level ./oci package for instance).

**Comment by rhatdan** [comment]
Ok, I was just complaining about the container_foobar namespace, just a thought, but the circular dependency problem is a good reason not to.

**Comment by mrunalp** [comment]
Yeah, go gets in the way of doing that :/

**Comment by runcom** [comment]
@mrunalp PTAL, ready to go

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
