### PR TITLE
hack/libdm_installed.sh: Add a test for libdevmapper.h

### PR DESCRIPTION
**Pull request by wking**
Avoid crashing `make` with:

    No package 'devmapper' found

by disabling the devmapper driver when the library it requires is not installed.  Also give the `libdm_no_deferred_remove` script a more specific name to avoid confusion.

### CODE REVIEW

**Comment by rhatdan** [comment]
/ok-to-test
LGTM

**Comment by wking** [comment]
The [CI error][1]:

    E0119 21:12:43.691734    4845 remote_runtime.go:187] CreateContainer in sandbox "ddb7458f7915806f20372e980a46c5f34e987fa0c8ff4da83bf8457bb021d994" from runtime service failed: rpc error: code = Unknown desc = container create failed: container_linux.go:296: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"failed to write 16823 to cgroup.procs: open /sys/fs/cgroup/pids/system.slice/crio-ee238a0dcb3bb75b23c1b62f147cd12b36372bf422e8ed2297105d08b4a84983.scope/cgroup.procs: no such file or directory\""
    Jan 19 21:12:43.691: INFO: Unexpected error occurred: rpc error: code = Unknown desc = container create failed: container_linux.go:296: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"failed to write 16823 to cgroup.procs: open /sys/fs/cgroup/pids/system.slice/crio-ee238a0dcb3bb75b23c1b62f147cd12b36372bf422e8ed2297105d08b4a84983.scope/cgroup.procs: no such file or directory\""

appears unrelated.  Maybe it's #1196?

[1]: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_crio_critest_rhel/29/consoleFull#-105893804558b6e51eb7608a5981914356

**Comment by mrunalp** [comment]
@wking Yes, it is most likely #1196. I'll check if we have runc bumped up here or make a PR to bump it up.
We can restart this test after all the tests are run. The e2e also have some flakes.

**Comment by mrunalp** [comment]
e2e_rhel failed with known flakes.

**Pull request merged**
