### PR TITLE
conmon: open+rename the log file instead of unlink+open

### PR DESCRIPTION
**Pull request by giuseppe**
**- What I did**
change the way the log file is replaced once it reaches the maximum size

**- How I did it**
I first create a new file, then rename it to the old one; instead of deleting the old one then creating a new one.

**- How to verify it**
tail -F $LOG_FILE will not warn with "$LOG_FILE has become inaccessible" when the log file is recreated.

**- Description for the changelog**
conmon will never leave the log file inaccessible.

### CODE REVIEW

**Comment by giuseppe** [comment]
Yes correct.  The effect of the `open+rename` is be the same as `unlink+open`.  The old file will be destroyed once the last reader closes it.

**Comment by TomSweeneyRedHat** [comment]
@giuseppe thanks for the confirmation.  Given that:
LGTM

**Comment by rhatdan** [comment]
Won't the rename fail, since the old file still exists?

**Comment by rhatdan** [comment]
Actually just read the man page, looks like rename is designed to do what you want.  Old file will just get removed.

**Comment by mrunalp** [comment]
Needs rebase for build fix.

**Comment by giuseppe** [comment]
rebased :arrow_up:

**Comment by rhatdan** [comment]
Finally passes.  Merging.

**Pull request merged**
