### PR TITLE
Add btrfs-progs-devel to list of required rpms

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
I have no problem adding this back, but the package is about to disappear.  So the build should handle it, and theoretically does.

**Comment by mrunalp** [comment]
@rhatdan I am debugging why the build failed in another VM. Meanwhile, this will make the tests operational while we figure that out.

**Comment by mrunalp** [comment]
I talked with @nalind. We want to set `exclude_graphdriver_btrfs` BUILDTAG when distro is RHEL/Centos. I will create a PR for that.

**Comment by mrunalp** [comment]
Closing as we merged #969 instead.

**Pull request closed without merging**
