### PR TITLE
Applying k8s kubelet v3 api to cri-o server

### PR DESCRIPTION
**Pull request by mzylowski**
After merging to master https://github.com/kubernetes/kubernetes/pull/39158 we need changes on server side  to talk with kubelet correctly.

This is beginning of required work.

cc @jjlakis @runcom @mrunalp

### CODE REVIEW

**Comment by mzylowski** [comment]
Ocid part looks good. I can deploy a k8s pod.
```
Name:                           tescior
Namespace:                      default
Node:                           127.0.0.1/127.0.0.1
Start Time:                     Fri, 27 Jan 2017 13:56:12 +0100
Labels:                         name=tescior
Status:                         Terminating (expires Fri, 27 Jan 2017 13:59:15 +0100)
Termination Grace Period:       30s
IP:
Controllers:                    <none>
Containers:
  nginx:
    Container ID:
    Image:              nginx
    Image ID:
    Port:               80/TCP
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-c95hl (ro)
    Environment Variables from: <none>
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True 
  Ready         False 
  PodScheduled  True 
Volumes:
  default-token-c95hl:
    Type:       Secret (a volume populated by a Secret)
    SecretName:     Optional:   %v

%!(EXTRA string=default-token-c95hl, bool=false)QoS Class:      BestEffort
Node-Selectors:                                                 <none>
Tolerations:                                                    <none>
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath           Type               Reason          Message
  ---------     --------        -----   ----                    -------------           --------   ------          -------
  4m            4m              1       {default-scheduler }                            Normal             Scheduled       Successfully assigned tescior to 127.0.0.1
  4m            4m              1       {kubelet 127.0.0.1}                             Normal             SandboxReceived Pod sandbox received, it will be created.
  3m            3m              1       {kubelet 127.0.0.1}     spec.containers{nginx}  Normal             Pulling         pulling image "nginx"
  2m            2m              1       {kubelet 127.0.0.1}     spec.containers{nginx}  Normal             Pulled          Successfully pulled image "nginx"
  2m            2m              1       {kubelet 127.0.0.1}     spec.containers{nginx}  Normal             Created         Created container with id 5a63209891404d43a524794ca57ab91e5b051ca8de139b52c35ed21805e35331
  2m            2m              1       {kubelet 127.0.0.1}     spec.containers{nginx}  Normal             Started         Started container with id 5a63209891404d43a524794ca57ab91e5b051ca8de139b52c35ed21805e35331
```

It's time to look at ocic.

**Comment by mrunalp** [comment]
Can you rebase to use dep? Thanks!

**Comment by mrunalp** [comment]
For bumping up to a specific revision, just change it in lock.json and then run `dep ensure`.

**Comment by mzylowski** [comment]
Rebased. 
With #352 vendoring is easy. New version of k8s is in vendor now.

Status: We can build project now, but there is still some issues with null pointers etc. Work is in progress.

**Comment by runcom** [comment]
@mzylowski tests passed in Travis but you have some issues with lint/gofmt:
```
0.15s$ make gofmt
!!! 'gofmt -s' needs to be run on the following files: 
./server/container_list.go
./server/sandbox_list.go
make: *** [gofmt] Error 1
The command "make gofmt" exited with 2.
25.34s$ make lint
checking lint
server/container_create.go:106::warning: cyclomatic complexity 61 of function (*Server).createSandboxContainer() is high (> 60) (gocyclo)
make: *** [lint] Error 1
```

**Comment by mzylowski** [comment]
@runcom Thanks! I was pretty sure there was some small things to fix when I pushed rebased code in friday midnight. I will fix lint and fmt in monady.

**Comment by mzylowski** [comment]
Lint and fmt fixed. All checks ok.

Fixes #339 

cc: @jjlakis @mrunalp @runcom

**Comment by runcom** [comment]
Awesome

**Comment by mrunalp** [comment]
Testing/reviewing. cc: @sameo @mikebrow PTAL

**Comment by mrunalp** [comment]
LGTM

**Comment by mikebrow** [comment]
Bit late but I have no issues LGTM

**Pull request merged**
