### PR TITLE
Add mark comments near all lines added by Ansible

### PR DESCRIPTION
**Pull request by cevich**
**- What I did**
    Update all ``lineinfile`` and similar tasks to also add a comment indicating the change came from Ansible, and from which specific YAML file.

**- How I did it**
    Use YAML line-folding syntax.

**- How to verify it**
    The CI tests won't puke if I did it right :smile:

### CODE REVIEW

**Comment by cevich** [comment]
# quick-check I didn't mess up the syntax

/test integration

**Comment by cevich** [comment]
Looks like I messed up the crio.conf changes.  Waiting for #1499 to merge, then I'll rebase this to use that.

**Comment by rhatdan** [comment]
Merging.

**Pull request merged**
