### PR TITLE
Fix Typo in cri-o README

### PR DESCRIPTION
**Pull request by mbssaiakhil**

### CODE REVIEW

**Comment by rhatdan** [comment]
You need to sign your pull request.

**Comment by runcom** [comment]
Please consider creating a Pull Request with 3 commits next time :) no need for 3 PRs.

As Dan said, you need to sign off your commit also...

**Comment by mbssaiakhil** [comment]
Thanks @rhatdan and @runcom, I have signed my commit, kindly review and merge. Sure, from next time I would raise a single PR for multiple commits :)

**Comment by rhatdan** [comment]
LGTM
@runcom Please merge no reason to wait for tests.

**Comment by rhatdan** [comment]
@mrunalp Please merge, no need to wait for/run tests.

**Pull request merged**
