### PR TITLE
cache sandbox's IP address

### PR DESCRIPTION
**Pull request by runcom**
We were always calling into net ns for each sandbox status call. These patches modify the code to store the IP on sandbox creation and return it on status calls. It also stores IP for containers and take care of showing it even when network comes from the host.

@mrunalp @sameo @derekwaynecarr  PTAL

### CODE REVIEW

**Comment by mrunalp** [comment]
This looks fine. Will wait for the tests.

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
kpod logs tests fail..... @rhatdan @mheon do you know what's happening?

**Comment by rhatdan** [comment]
LGTM
I don't see any failed logs in here?

**Comment by runcom** [comment]
> I don't see any failed logs in here?

I restarted it in the hope to see it green :)

**Comment by runcom** [comment]
Something is wrong with this patch set, I'll take a look

**Comment by runcom** [comment]
should be fixed now :)

**Comment by runcom** [comment]
[retest]

**Comment by mrunalp** [comment]
@cevich You can see the runs on this one.

**Comment by mrunalp** [comment]
@runcom The e2e failures are repeating so might be worth looking at.

**Comment by runcom** [comment]
[retest]

**Comment by TomSweeneyRedHat** [comment]
@runcom travis still isn't happy.  :^(

**Comment by runcom** [comment]
pushed another commit, we're now always grabbing IP on sandbox run and one of our network test was failing because it used a bash mock plugin which wasn't correctly setting up network with IP

**Comment by runcom** [comment]
alright, all fixed now, let's wait for CI and Travis (I'm gonna retrigger till green)

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by mrunalp** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
@cevich what's wrong with the CI?! https://atomic-e2e-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cri-o-integration-tests-prs/1388/PLATFORM=Fedora/console

why is the CI fetching the playbook from master?! I modified the playbook in this PR so it won't error, still it fetches the playbook from master? can we revert that? we need this PR asap and I just found this out, we need to test the CI with whatever playbook the PR's last commit has (like it was before the change to the CI jobs). Can you revert the changes to fetch the playbook from the PR commit?

**Comment by cevich** [comment]
@runcom IIRC, that was always the behavior.  However, I read your mind, and already put a change in to fix this.  It's going into testing now.

**Comment by mrunalp** [comment]
[develretest]

**Comment by runcom** [comment]
@mrunalp @cevich 

```
16:58:38 TASK [Copy plugin args so tests dont hang] *************************************
16:58:38 fatal: [10.8.168.201]: FAILED! => {"changed": true, "cmd": "cp test/plugin_test_args.bash /opt/cni/bin/", "delta": "0:00:00.003132", "end": "2017-09-01 20:58:37.509864", "failed": true, "rc": 1, "start": "2017-09-01 20:58:37.506732", "stderr": "cp: cannot stat 'test/plugin_test_args.bash': No such file or directory", "stderr_lines": ["cp: cannot stat 'test/plugin_test_args.bash': No such file or directory"], "stdout": "", "stdout_lines": []}
```
The above means the CI isn't grabbing the playbook from this PR commit (because that Task in the playbook is removed here. Also, you can see it's grabbing the playbook from master below:
```
16:47:53 + curl -o crio-integration-playbook.yaml https://raw.githubusercontent.com/kubernetes-incubator/cri-o/master/contrib/test/crio-integration-playbook.yaml
```
this is wrong, it should grab it from the PR commit. Is there any way we can fix this?

**Comment by runcom** [comment]
@cevich sorry to bother everytime though <3

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
seems like CI is still fetching the playbook from master

**Comment by runcom** [comment]
[retest]

**Comment by cevich** [comment]
@runcom Sorry for the confusion...the 'devel + retest' keyword should only trigger the 'crio-devel' job but the URL you posted was from a 'crio'  job.  It's possible the crio-devel job didn't trigger, I'll see if I can go hunt down why...I also asked Johnny to just merge the production change, since you asked for it.

**Comment by runcom** [comment]
Thanks Chris, I believe the best fix we can do actually is to trigger jobs only by a selected group of users instead of allowing everyone to change the playbook and run code in the CI, can we do that instead? One open a PR and it doesn't get tested till one of the maintainers sat "test"

**Comment by cevich** [comment]
...Johnny's merged the change into production, so in about 30-minutes it should start working (or everything will break 😄)

**Comment by cevich** [comment]
> One open a PR and it doesn't get tested till one of the maintainers sat "test"

My understanding (maybe wrong) is that only a select group of people may trigger by keyword.  We need that in all cases for security purposes.  Also because we don't have a 'cancel existing runs' feature (yet).

**Comment by cevich** [comment]
Okay...dug down and found this devel-job run against this PR: https://hurl.corp.redhat.com/dcab961  If you scroll down, you can see @ 00:06:00.894 (elapsed), it pulled the playbook from [3007ed2bcc6391347998f577ca7f724fa3b0af0f](https://raw.githubusercontent.com/kubernetes-incubator/cri-o/3007ed2bcc6391347998f577ca7f724fa3b0af0f/contrib/test/crio-integration-playbook.yaml).  So that gives me confidence that we should see the production merge take affect w/o error in about 15-minutes (or so).

**Comment by cevich** [comment]
> @cevich sorry to bother everytime though <3

Don't be. It's my job to bash Jenkins with a dead-trout until it submits to your wishes.  Sometimes it takes an ocean full of trout, but that doesn't mean you shouldn't ask me to try 😀

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
@cevich builds are building fine but at the end the job is reported as failed. Could you take a look? There's a grep command failing at the end...

**Comment by cevich** [comment]
@runcom man, I told you not to look at Jenkins sideways!  I'm on it...

**Comment by cevich** [comment]
(note to self: job is - https://hurl.corp.redhat.com/0c7f253 )

**Comment by cevich** [comment]
@runcom Uggg, this is very broken, I'm unsure of how urgent a fix is needed, writing an e-mail to the group...

**Comment by cevich** [comment]
@runcom ...okay, back on the immediate problem.  This is the "grep" you're speaking of, correct:
(from line 105 https://hurl.corp.redhat.com/fca021a ) 

```bash
FAILED=$(cat $WORKSPACE/testout.txt | grep "not ok [0-9]" | wc -l)
```

ya?

**Comment by cevich** [comment]
I see the failure on both [RHEL and Fedora in the results ](https://aos-ci.s3.amazonaws.com/kubernetes-incubator/cri-o/crio-integration-tests-prs/1441/fullresults.txt):

```bash
ok 102 Ping pod from another pod
not ok 103 Ensure correct CNI plugin namespace/name/container-id arguments
# (in test file ./network.bats, line 79)
#   `[ "$status" -eq 0 ]' failed
# 0
# time="2017-09-06 09:01:57.066402467Z" level=debug msg="[graphdriver] trying provided driver "overlay2"" 
```

**Comment by runcom** [comment]
> I see the failure on both RHEL and Fedora in the results :

I've fixed those, next run will be green

**Comment by runcom** [comment]
Ping @mrunalp, let's get this in!

**Comment by mrunalp** [comment]
Finally :tada:

**Comment by dcbw** [comment]
@runcom so, I actually want to revert most of this :)  Once CNI gets the GET action, we want to call that whenever we want status, to ensure we have the most up-to-date status of the container and that we can get errors in the container network setup in a timely fashion.

**Comment by runcom** [comment]
@dcbw fine with me, we needed a way to expose ip though because it's needed in cadvisor and caching the IP could have been a super tiny performance gain (not that much, I know I know..)

**Comment by dcbw** [comment]
@runcom we can certainly cache it, and then update the cache with network status done on a timer instead of constant Kubelet requests.  We know the IP won't change much (if ever) and kubelet is very, very chatty with status requests.  So I think a hybrid could work well.

**Comment by mrunalp** [comment]
@dcbw  yeah, hybrid approach could work once we have GET in CNI. Thanks!

**Pull request merged**
