### PR TITLE
update dependencies for successful build

### PR DESCRIPTION
**Pull request by egernst**
Add dependencies so it matches what is on README.md

This is necessary for successful build on this tutorial

### CODE REVIEW

**Comment by mrunalp** [comment]
@egernst You need to sign the CLA. Thanks!

**Comment by egernst** [comment]
Yes - Working to find the right process on my side for signing now.

I followed rest of directions and saw issues starting pod, so may send another update as well.

Eric

On Jul 20, 2017, at 5:11 PM, Mrunal Patel <notifications@github.com<mailto:notifications@github.com>> wrote:


@egernst<https://github.com/egernst> You need to sign the CLA. Thanks!

**Comment by mrunalp** [comment]
There is still an issue with CLA. You might want to check with @sboeuf or @sameo.

**Comment by egernst** [comment]
@mrunalp - should be updated now.

**Comment by rhatdan** [comment]
@egernst Now you need to sign the pull request.

**Comment by rhatdan** [comment]
@egernst We still need this signed.

**Comment by egernst** [comment]
thanks for the nudge; sorry I had missed this before.  Updated.

**Comment by mrunalp** [comment]
This needs a rebase.

**Comment by rhatdan** [comment]
@egernst Is this still needed or are the docs correct? Lets either complete this or close.  Attempting to cleanup old PRs

**Comment by egernst** [comment]
I’ll  check the tutorial later today and close this PR if no longer valid.

**Comment by rhatdan** [comment]
@egernst Any update?

**Comment by egernst** [comment]
shame on me!  

Just checked on a clean xenial.  Tutorial.md is up to date and accurate now with respect to pre-requisite packages on the host system. Closing this PR.

**Pull request closed without merging**
