### PR TITLE
Conmon cleanup

### PR DESCRIPTION
**Pull request by alexlarsson**
This is a bunch of code cleanups to conmon. They should not affect the behaviour at all, but makes the code easier to read.

The first commit is from https://github.com/kubernetes-incubator/cri-o/pull/620, and i will rebase this when that lands, so ignore that.

### CODE REVIEW

**Comment by alexlarsson** [comment]
Fixed the test failures...

**Comment by runcom** [comment]
LGTM

**Comment by alexlarsson** [comment]
rebased on new master

**Comment by mrunalp** [comment]
Looks good; will wait for jenkins to come back.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
