### PR TITLE
4294967295 does not fix in an int on 32 bit systems

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @mrunalp @runcom PTAL
/test all

**Comment by giuseppe** [comment]
I think we should fix this in `containers/storage`, the type should be `uint32`.  This is what the kernel uses internally on all platforms.

**Comment by TomSweeneyRedHat** [comment]
nit;  Typo in title.  "fix" -> "fit"

**Comment by rhatdan** [comment]
@giuseppe Could you open a PR in storage to fix this.  I have no idea how this PR got so screwed up.

**Pull request closed without merging**
