### PR TITLE
lib: abstract out selinux call

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
/test all

**Comment by vbatts** [comment]
what is the failure? I can't see the logs

**Comment by rhatdan** [comment]
Finally all green.
Merging.

**Pull request merged**
