### PR TITLE
Move StorageRuntimeServer into libkpod

### PR DESCRIPTION
**Pull request by mheon**
Removes some code duplication as a side effect. Required for #713 and create refactoring work.

### CODE REVIEW

**Comment by mheon** [comment]
@14rcole You can rebase #713 on this if you need StorageRuntimeServer for Update()

**Comment by rhatdan** [comment]
LGTM

**Comment by 14rcole** [comment]
@mheon WIll do.  I had it added into my PR but rebasing is fine with me

**Comment by rhatdan** [comment]
@14rcole Rebase.

**Comment by mrunalp** [comment]
I see this as a part of #713 already.

**Comment by mheon** [comment]
@mrunalp If you want to review + merge it there I'm fine with closing this

**Comment by 14rcole** [comment]
@mrunalp I added the code before I was aware of this PR.  I'm happy to rebase my code on top of this and repush

**Comment by mrunalp** [comment]
okay, we can get this in first, then once the tests return.

**Comment by TomSweeneyRedHat** [comment]
LGTM, fwiw.

**Comment by rhatdan** [comment]
@mrunalp tests pass.

**Comment by rhatdan** [comment]
@mheon rebase

**Comment by rhatdan** [comment]
@mrunalp @runcom Passes tests.

**Comment by rhatdan** [comment]
@mheon :^(

**Comment by mheon** [comment]
Merged via #713, closing

**Pull request closed without merging**
