### PR TITLE
Update gitignore to replace ocic with crioctl

### PR DESCRIPTION
**Pull request by mheon**
Matches the rename that just got merged

### CODE REVIEW

**Comment by runcom** [comment]
:+1:

**Comment by jawnsy** [comment]
Just a thought, maybe we can put all the binaries in a subdirectory like `_output` to simplify maintenance of gitignore and `make clean` and so on?

**Comment by mheon** [comment]
Added another commit to fix the unit tests - looks like one was still using ocic/ocid

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
