### PR TITLE
fix link in tutorial.md

### PR DESCRIPTION
**Pull request by carlory**
```
➜  Downloads wget https://github.com/opencontainers/runc/releases/download/v1.0.0-rc4/runc-linux-amd64

--2017-10-25 12:19:52--  https://github.com/opencontainers/runc/releases/download/v1.0.0-rc4/runc-linux-amd64
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-25 12:19:55 ERROR 404: Not Found.
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@carlory You need to sign your PR.

git commit -a --amend -s

**Comment by carlory** [comment]
so sorry,  the VERSION is deleted  because the filename is insensitive case on the mac OS. 

I am dealing with this issue.

**Comment by carlory** [comment]
closed because of the same [pr](https://github.com/kubernetes-incubator/cri-o/pull/1070)

**Pull request closed without merging**
