### PR TITLE
Allow overriding the container name in the config

### LINKED ISSUE #117: ocic ctr create could have --name
run into this early today - would be nice to support `--name` as `ocic pod create` does. **Absolutely a nice to have though**.

### PR DESCRIPTION
**Pull request by mrunalp**
Close #117

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
Addresses #117

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM except for changes to man page.  I am working on the man page as it is, so if you want to merge, I can fix that up.

**Comment by rhatdan** [comment]
Never mind, I am working on ocid man page this is for ocic,

**Pull request merged**
