### PR TITLE
Add more debugs

### PR DESCRIPTION
**Pull request by mrunalp**
These are very useful to figure out what calls kubelet is making. 

Signed-off-by: Mrunal Patel <mpatel@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
damn, make lint failing from @cyphar's PR

**Comment by mikebrow** [comment]
failing.. Which PR? I remember seeing one last week due to some name change or what not.. just needed a one time manual rm.

**Comment by mrunalp** [comment]
@mikebrow It was #170 which we have reverted for now.

**Comment by mrunalp** [comment]
@runcom This is ready too.

**Comment by runcom** [comment]
LGTM!

**Pull request merged**
