### PR TITLE
Move crio default sock to /var/run/crio/crio.sock

### LINKED ISSUE #1028: Move crio.sock to /var/run/crio/crio.sock by default
Using crio.sock at the /var/run level means we cannot give a pod access to only the crio socket, such that a Kubernetes pod can hostPath mount only that directory.  It also is uncommon to mount in that directory - having a specific path would be more consistent with other users of /var/run

### PR DESCRIPTION
**Pull request by mrunalp**
Fixes #1028 
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Assuming happy tests, LGTM.  I did a grep and found only the same ones that you changed.

**Comment by runcom** [comment]
Kube and cadvisor rely on /var/run/crio.sock - we should make a PR in kube to change this as well

**Comment by runcom** [comment]
created https://github.com/google/cadvisor/pull/1773 and  https://github.com/kubernetes/kubernetes/pull/54136

**Comment by derekwaynecarr** [comment]
this would break kube where the constant is hard-coded.

can we make sure we do not break while making this change so we have time to transition?

 https://github.com/kubernetes/kubernetes/pull/52297/files#diff-a1e3deda6194578220521173637fbf46L44

**Comment by runcom** [comment]
I created PRs in kube and cadvisor to take care of this change

**Comment by rhatdan** [comment]
I think we should do this in stages. Create a symbolic link from /var/run/crio.sock to /var/run/crio/crio.sock,
So we continue to work with older kubernetes/minikube/minishift ...

Perhaps in crio-1.9 frame once these other patches are merged we remove the symbolic link.

**Comment by mrunalp** [comment]
We can control this in crio.conf so can still start crio with /var/run/crio.sock after this change.

**Comment by derekwaynecarr** [comment]
@runcom -- i reviewed your pulls, but we need to support a smooth transition.  we will need to pick those changes back to origin/master.  please work with @sjenning to get them in place for where you want the crio.socket to be located for what will roll out to our clusters.

@mrunalp -- good to know this is controllable.

**Comment by mrunalp** [comment]
This is ready now.

**Comment by derekwaynecarr** [comment]
Let's not establish bad precedent.

This branch of development is targeting Kubernetes 1.8.  Kubernetes 1.8 has shipped, and we cannot just make changes that assume Kubernetes 1.8 will change (its too late).  As a result, we should queue this change up for Kubernetes 1.9 after we have merged @runcom change in cAdvisor, and kubernetes/kubernetes master branches.

I expect we will release a version of CRI-O day and date with Kubernetes 1.9 releases.

If @smarterclayton request is needed for origin 1.7 or 1.8, we should handle that separately with a unique branch, but we need to be disciplined on this stuff.

**Comment by mrunalp** [comment]
I am fine reverting this if we feel strongly but this PR _doesn't break_ kube 1.8 as I mentioned earlier https://github.com/kubernetes-incubator/cri-o/pull/1030#issuecomment-337637550. We ship cri-o rpms/configs and can set the listen socket to continue to point to /var/run/crio.sock.

**Pull request merged**
