### PR TITLE
Kpod format

### PR DESCRIPTION
**Pull request by 14rcole**
Add functions to text/template, as well as the ability to create a table with it.  Also create a default template for `kpod images` so that images can outputted via text/template instead of `fmt.Printf()`

### CODE REVIEW

**Comment by rhatdan** [comment]
Isn't @baude working on this also?

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by 14rcole** [comment]
I believe he's working on modularizing the output so support can be added for json, etc. @baude if you're already working on table and moving printf output to a template, I can close this

**Comment by rhatdan** [comment]
@14rcole I think your right, I wrote comment based on the title of the pull request after reviewing, I realized this was different.

**Comment by baude** [comment]
if we can merge my PR for format and this one, i will circle back and reimplement his stdout stuff in the other commands

**Comment by rhatdan** [comment]
@cevich @mrunalp looks like the RHEL tests are not running?

**Comment by rhatdan** [comment]
Now they finished.  Passes tests.
@mrunalp @runcom PTAL
And lets get this merged.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
