### PR TITLE
Rename libkpod files to follow Go conventions

### LINKED ISSUE #710: GO idiomatic (not)
Stuff like https://github.com/kubernetes-incubator/cri-o/blob/master/libkpod/containerData.go aren't go idiomatic, that file should be `container_data.go` . This also should be underscored https://github.com/kubernetes-incubator/cri-o/blob/master/libkpod/containerserver.go

@14rcole @mheon PTAL

### PR DESCRIPTION
**Pull request by mheon**
Fixes #710

### CODE REVIEW

**Comment by runcom** [comment]
:+1:

**Comment by 14rcole** [comment]
LGTM

**Comment by mrunalp** [comment]
:+1:

**Comment by mrunalp** [comment]
One of the lint tools should have caught it. Well, we could contribute a checker to one of the lint tools :)

**Comment by rhatdan** [comment]
@mrunalp @runcom Passes lets merge it.

**Pull request merged**
