### PR TITLE
[release-1.0] test: Fix partial log line parsing

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

Carry https://github.com/kubernetes-incubator/cri-o/pull/1120 for `release-1.0` branch

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
@mrunalp we would need this for `master` (1.8) and probably 1.9 in the future as upstream hasn't yet decided on how to handle this.

**Comment by runcom** [comment]
Green :)

**Comment by mrunalp** [comment]
Yeah we will need to carry this for 1.8 and hopefully get it fixed in master. Also we need to take my commit into origin to fix the bug. LGTM.

**Comment by runcom** [comment]
> Yeah we will need to carry this for 1.8 and hopefully get it fixed in master. Also we need to take my commit into origin to fix the bug. LGTM.

master doesn't need a PR as I've just push forced to the kube branch we use for testing and should just work I guess

**Pull request merged**
