### PR TITLE
server: inspect: add log path and mount point for cadvisor

### PR DESCRIPTION
**Pull request by runcom**
@mrunalp PTAL this is needed by cadvisor

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
Looks good; will wait for tests.

**Comment by runcom** [comment]
:tada:

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
