### PR TITLE
Only print error message on kpod error not stacktrace

### PR DESCRIPTION
**Pull request by rhatdan**
If the user specifies --debug flag then print stack trace.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @umohnani8 @mheon PTAL

**Comment by mheon** [comment]
LGTM pending tests

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
Fixes https://github.com/kubernetes-incubator/cri-o/issues/882

**Comment by TomSweeneyRedHat** [comment]
LGTM, but you took away my breakfast fun!  I was trying to test this, but can't get CRI-O to compile this morning.  If your tests look good on your end, ship it!

**Comment by rhatdan** [comment]
[retest]

**Comment by rhatdan** [comment]
Merging.

**Pull request merged**
