### PR TITLE
test: Add libkpod config tests

### PR DESCRIPTION
**Pull request by ashcrow**
- ``config_test.go`` for testing ``libkpod/config.go``
- ``testdata/config.toml`` as a fixture for ``config_test.go``

### CODE REVIEW

**Comment by rhatdan** [comment]
Fix spelling error.  We are hoping to make likpod go away as we move towards libpod, but this test should be able to be easily ported.

**Comment by mheon** [comment]
@rhatdan This isn't really going to end up a libpod test, libpod won't directly deal with loading config files to/from disk. This will probably move back into the CRI-O code at some point. Still a good test, though.

@ashcrow We don't actually have a makefile target for running unit tests right now, as all our tests are integration tests. Would you mind adding one? We can see about getting them running in Travis after that.

**Comment by ashcrow** [comment]
@rhatdan will fix.

@mheon will do!

**Comment by ashcrow** [comment]
@mheon it looks like there is a ``make`` target for unit testing: ``make testunit``:


```
$ make testunit
can't load package: package github.com/kubernetes-incubator/cri-o/vendor/github.com/ostreedev/ostree-go/pkg/otadmin: 
vendor/github.com/ostreedev/ostree-go/pkg/otadmin/admin.go:1:1: expected 'package', found 'EOF'
can't load package: package github.com/kubernetes-incubator/cri-o/vendor/github.com/ostreedev/ostree-go/pkg/otremote: 
vendor/github.com/ostreedev/ostree-go/pkg/otremote/remoteadd.go:1:1: expected 'package', found 'EOF'
go test -tags "selinux seccomp  " -cover github.com/kubernetes-incubator/cri-o/cmd/crio github.com/kubernetes-incubator/cri-o/cmd/crioctl github.com/kubernetes-incubator/cri-o/cmd/kpod github.com/kubernetes-incubator/cri-o/cmd/kpod/docker github.com/kubernetes-incubator/cri-o/cmd/kpod/formats github.com/kubernetes-incubator/cri-o/libkpod github.com/kubernetes-incubator/cri-o/libkpod/sandbox github.com/kubernetes-incubator/cri-o/libpod github.com/kubernetes-incubator/cri-o/libpod/common github.com/kubernetes-incubator/cri-o/libpod/ctr github.com/kubernetes-incubator/cri-o/libpod/driver github.com/kubernetes-incubator/cri-o/libpod/images github.com/kubernetes-incubator/cri-o/libpod/layers github.com/kubernetes-incubator/cri-o/libpod/pod github.com/kubernetes-incubator/cri-o/oci github.com/kubernetes-incubator/cri-o/pkg/annotations github.com/kubernetes-incubator/cri-o/pkg/registrar github.com/kubernetes-incubator/cri-o/pkg/storage github.com/kubernetes-incubator/cri-o/server github.com/kubernetes-incubator/cri-o/server/apparmor github.com/kubernetes-incubator/cri-o/server/seccomp github.com/kubernetes-incubator/cri-o/test/bin2img github.com/kubernetes-incubator/cri-o/test/checkseccomp github.com/kubernetes-incubator/cri-o/test/copyimg github.com/kubernetes-incubator/cri-o/utils
?       github.com/kubernetes-incubator/cri-o/cmd/crio  [no test files]
?       github.com/kubernetes-incubator/cri-o/cmd/crioctl       [no test files]
ok      github.com/kubernetes-incubator/cri-o/cmd/kpod  0.069s  coverage: 0.0% of statements
?       github.com/kubernetes-incubator/cri-o/cmd/kpod/docker   [no test files]
?       github.com/kubernetes-incubator/cri-o/cmd/kpod/formats  [no test files]
ok      github.com/kubernetes-incubator/cri-o/libkpod   0.122s  coverage: 3.1% of statements
?       github.com/kubernetes-incubator/cri-o/libkpod/sandbox   [no test files]
?       github.com/kubernetes-incubator/cri-o/libpod    [no test files]
?       github.com/kubernetes-incubator/cri-o/libpod/common     [no test files]
?       github.com/kubernetes-incubator/cri-o/libpod/ctr        [no test files]
?       github.com/kubernetes-incubator/cri-o/libpod/driver     [no test files]
?       github.com/kubernetes-incubator/cri-o/libpod/images     [no test files]
?       github.com/kubernetes-incubator/cri-o/libpod/layers     [no test files]
?       github.com/kubernetes-incubator/cri-o/libpod/pod        [no test files]
?       github.com/kubernetes-incubator/cri-o/oci       [no test files]
?       github.com/kubernetes-incubator/cri-o/pkg/annotations   [no test files]
ok      github.com/kubernetes-incubator/cri-o/pkg/registrar     0.024s  coverage: 84.8% of statements
?       github.com/kubernetes-incubator/cri-o/pkg/storage       [no test files]
ok      github.com/kubernetes-incubator/cri-o/server    0.099s  coverage: 0.8% of statements
?       github.com/kubernetes-incubator/cri-o/server/apparmor   [no test files]
?       github.com/kubernetes-incubator/cri-o/server/seccomp    [no test files]
?       github.com/kubernetes-incubator/cri-o/test/bin2img      [no test files]
?       github.com/kubernetes-incubator/cri-o/test/checkseccomp [no test files]
?       github.com/kubernetes-incubator/cri-o/test/copyimg      [no test files]
?       github.com/kubernetes-incubator/cri-o/utils     [no test files]

```

**Comment by mheon** [comment]
@ashcrow Huh. Did not know that. Cool!

In that case, we'll probably want to add some extra targets to run both unit and integration tests, optionally in a container, but I can make that happen in another PR.

**Comment by mheon** [comment]
LGTM pending tests

**Comment by mheon** [comment]
Tests are green, and this is just a makefile change - shouldn't need a pass of the E2E tests. @rhatdan let's get this merged.

**Comment by rhatdan** [comment]
@mheon Did you comment on the wrong PR?  This is not a Makefile change?

**Comment by mheon** [comment]
@rhatdan Sorry, test change - just adding new unit tests. Oops. My point stands, though - none of this will break the E2E tests.

**Comment by rhatdan** [comment]
Do we run unit tests on E2E?  I guess not, but we really should run these tests in RHEL/Fedora systems.
LGTM

**Pull request merged**
