### PR TITLE
utils: Fix close conn after starting scope

### PR DESCRIPTION
**Pull request by mrunalp**
This fixes the goroutine leak in cri-o.

Signed-off-by: Mrunal Patel <mpatel@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM pending tests

**Comment by runcom** [comment]
LGTM lol

**Comment by mrunalp** [comment]
[retest]

**Comment by runcom** [comment]
Seems like this is breaking systemd cgroup manager

**Comment by TomSweeneyRedHat** [comment]
LGTM.  @runcom where are you seeing the break?  The tests seem to be passing.

**Comment by runcom** [comment]
CI is failing integration tests, probably related to this change in systemd connection I guess. See comment above mine...

**Comment by mrunalp** [comment]
Jenkins has been failing with this error since yesterday before this PR. We have to fix jenkins or code that broke it.

**Comment by mrunalp** [comment]
retest

**Comment by mrunalp** [comment]
[retest]

**Comment by mrunalp** [comment]
@runcom This is the failing line in the tests:
```
 "$CRICTL_BINARY" -r "$CRIO_SOCKET" -i "$CRIO_SOCKET" "$@"
```

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
this needs a rebase to fix tests I guess

**Comment by mrunalp** [comment]
I just rebased this.

**Comment by mrunalp** [comment]
Once travis passes, we can restart jenkins.

**Comment by mrunalp** [comment]
[retest]

**Pull request merged**
