### PR TITLE
*WIP* Move to file-based state

### PR DESCRIPTION
**Pull request by mheon**
These patches move CRI-O's state out of server into a separate package accessible by an interface, and adds an implementation that stores state on disk. It removes the existing sync code in the server, and replaces it with in-state sync. It's mainly to enable `kpod` to run alongside CRI-O without races.

There are technically 2 state implementations available, an in-memory version and file-based version. However, with the removal of the existing sync code, the in-memory state cannot preserve the state across restart. It might be interesting to re-add the code to load state information from container runtime configs and allow the in-memory state to be used as an alternative for performance-sensitive implementations where we don't expect other applications to be interacting with containers.

There's a description of the on-disk state structure in `file_state.go`. I moved away from using the OCI runtime spec JSON to simplify things (the on-disk format is kept very similar to in-memory format minus a few things that don't serialize well), but it might have ended up being just as the previous code in server to load containers from their runtime spec. Still investigating if there's a better way of doing this.

Moving `sandbox` out into its own package was probably not strictly necessary, but it helps ensure no out-of-band modifications to sandboxes happen that aren't caught and synced to disk.

Work still in progress:
- Make all operations atomic to the greatest extent possible
- Investigate better on-disk storage format
- Restore prior semantics of container and sandbox names
- Fix bugs causing issues with Kube e2e tests
- Improve performance on state sync

### CODE REVIEW

**Comment by cyphar** [comment]
> I moved away from using the OCI runtime spec JSON to simplify things (the on-disk format is kept very similar to in-memory format minus a few things that don't serialize well)

I haven't reviewed this yet (and I like where it's heading though I'm concerned about premature optimisation with the whole `InMemoryState`) but this line stood out to me. I would prefer if we didn't have to maintain a structure that is a subset of the runtime-spec, because it means that when the runtime-spec changes we have to update our own on-disk state schema as well as the schema that we generate otherwise. Maybe I'm in the minority on this one, but I'd prefer that if we can use a standardised schema to store information we should.

**Comment by mheon** [comment]
@cyphar No objections to using the official runtime state JSON here. I'm not particularly happy with the way on-disk storage works right now. There are a few issues that need to be worked out (it might be desirable to move generation for the runtime config into the state, to not break the abstraction? Adds even more churn to an already big set of changes, though). I'll look into it on Monday.

**Comment by rhatdan** [comment]
Maybe we could do this in a series of changes. First get patch 1 merged, IE move the state behind an interface.

**Comment by rhatdan** [comment]
@mheon Now that we have changed our strategy should you close this pull request?

**Comment by mheon** [comment]
@rhatdan Yeah, closing this

**Pull request closed without merging**
