### PR TITLE
sandbox_run: Drop ambient capabilities for infra pod

### PR DESCRIPTION
**Pull request by mrunalp**
@umohnani8 @rhatdan PTAL. I will add this commit to the 1.10 PR.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
/test all

**Comment by mrunalp** [comment]
@umohnani8 Sandbox object doesn't have capabilities.

**Comment by umohnani8** [comment]
@mrunalp oh okay, didn't know thanks!
LGTM

**Pull request merged**
