### PR TITLE
Bump up version to 0.1

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom @sameo @rhatdan @cyphar PTAL

We will tag this as 0.1 on the repo. 

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
:+1:

**Comment by rhatdan** [comment]
:+1:

**Comment by sameo** [comment]
LGTM

**Comment by feiskyer** [comment]
LGTM

**Comment by mrunalp** [comment]
Thanks! Merging. I'll tag and release tomorrow.

**Comment by mrunalp** [comment]
I pushed the v0.1 tag. I'll compile release notes and cut a release tomorrow.

**Pull request merged**
