### PR TITLE
release 1.10.3

### PR DESCRIPTION
**Pull request by runcom**
I'll tag the new version once all other PR for 1.10.x are merged and I rebase this one.

@mrunalp @rhatdan PTAL

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
do not merge this until [release-1.10] PRs are all in

**Comment by rhatdan** [comment]
Ok

**Comment by runcom** [comment]
alright, all 1.10 PRs went in, this should be ready to ship

**Comment by rhatdan** [comment]
@runcom Do you need to rebase this PR?

**Comment by mrunalp** [comment]
We shouldn't have to rebase unless there is a conflict.

**Pull request merged**
