### PR TITLE
vndr: Update logrus package to v1.0.0

### LINKED ISSUE #712: Sirupsen and sirupsen
runc and containerd are all moving up to `sirupsen` v1.0.0.

cri-o and packages it's using are still at `Sirupsen` v0.11.5.

Are we going to update to `sirupsen`?

### PR DESCRIPTION
**Pull request by mrunalp**
Fixes #712
Signed-off-by: Mrunal Patel <mpatel@redhat.com>

### CODE REVIEW

**Comment by Random-Liu** [comment]
Some dependencies are still using old version, won't that cause any problem?
https://github.com/kubernetes-incubator/cri-o/blob/master/vendor/github.com/docker/docker/pkg/signal/trap.go#L14

**Comment by mrunalp** [comment]
@Random-Liu good point. Let me check the vendors as well.

**Comment by mrunalp** [comment]
I am fixing the deps in our other packages and then we can come back to this.

**Comment by mrunalp** [comment]
Created https://github.com/containers/storage/pull/81
and https://github.com/containers/image/pull/319

**Comment by rhatdan** [comment]
@mrunalp Lets close this and work on it in https://github.com/kubernetes-incubator/cri-o/issues/735

**Pull request closed without merging**
