### PR TITLE
README.md: add go-md2man to build dep in Ubuntu

### PR DESCRIPTION
**Pull request by runcom**
Needed by `make docs`

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
/test all
LGTM

**Comment by runcom** [comment]
> /test all
> LGTM

can you just merge it Dan?

**Comment by rhatdan** [comment]
Oops I thought this was a change to a test package.  Not a README.
No need to test.

**Pull request merged**
