### PR TITLE
move ocicni from vendors to pkg

### PR DESCRIPTION
**Pull request by rajatchopra**
Signed-off-by: Rajat Chopra <rchopra@redhat.com>

@mrunalp PTAL

### CODE REVIEW

**Comment by rajatchopra** [comment]
I signed it

**Comment by runcom** [comment]
@sameo PTAL

**Comment by sameo** [comment]
@rajatchopra Nice, thanks.
LGTM.

**Comment by sameo** [comment]
@rajatchopra There are a couple of lint errors. With `make lint` you should be able to reproduce locally.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
