### PR TITLE
conmon: return the correct exit status

### PR DESCRIPTION
**Pull request by giuseppe**
WEXITSTATUS(x) can be used only if WIFEXITED(x).  We were using it
also in the case the process exited because it was signaled.

Since we check for the exit_status both for the container and the
runtime, move the common code to a new function get_exit_status that
is used in both cases.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

**- What I did**
Fix the exit status reported by conmon

**- How I did it**
I added a check if the process was exited because of a signal

**- How to verify it**
conmon returns exit status 137 on "kill -9 $CONTAINER_PID"

**- Description for the changelog**
conmon returns the corrrect exit status when the process is signaled

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
/test all

**Comment by rhatdan** [comment]
@wking @mrunalp @runcom @umohnani8 PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
Merging

**Pull request merged**
