### PR TITLE
systemd: expand limits for tests

### PR DESCRIPTION
**Pull request by lsm5**
Borrowed from:
https://github.com/projectatomic/atomic-system-containers/pull/136

From: Antonio Murdaca <runcom@redhat.com>
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@mrunalp @runcom PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
@mrunalp is the travis failure a known issue? I haven't changed anything for the `install.tools` target.

**Comment by mrunalp** [comment]
@lsm5 network flake. I have restarted the travis build.

**Comment by lsm5** [comment]
@mrunalp seems all checks good.

**Comment by runcom** [comment]
LGTM

**Pull request merged**
