### PR TITLE
Correct package name for pkg-config

### PR DESCRIPTION
**Pull request by vbmade2000**
Signed-off-by: Malhar Vora  <mlvora.2010@gmail.com>

### CODE REVIEW

**Comment by vbmade2000** [comment]
I signed it!

**Comment by runcom** [comment]
@vbmade2000 can you just `git commit --amend --no-ed && git push -f` to have github hook restart for the CLA?

**Comment by runcom** [comment]
LGTM (in the meantime)

**Comment by vbmade2000** [comment]
@runcom : Executed command you mentioned.

**Comment by vbmade2000** [comment]
@runcom I forget to wrap email in <>. Can it be the reason ? If required I can create new pull request.

**Comment by cyphar** [comment]
@vbmade2000 The `Author` field of your commit is wrong:

```
commit 416648ffc296dbb73f030bfa0fd5ac0e2cbe7948
Author: Malhar L Vora <531300@PUN-U531650L001.local>
Commit: Malhar Vora <mlvora.2010@gmail.com>
```

You can fix it by doing the following:

```
git commit --amend --author="Malhar Vora <mlvora.2010@gmail.com>"
```

**Comment by vbmade2000** [comment]
@cyphar : I'll do it. Thanks.

**Pull request merged**
