### PR TITLE
Makefile: force symlink to cri-o.service

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@rhatdan PTAL and merge if it looks ok

**Comment by rhatdan** [comment]
Since I just added the same patch, I will say 
LGTM

**Comment by rhatdan** [comment]
https://github.com/kubernetes-incubator/cri-o/pull/800 is same.

**Comment by TomSweeneyRedHat** [comment]
LGTM, but why is duelling banjos playing in my head now?

**Comment by runcom** [comment]
[retest]

**Pull request merged**
