### PR TITLE
[release-1.0] Add /proc/scsi to masked paths

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
e2e failures are fixed here https://github.com/kubernetes-incubator/cri-o/pull/1176

**Comment by runcom** [comment]
e2e failures are fixed here #1176

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
alright, this is now running with the correct AMIs :)

**Comment by runcom** [comment]
green, if you guys merge, I'll tag v1.0.5 @rhatdan @mrunalp

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
