### PR TITLE
server: fix set caps on container create

### PR DESCRIPTION
**Pull request by runcom**
Found while integrating CRI-O with OpenShift Origin:
```
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath         Type             Reason          Message
  ---------     --------        -----   ----                            -------------         -------- ------          -------
  3s            3s              1       default-scheduler                                     Normal           Scheduled       Successfully assigned nginx10-1-deploy to 192.168.122.186
  3s            2s              2       kubelet, 192.168.122.186        spec.containers{deployment}    Normal          Pulled          Container image "openshift/origin-deployer:d98ef74" already present on machine
  3s            2s              2       kubelet, 192.168.122.186        spec.containers{deployment}    Warning         Failed          Failed to create container with error: rpc error: code = 2 desc = capability KILL must start with CAP_
  3s            2s              2       kubelet, 192.168.122.186                              Warning          FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "deployment" with rpc error: code = 2 desc = capability KILL must start with CAP_: "Create Container Failed"
```

@mrunalp @sameo PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
**note to myself**: this needs to be ported to kube-1.6.1 branch

**Comment by runcom** [comment]
so, failure in tests seem legit, I'm debugging it.

**Comment by mrunalp** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
