### PR TITLE
Remove disused contrib/rpm

### PR DESCRIPTION
**Pull request by cevich**
**- What I did**

Remove two files I don't believe are needed anymore.  Freeing up the directory for use in the future, minus possibly clashing filenames.

**- How I did it**

``rm -rf ./contrib/rpm/*``

**- How to verify it**

CI testing passes

### CODE REVIEW

**Comment by cevich** [comment]
**N/B:**  I don't really know for sure these things aren't used/needed, I'm relying on somebody who needs them speaking up 😀

**Comment by cevich** [comment]
@mrunalp or @runcom I believe @rhatdan wrote these long ago.  Just doing some janitorial duty here, nothing critical/urgent.

**Comment by mrunalp** [comment]
@cevich Sounds good to me if @rhatdan is okay with this.

**Comment by rhatdan** [comment]
The idea of these two files was to make it easy for someone to create an installable rpm from their contents.  I was hoping that You, Ed and Lokesh we coming up with a better way to handle this. If so then removing these files is fine with me.

**Comment by cevich** [comment]
> I was hoping that You, Ed and Lokesh we coming up with a better way

Ahh, yep, in fact I was working on that when I opened this :D  It's the [linked PR above](https://github.com/lsm5/cri-o/pull/2) that @lsm5 merged into his #921.  Though we didn't actually test it yet 😀   We're intending intended it to work like so:

``make test-rpm``

-or-

Drop a something.spec file into the the cloned repo, then
``make test-rpm``

I'm not married to the 'test-rpm' target name...Probably should change that to 'package', since #957 expects the Makefile to just do the right thing (for whatever platform).

**Pull request merged**
