### PR TITLE
Add SECURITY_CONTACTS

### LINKED ISSUE #1577: Create a SECURITY_CONTACTS file.
As per the email sent to kubernetes-dev[1], please create a SECURITY_CONTACTS
file.

The template for the file can be found in the kubernetes-template repository[2].
A description for the file is in the steering-committee docs[3], you might need
to search that page for "Security Contacts".

Please feel free to ping me on the PR when you make it, otherwise I will see when
you close this issue. :)

Thanks so much, let me know if you have any questions.

(This issue was generated from a tool, apologies for any weirdness.)

[1] https://groups.google.com/forum/#!topic/kubernetes-dev/codeiIoQ6QE
[2] https://github.com/kubernetes/kubernetes-template-project/blob/master/SECURITY_CONTACTS
[3] https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance-template-short.md

### PR DESCRIPTION
**Pull request by mrunalp**
@jessfraz PTAL :)

cc: @rhatdan @runcom 

Fixes #1577
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
There seems to be some issue with vet and go tip.

**Comment by rhatdan** [comment]
LGTM

**Comment by jessfraz** [comment]
dope thanks for doing this so quickly

**Comment by runcom** [comment]
LGTM

**Comment by runcom** [comment]
mmmm, travis's failing looking

**Comment by giuseppe** [comment]
should we allow failures for go:tip?  I've added temporarily a patch to get tests passing for https://github.com/kubernetes-incubator/cri-o/pull/1578 as I am hitting the same build failure.

**Comment by TomSweeneyRedHat** [comment]
FWIW, Buildah builds using tip, but does allow for failures there.   I'd +1 on allowing failures on tip as long as we keep up with the recent versions of go too.

**Comment by mrunalp** [comment]
@giuseppe Yeah, I think we should allow failures for go:tip.

**Comment by runcom** [comment]
:+1: for allowing failures in go tip.

Since this isn't really dealing with code and given it's something security-related, I'll merge this and we can make a PR to allow features in go tip, @giuseppe do you already have a patch right?

**Comment by giuseppe** [comment]
yes, it is part of the PR I've linked above.  Should I move it to a new PR?

**Comment by runcom** [comment]
> yes, it is part of the PR I've linked above. Should I move it to a new PR?

yeah, that would be best thanks!

**Pull request merged**
