### PR TITLE
Remove unnecessary check for mount label for /dev/shm

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mpatel@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
:+1:

**Comment by rhatdan** [comment]
No this is wrong,

You still need
```
	shmOptions = label.FormatMountLabel(shmOptions, mountLabel) 
```
before the mount.

label.FormatMountLabel will return shmOptions, if mountLabel == ""

**Comment by mrunalp** [comment]
@rhatdan I may be missing something but how is that different from this PR besides adding one more line for assignment?

**Comment by rhatdan** [comment]
shmOptions = label.FormatMountLabel(shmOptions, mountLabel) 
Modifies the shmOptions and needs to be passed into the mount command.

label.FormatMountLabel("ro", "")
Generates a shmOption of "ro"

label.FormatMountLabel("ro", "system_u:object_r:container_file_t:s0:c1,c2")
Generates a shmOption of "ro,context='system_u:object_r:container_file_t:s0:c1,c2'" Which needs to be passed to the mount option.  Calling this function after the mount does nothing.

**Comment by runcom** [comment]
@rhatdan I believe the diff is fooling, the call to `label.FormatMountLabel` is not _after_ the `mount` call, it's actually _in_ the call to mount but on a new line.

**Comment by rhatdan** [comment]
Ah sh*t, my lying eyes were deceiving me.

LGTM

**Pull request merged**
