### PR TITLE
replace crioctl with crictl in e2e

### PR DESCRIPTION
**Pull request by weiwei04**
Signed-off-by: Wei Wei <weiwei.inf@gmail.com>

**- What I did**

replace crioctl with crictl in e2e

**- How I did it**

vim

**- How to verify it**

make verify

make integration

**- Description for the changelog**

replace crioctl with crictl in e2e

### CODE REVIEW

**Comment by runcom** [comment]
This is awesome @weiwei04 Thanks!!!!

Could you go a step further and add a commit that completely removes crioctl code under `cmd/crioctl` as well? :angel: :)

**Comment by TomSweeneyRedHat** [comment]
LGTM @weiwei04 Thanks for the PR, as @runcom noted, it's awesome!  
Green buttons on this one.  I'd vote on getting this merged then doing a separate PR for cmd if you're up for it @weiwei04

**Comment by rhatdan** [comment]
Yes lets remove the crioctl stuff in a separate PR.
Want @mrunalp to review this before we merge.
LGTM

**Comment by rhatdan** [comment]
@weiwei04 Also can you remove WIP

**Comment by weiwei04** [comment]
Yes, I will open another pr to remove crioctl code once this pr is done.

Please hold this pr, I think I can finish remaining *.bats files by tomorrow :)

**Comment by TomSweeneyRedHat** [comment]
@weiwei04 I'd suggest not adding anything further to this PR.  If you could just remove the WIP from the title via the GitHub gui, I think this one should be merged once @mrunalp gets a look see.  FWIW, I'm a big proponent of small and frequent PRs.

**Comment by weiwei04** [comment]
Sure, removed WIP, and I will open separate pr to address other test file changes make this crioctl -> crictl process more reviewable :)

**Comment by runcom** [comment]
LGTM

@mrunalp PTAL

**Comment by mrunalp** [comment]
This actually does the replacement in pod.bats we still need to remove it from the other files but that can be done in other PRs. 
```
[mrunalp@localhost test]$ grep crioctl -rl .
./restore.bats
./default_mounts.bats
./testdata/sandbox_config_hostport.json
./testdata/sandbox1_config.json
./testdata/sandbox3_config.json
./testdata/README.md
./testdata/sandbox_config_selinux.json
./testdata/sandbox2_config.json
./testdata/sandbox_config_hostnet.json
./testdata/sandbox_config.json
./testdata/sandbox_config_seccomp.json
./testdata/sandbox_config_sysctl.json
./testdata/template_sandbox_config.json
./README.md
./helpers.bash
./inspect.bats
./runtimeversion.bats
./image.bats
./network.bats
./hooks.bats
./cgroups.bats
./selinux.bats
./ctr.bats
./ctr_seccomp.bats
./image_volume.bats
./apparmor.bats
```

**Comment by mrunalp** [comment]
We can wait for https://github.com/kubernetes-incubator/cri-o/pull/1156#issuecomment-344640328 so we can change all the bats file in one shot here.

**Comment by rhatdan** [comment]
@mrunalp I am not sure what you are saying.  You want to have this PR Held up?  And have @weiwei04 update the patch to completely remove crioctl?  Or should we merge and have @weiwei04 submit a different PR?

**Comment by mrunalp** [comment]
@rhatdan I meant that we can wait for @weiwei04 to update the PR to remove crioctl from all bats files. The removal of cmd/crioctl can be in a follow-on PR. Thanks!

**Comment by mrunalp** [comment]
Sorry for all the confusion. We can have follow-on PRs to fix the other test files. Merging this now. Thanks @weiwei04 !

**Pull request merged**
