### PR TITLE
Release v1.9.11

### PR DESCRIPTION
**Pull request by mrunalp**
@rhatdan @runcom @umohnani8 PTAL

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, assuming happy tests.

**Comment by TomSweeneyRedHat** [comment]
speak of the devil, happy green test buttons.

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
Merging.

**Comment by rhatdan** [comment]
@mrunalp You need to create a Tag and a Release.

**Comment by runcom** [comment]
LGTM

**Pull request merged**
