### PR TITLE
lib: Use libpod's hooks package

### PR DESCRIPTION
**Pull request by wking**
This collects the hook logic which was previously spread between lib and server.  It also adds unit tests with almost-complete coverage.  Now the main packages are fairly isolated from the hook internals, which makes it fairly straightforward to bump the hook config file to 1.0.0.  I've dubbed the old format 0.1.0, although it doesn't specify an explicit version.  Motivation for some of my changes with 1.0.0:

* Add an explicit version field.  This will make any future JSON structure migrations more straightforward by avoiding the need for version-guessing heuristics.

* Collect the matching properties in a new When sub-structure.  This makes the root Hook structure easier to understand, because you don't have to read over all the matching properties when wrapping your head around Hook.

* Replace the old 'hook' and 'arguments' with a direct embedding of the runtime-spec's hook structure.  This provides access to additional upstream properties (args[0], env, and timeout) and avoids the complication of a CRI-O-specific analog structure.

* Add a 'when.always' property.  You can usually accomplish this effect in another way (e.g. when.commands = [".*"]), but having a boolean explicitly for this use-case makes for easier reading and writing.

* Replace the previous annotations array with an annotations map.  The 0.1.0 approach matched only the values regardless of key, and that seems unreliable.

* Replace 'cmds' with 'when.commands', because while there are a few ways to abbreviate "commands", there's only one way to write it out in full ;).  This gives folks one less thing to remember when writing hook JSON.

I've also added doc-compat support for the various pluralizations of the 0.1.0 properties.  Previously, the docs and code were not in agreement.  More on this particular facet in #1235.

And I've updated the docs to point out that the annotations being matched are the Kubernetes annotations, which are a subset of the annotations in the runtime configuration.  For exmaple, io.kubernetes.cri-o.Volumes is part of the runtime config annotations, but not part of the Kubernetes annotations being matched for hooks.

### CODE REVIEW

**Comment by rhatdan** [comment]
I think it would be better to do this consolodation by moving/merging this code with libpod/pkg/hooks.

**Comment by wking** [comment]
> I think it would be better to do this consolodation by moving/merging this code with libpod/pkg/hooks.

I thought about that, but because libpod has a root `vendor`, I don't think we can use it as a libray here see (opencontainers/image-spec#528 and opencontainers/image-spec#532).  This hook lib could be part of a shared library repo though.  Or maybe I'm missing something and we could vendor libpod packages here?

**Comment by wking** [comment]
#1537 demonstrated that vendoring libpod with `vndr` does work, so my [earlier concerns][1] were unfounded.  I've rebased this commit onto libpod v0.5.2 with 35b300ba -> 4b3f0786 to pick up the new hooks package there.

[1]: https://github.com/kubernetes-incubator/cri-o/pull/1517#issuecomment-379965399

**Comment by wking** [comment]
With 4b3f0786a -> 46bb7c965, I've rebased this onto master and re-run the vendor commit to pull in libpod v0.5.3 and the multi-directory monitoring improvements from projectatomic/libpod#757.

**Comment by wking** [comment]
I'm not sure what the critest failure is.  The logs [have][1]:

> Unable to start service crio: Job for crio.service failed because the control process exited with error code. See "systemctl status crio.service" and "journalctl -xe" for details.

but I can't find the systemd logs.  Weren't we going to capture those (openshift/aos-cd-jobs#1192)?  I suspect the issue is related to missing hook directories (see [here][2] and later), so I'll take a few stabs in that direction when I get time.  Until I get the tests sorted, I've added a WIP prefix to the PR subject.


[1]: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_crio_critest_rhel/377/consoleFull#-92802960658b6e51eb7608a5981914356
[2]: https://github.com/projectatomic/libpod/pull/686#issuecomment-385095212

**Comment by wking** [comment]
The [Travis failure][1] looks like #1473.

[1]: https://travis-ci.org/kubernetes-incubator/cri-o/jobs/381206006#L3239

**Comment by wking** [comment]
@rhatdan, can you kick the tests again at sone point?

**Comment by wking** [comment]
I've removed the WIP prefix.  As far as I can tell, this is working.  And the failing CI workers [are missing logs][1] needed to dig deeper.

[1]: https://github.com/kubernetes-incubator/cri-o/pull/1517#issuecomment-390446238

**Comment by wking** [comment]
Go tip is [not pleased][1], starting out with:

```
cmd/crio/config.go:7:2: could not import github.com/kubernetes-incubator/cri-o/server (cannot import, possibly version skew (embedded type is not an interface) - reinstall package)
cmd/crio/main.go:483:31: invalid operation: config (variable of type *invalid type) has no field or method Runtime
cmd/crio/main.go:488:45: invalid operation: config (variable of type *invalid type) has no field or method Listen
```

and much more in that vein.  I'm guessing this is a flake, although it may be an issue with us if we're asking Travis to cache anything?  Some similar "no field or method" errors are discussed in #481, where the issue was "your Go is too old".  Here it seems like it's either "your Go is too new" or "your Go is broken" ;).  Do we really want to run CI on Go tip?

[1]: https://travis-ci.org/kubernetes-incubator/cri-o/jobs/383853748#L646

**Comment by wking** [comment]
Rebased onto master with 3e0642c5b -> 3915e5618 (no conflicts) now that #1581 has landed and made [the earlier Go tip issues][1] non-fatal.

[1]: https://github.com/kubernetes-incubator/cri-o/pull/1517#issuecomment-392166491

**Comment by wking** [comment]
> I'll file a patch upstream to skip that iteration if `directories` is `nil`.

Ah, actually it seems like the issue is `m` being `nil`.  I've rebased onto master and made the monitoring conditional on actually having a hook `Manager` with 3915e5618 -> 9397e913e.

**Comment by wking** [comment]
[The Travis failure][1] is the #1473 flake.

[1]: https://travis-ci.org/kubernetes-incubator/cri-o/jobs/388047436#L3239

**Comment by wking** [comment]
> The following tests failed, say `/retest` to rerun them all:
>
> | Test name | Commit | Details | Rerun command |
> | -- | -- | -- | -- |
> | ci/openshift-jenkins/e2e_rhel | 3915e56 | link | /test e2e_rhel |

Not sure why that's still testing [the previous tip][1].

`integration_fedora` is failing [with][2]:

```
TASK [run integration tests] ***************************************************
task path: /go/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/test.yml:26
fatal: [localhost]: FAILED! => {
    "ansible_job_id": "782351339187.7770", 
    "changed": true, 
    "cmd": "CGROUP_MANAGER=cgroupfs STORAGE_OPTIONS='--storage-driver=overlay' make localintegration >& /tmp/artifacts/testout.txt", 
    "delta": "0:11:56.223115", 
    "end": "2018-06-05 17:23:50.452566", 
    "finished": 1, 
    "rc": 2, 
    "start": "2018-06-05 17:11:54.229451"
}

MSG:
---
non-zero return code
---
```

[`testout.txt` has][3]:

```
not ok 78 Ensure correct CNI plugin namespace/name/container-id arguments
...
# time="2018-06-05 17:21:20.807047363Z" level=error msg="Error adding network: failed to find plugin "cni_plugin_helper.bash" in path [/opt/cni/bin/ /opt/cni_plugin_helper.bash/bin]" 
# time="2018-06-05 17:21:20.807055428Z" level=error msg="Error while adding to cni network: failed to find plugin "cni_plugin_helper.bash" in path [/opt/cni/bin/ /opt/cni_plugin_helper.bash/bin]" 
...
# time="2018-06-05 17:21:20.807081687Z" level=info msg="About to del CNI network crionet_test_args (type=cni_plugin_helper.bash)" 
# time="2018-06-05 17:21:20.807093551Z" level=error msg="Error deleting network: failed to find plugin "cni_plugin_helper.bash" in path [/opt/cni/bin/ /opt/cni_plugin_helper.bash/bin]" 
# time="2018-06-05 17:21:20.807101036Z" level=warning msg="failed to destroy network for pod sandbox k8s_podsandbox1_redhat.test.crio_redhat-test-crio_1(d8e852c5f9cef11d1698db0476244d8df8895dc189f3d537690dbb19d6c73f42): failed to find plugin "cni_plugin_helper.bash" in path [/opt/cni/bin/ /opt/cni_plugin_helper.bash/bin]"
...
# time="2018-06-05 17:21:20.867178551Z" level=debug msg="ListPodSandboxResponse &ListPodSandboxResponse{Items:[],}" 
# time="2018-06-05 17:21:20.868514600Z" level=debug msg="Caught SIGTERM" 
# time="2018-06-05 17:21:20.868713116Z" level=error msg="Failed to start streaming server: http: Server closed" 
```

So looks like something SIGTERMed `crio`.  Not sure what that would have been.

[1]: https://github.com/kubernetes-incubator/cri-o/pull/1517#issuecomment-394535920
[2]: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_crio_integration_fedora/809/consoleFull#47208492158b6e51eb7608a5981914356
[3]: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_crio_integration_fedora/809/s3/download/gathered/artifacts/testout.txt

**Comment by wking** [comment]
I've pushed 9397e913e -> f60223068, rebasing onto master (no conflicts) and bumping libpod to 0.6.2 to pick up projectatomic/libpod#887.

**Comment by wking** [comment]
Rebased around #1649 (which touched some lines I'm removing here) with f60223068 -> 9f48bf44a.  I've left the libpod pull at 0.6.2 (it's floating in `vendor.conf`), because it's `pkg/hooks` hasn't changed since then.

**Comment by rhatdan** [comment]
@wking Needs another rebase, and then I will push to get this merged.

**Comment by wking** [comment]
> Needs another rebase...

Rebased around #1655 with 9f48bf44a -> 99fe854b1, which also takes advantage of a `Spec()` -> `Config` change following #1676.

**Comment by wking** [comment]
Is [the e2e_rhel failure][1] a flake?

```
TASK [run e2e tests]
***********************************************************
task path: /go/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/e2e.yml:75
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace

########## FINISHED STAGE: FAILURE: RUN THE CRI-O E2E TESTS [02h 18m 44s] ##########
Build step 'Execute shell' marked build as failure
```

I can't find anything that looks more specific.

[1]: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_crio_e2e_rhel/1196/consoleFull#145448644858b6e51eb7608a5981914356

**Comment by wking** [comment]
All green :).

**Comment by rhatdan** [comment]
@mrunalp @runcom PTAL
LGTM

**Comment by mrunalp** [comment]
@runcom PTAL

**Comment by wking** [comment]
Ping @runcom.  Would be nice to get this landed before it goes stale again ;)

**Comment by rhatdan** [comment]
I will merge.

**Pull request merged**
