### PR TITLE
Add image pull with signature integration test

### PR DESCRIPTION
**Pull request by runcom**
Close #748 

Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by runcom** [comment]
[retest]

**Comment by TomSweeneyRedHat** [comment]
LGTM, assumit Travis is happy.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
