### PR TITLE
Vendor in latest code.

### PR DESCRIPTION
**Pull request by rhatdan**
Add support for vendoring in containers/storage and ran
dep ensure

Need to get default storage for containers to include and default to
overlay2.
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
dep doesn't detect Godeps directory. We don't actually need to pull in the runc/Godeps directory. can you take that out from under vendor/

**Comment by rhatdan** [comment]
@mrunalp Thats  a lot cleaner

**Comment by mrunalp** [comment]
@rhatdan Thanks! Looks good. will wait for the tests to be green.

**Comment by runcom** [comment]
LGTM as well pending tests

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
