### PR TITLE
docs: Add missing `sudo` command in tutorial

### PR DESCRIPTION
**Pull request by williamsandrew**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Thanks for the touch up @williamsandrew.  I'm not sure why Travis isn't happy, will see if I can restart the test.

**Comment by rhatdan** [comment]
@williamsandrew You need to sign your commit.

git commit -a --amend -s

**Comment by williamsandrew** [comment]
Amended for the sign off. Should be good now

**Comment by rhatdan** [comment]
Will merge as soon as travis passes. Thanks @williamsandrew.

**Comment by rhatdan** [comment]
Only in docs, no need for E2e.

**Pull request merged**
