### PR TITLE
Vendor in latest containers/storage

### PR DESCRIPTION
**Pull request by rhatdan**
Container/storage has been enhanced to speed up the compiling and loading
of json files.  This should make make cri-o a little bit faster.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@runcom PTAL

**Comment by runcom** [comment]
LGTM, not sure we want this for v1 though, may be better to wait for this (but still test it)

**Comment by rhatdan** [comment]
V1 is out this would be for v1.8

**Comment by runcom** [comment]
Awesome

**Comment by rhatdan** [comment]
@mrunalp WDYT?  Did we create a 1.0 branch so that we could easily put fixes in for 1.0 issues, and then we can move to 1.8 support.

**Comment by mrunalp** [comment]
I have created a branch named 1.0.x for 1.0 fixes.

**Comment by runcom** [comment]
> I have created a branch named 1.0.x for 1.0 fixes.

I've renamed the branch to `release-1.0` following kube branch naming :yum:

**Pull request merged**
