### PR TITLE
.travis.yml: Add allowed-to-fail OS X compilation

### PR DESCRIPTION
**Pull request by wking**
As an initial step in continuous integration testing for @vbatts' cross-platform work.  Once we get this passing on OS X we can remove the `allow_failures` entry.  The best docs I could find for using `allow_failures` with [build stages][0] was [here][1], so that's the pattern I'm following.  Travis' OS X docs are [here][3].

[0]: https://docs.travis-ci.com/user/build-stages/
[1]: https://github.com/travis-ci/travis-ci/issues/7789#issuecomment-303685412
[3]: https://docs.travis-ci.com/user/reference/osx

### CODE REVIEW

**Comment by wking** [comment]
This looks like this approach is working, with Travis happy overall, [warning about the allowed failure][1], and [complaining about a missing `apt-get` on OS X][2].  I'll have to find a way to make those `before_install` commands conditional and not run them on the OS X worker.

[1]: https://travis-ci.org/kubernetes-incubator/cri-o/builds/350486504
[2]: https://travis-ci.org/kubernetes-incubator/cri-o/jobs/350486513#L86

**Comment by wking** [comment]
Got the install bits sorted, so I think this is good to merge.  Currently gets stuck [on][1]:

```
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
configure.ac:78: error: possibly undefined macro: AM_PATH_GLIB_2_0
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

during the [ostree build][2].  But that's why we're allowing failures.  This PR isn't about fixing them all, we can chip away in follow-up work.

[1]: https://travis-ci.org/kubernetes-incubator/cri-o/jobs/350679059#L200
[2]: https://github.com/kubernetes-incubator/cri-o/blob/e8c108d415d7de0fb890be95e17307b845a19c2c/Makefile#L217

**Comment by rhatdan** [comment]
@wking Won't this just be ignored?

**Comment by wking** [comment]
> Won't this just be ignored?

Mostly.  But folks working on OS X compat (@vbatts) can check it to see how they're doing.

**Comment by rhatdan** [comment]
Well I am fine with it.
@mrunalp @runcom WDYT

**Comment by wking** [comment]
I've pushed f06674b93, dropping the OSTree build from OS X runs because OSTree is Linux-specific.

**Comment by wking** [comment]
We got further in this time, with [the current limiter being `server/seccomp/seccomp.go`][1]:

```console
$ make testunit
go test -tags "seccomp btrfs_noversion exclude_graphdriver_devicemapper libdm_no_deferred_remove exclude_graphdriver_btrfs containers_image_ostree_stub  containers_image_ostree_stub" -cover github.com/kubernetes-incubator/cri-o/client github.com/kubernetes-incubator/cri-o/cmd/crio github.com/kubernetes-incubator/cri-o/lib github.com/kubernetes-incubator/cri-o/lib/sandbox github.com/kubernetes-incubator/cri-o/oci github.com/kubernetes-incubator/cri-o/pkg/annotations github.com/kubernetes-incubator/cri-o/pkg/registrar github.com/kubernetes-incubator/cri-o/pkg/storage github.com/kubernetes-incubator/cri-o/server github.com/kubernetes-incubator/cri-o/server/apparmor github.com/kubernetes-incubator/cri-o/server/metrics github.com/kubernetes-incubator/cri-o/server/seccomp github.com/kubernetes-incubator/cri-o/test/bin2img github.com/kubernetes-incubator/cri-o/test/checkseccomp github.com/kubernetes-incubator/cri-o/test/copyimg github.com/kubernetes-incubator/cri-o/types github.com/kubernetes-incubator/cri-o/utils github.com/kubernetes-incubator/cri-o/version
server/seccomp/seccomp.go:13:2: build constraints exclude all Go files in /Users/travis/gopath/src/github.com/kubernetes-incubator/cri-o/vendor/github.com/seccomp/libseccomp-golang
make: *** [testunit] Error 1
```

We probably need to stop [hardcoding the `seccomp` build tag][2] (although [again][3], I don't see a need to hold up this PR while we fix these sorts of things).

[1]: https://travis-ci.org/kubernetes-incubator/cri-o/jobs/350989467#L168
[2]: https://github.com/kubernetes-incubator/cri-o/blob/f7c1adf303b9380df5fe795ffa24b344ea70858b/Makefile#L17
[3]: https://github.com/kubernetes-incubator/cri-o/pull/1428#issuecomment-371509368

**Comment by mrunalp** [comment]
@runcom Can you take a look?

**Comment by wking** [comment]
I've just pushed 5d449568b to make the `seccomp` tag conditional on whether libseccomp is installed.

**Comment by wking** [comment]
With 5d44956, we're getting a bit [further into `testunit`][1]:

```
# github.com/kubernetes-incubator/cri-o/vendor/github.com/containerd/cgroups
vendor/github.com/containerd/cgroups/blkio.go:301:29: cannot use st.Rdev (type int32) as type uint64 in argument to major
vendor/github.com/containerd/cgroups/blkio.go:301:45: cannot use st.Rdev (type int32) as type uint64 in argument to minor
vendor/github.com/containerd/cgroups/memory.go:158:33: undefined: unix.SYS_EVENTFD2
# github.com/kubernetes-incubator/cri-o/vendor/github.com/mtrmac/gpgme
vendor/github.com/mtrmac/gpgme/data.go:4:11: fatal error: 'gpgme.h' file not found
 #include <gpgme.h>
          ^
1 error generated.
# github.com/kubernetes-incubator/cri-o/vendor/github.com/opencontainers/runc/libcontainer/configs
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go:128:11: undefined: Cgroup
# github.com/kubernetes-incubator/cri-o/test/checkseccomp
test/checkseccomp/checkseccomp.go:11:12: undefined: unix.Prctl
test/checkseccomp/checkseccomp.go:11:23: undefined: unix.PR_GET_SECCOMP
test/checkseccomp/checkseccomp.go:13:13: undefined: unix.Prctl
test/checkseccomp/checkseccomp.go:13:24: undefined: unix.PR_SET_SECCOMP
test/checkseccomp/checkseccomp.go:13:45: undefined: unix.SECCOMP_MODE_FILTER
make: *** [testunit] Error 2
```

and a bit further in the build:

```
go build -i -ldflags '-s -w -X main.gitCommit="7912f6cbdbd45fa0fb5ab5404313559aa6671d49" -X main.buildInfo=1520543740' -tags "btrfs_noversion exclude_graphdriver_devicemapper libdm_no_deferred_remove exclude_graphdriver_btrfs containers_image_ostree_stub   containers_image_ostree_stub" -o bin/crio github.com/kubernetes-incubator/cri-o/cmd/crio
# github.com/kubernetes-incubator/cri-o/vendor/github.com/containerd/cgroups
vendor/github.com/containerd/cgroups/blkio.go:301:29: cannot use st.Rdev (type int32) as type uint64 in argument to major
vendor/github.com/containerd/cgroups/blkio.go:301:45: cannot use st.Rdev (type int32) as type uint64 in argument to minor
vendor/github.com/containerd/cgroups/memory.go:158:33: undefined: unix.SYS_EVENTFD2
# github.com/kubernetes-incubator/cri-o/vendor/github.com/mtrmac/gpgme
vendor/github.com/mtrmac/gpgme/data.go:4:11: fatal error: 'gpgme.h' file not found
 #include <gpgme.h>
          ^
1 error generated.
# github.com/kubernetes-incubator/cri-o/vendor/github.com/opencontainers/runc/libcontainer/configs
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go:128:11: undefined: Cgroup
make: *** [crio] Error 2
```

But now that we're well into the Go code, I'm happy to leave the remaining work to @vbatts ;).

[1]: https://travis-ci.org/kubernetes-incubator/cri-o/jobs/351020823#L167

**Comment by rhatdan** [comment]
Lets merge when this passes the travis tests

**Comment by wking** [comment]
> Lets merge when this passes the travis tests

Is that “drop `allow_failures` and keep rebasing this branch as @vbatts cleans up the Go”?  Are we ever actually going to get there?  I'm fairly sure [our `PR_SET_CHILD_SUBREAPER` call][1] is Linux-specific.  I'd rather land this as it stands if folks here are interested in OS X usage, at least it makes it easy for them to see what's broken.

[1]: https://github.com/kubernetes-incubator/cri-o/blob/959afb79d4247891b6176b74609b1133cb939f1b/conmon/conmon.c#L1322

**Comment by rhatdan** [comment]
Since it passes travis test.  No reason for E2E.  Merging.

**Pull request merged**
