### PR TITLE
[wip] Unit test for server/sandbox_run.go

### PR DESCRIPTION
**Pull request by mdshuai**
test server/sandbox_run.go 
address part of https://github.com/kubernetes-incubator/cri-o/issues/893

Signed-off-by: DeShuai Ma <dma@redhat.com>

### CODE REVIEW

**Comment by mdshuai** [comment]
test error with `sandbox_run_test.go:248: Create fakeServer error, mkdir /var/run/crio: permission denied`

**Comment by rhatdan** [comment]
Could this be an SELinux issue?  Could you rebase and try again?

**Comment by rhatdan** [comment]
@mdshuai Are you still interested in this?

**Comment by rhatdan** [comment]
I am closing this because of lack of response, Reopen if you are still interested in working on it.

**Pull request closed without merging**
