### PR TITLE
server: add prometheus metrics for CRI operations

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

Added metrics to the prometheus endpoint about CRI operations

**- How I did it**

vim

**- How to verify it**

access `localhost:4242/metrics` on a node running CRI-O with kubernetes. Play with pods, images and everything. Refresh the metrics endpoint and notice metrics about CRI operations:
```
# HELP container_runtime_crio_operations Cumulative number of CRI-O operations by operation type.
# TYPE container_runtime_crio_operations counter
container_runtime_crio_operations{operation_type="create_container"} 3
container_runtime_crio_operations{operation_type="pull_image"} 1
container_runtime_crio_operations{operation_type="remove_pod_sandbox"} 1
container_runtime_crio_operations{operation_type="run_pod_sandbox"} 3
container_runtime_crio_operations{operation_type="stop_pod_sandbox"} 1
# HELP container_runtime_crio_operations_latency_microseconds Latency in microseconds of CRI-O operations. Broken down by operation type.
# TYPE container_runtime_crio_operations_latency_microseconds summary
container_runtime_crio_operations_latency_microseconds{operation_type="create_container",quantile="0.5"} 151
container_runtime_crio_operations_latency_microseconds{operation_type="create_container",quantile="0.9"} 94446
container_runtime_crio_operations_latency_microseconds{operation_type="create_container",quantile="0.99"} 94446
container_runtime_crio_operations_latency_microseconds_sum{operation_type="create_container"} 191602
container_runtime_crio_operations_latency_microseconds_count{operation_type="create_container"} 3
container_runtime_crio_operations_latency_microseconds{operation_type="pull_image",quantile="0.5"} 8.812615e+06
container_runtime_crio_operations_latency_microseconds{operation_type="pull_image",quantile="0.9"} 8.812615e+06
container_runtime_crio_operations_latency_microseconds{operation_type="pull_image",quantile="0.99"} 8.812615e+06
container_runtime_crio_operations_latency_microseconds_sum{operation_type="pull_image"} 8.812615e+06
container_runtime_crio_operations_latency_microseconds_count{operation_type="pull_image"} 1
container_runtime_crio_operations_latency_microseconds{operation_type="remove_pod_sandbox",quantile="0.5"} 48381
container_runtime_crio_operations_latency_microseconds{operation_type="remove_pod_sandbox",quantile="0.9"} 48381
container_runtime_crio_operations_latency_microseconds{operation_type="remove_pod_sandbox",quantile="0.99"} 48381
container_runtime_crio_operations_latency_microseconds_sum{operation_type="remove_pod_sandbox"} 48381
container_runtime_crio_operations_latency_microseconds_count{operation_type="remove_pod_sandbox"} 1
container_runtime_crio_operations_latency_microseconds{operation_type="run_pod_sandbox",quantile="0.5"} 148501
container_runtime_crio_operations_latency_microseconds{operation_type="run_pod_sandbox",quantile="0.9"} 149494
container_runtime_crio_operations_latency_microseconds{operation_type="run_pod_sandbox",quantile="0.99"} 149494
container_runtime_crio_operations_latency_microseconds_sum{operation_type="run_pod_sandbox"} 852142
container_runtime_crio_operations_latency_microseconds_count{operation_type="run_pod_sandbox"} 3
container_runtime_crio_operations_latency_microseconds{operation_type="stop_pod_sandbox",quantile="0.5"} 505562
container_runtime_crio_operations_latency_microseconds{operation_type="stop_pod_sandbox",quantile="0.9"} 505562
container_runtime_crio_operations_latency_microseconds{operation_type="stop_pod_sandbox",quantile="0.99"} 505562
container_runtime_crio_operations_latency_microseconds_sum{operation_type="stop_pod_sandbox"} 505562
container_runtime_crio_operations_latency_microseconds_count{operation_type="stop_pod_sandbox"} 1
``` 

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
@mrunalp @derekwaynecarr PTAL

**Comment by runcom** [comment]
I'll wait to test this out after #1130

**Comment by TomSweeneyRedHat** [comment]
LGTM, would be interested to know if this dings performance much.  I think no, but would be nice to verify.

**Comment by rhatdan** [comment]
LGTM
/test all

**Comment by rhatdan** [comment]
@mrunalp you should be sitting  under a palm tree.

**Comment by runcom** [comment]
I'm adding error metrics as well for CRI operations so hold on merging this :) and I'd love @derekwaynecarr to look at this as well before going ahead and merging

**Comment by runcom** [comment]
This is fully green and can be merged (I'll port the patch to release-1.0 once merged)

**Comment by weiwei04** [comment]
I see most of the instrument are for the grpc-server call, how about use a grpc-middleware, like https://github.com/grpc-ecosystem/go-grpc-prometheus? the code would be much clean.

@runcom

**Comment by runcom** [comment]
Yeah we may move to that as point I guess. This implementation is what kube is using as well though and I'd want to stick with it for now. But we can surely look at that lib.

**Comment by runcom** [comment]
We talked on IRC yesterday, I think he's OK with this and we can add other metrics later. Latencies were the main ones.

**Comment by rhatdan** [comment]
Ok I will merge then.  We can improve this in further PRs if necessary.

**Pull request merged**
