### PR TITLE
conmon: Don't leave zombies and fix cgroup race

### PR DESCRIPTION
**Pull request by alexlarsson**
Currently, when creating containers we never call Wait on the
conmon exec.Command, which means that the child hangs around
forever as a zombie after it dies.

However, instead of doing this waitpid() in the parent we instead
do a double-fork in conmon, to daemonize it. That makes a lot of
sense, as conmon really is not tied to the launcher, but needs
to outlive it if e.g. the cri-o daemon restarts.

However, this makes even more obvious a race condition which we
already have. When crio-d puts the conmon pid in a cgroup there
is a race where conmon could already have spawned a child, and
it would then not be part of the cgroup. In order to fix this
we add another synchronization pipe to conmon, which we block
on before we create any children. The parent then makes sure the
pid is in the cgroup before letting it continue.

### CODE REVIEW

**Comment by sameo** [comment]
LGTM

**Comment by mrunalp** [comment]
Commit needs to be signed and the tests stalled :/

**Comment by alexlarsson** [comment]
signed...

**Comment by runcom** [comment]
Intégration tests failing

**Comment by alexlarsson** [comment]
Looking at the details it seems like we can actually do the double fork for exec too.

**Comment by alexlarsson** [comment]
Ah, the exec case needs more work. Reverting that.

**Comment by alexlarsson** [comment]
Integration tests passed. I had to back out the double-fork for exec() support, because that requires further work. But I think we should try to get this landed now, so we can get rid of those zombies.

**Comment by runcom** [comment]
:+1:

**Comment by mrunalp** [comment]
This looks good but we have one other issue (on master as well). We were getting back the container creation error for terminal=true case by passing in a buffer from cri-o. However, since we are now duping over stdout/stderr, we don't capture the container creation error message anymore.

```
[root@dhcp-16-107 cri-o]# crioctl pod run --config test/testdata/sandbox_config.json                                                                                         
d5456c892a2e307d0e813fd3a48991357819a487e1c8bd4d0e1fb82b710b1242
[root@dhcp-16-107 cri-o]# vim test/testdata/container_config.json # Change command to "nonexistent"
[root@dhcp-16-107 cri-o]# crioctl ctr create --config test/testdata/container_config.json --pod d545
Creating container failed: rpc error: code = 2 desc = container create failed: container_linux.go:265: starting container process caused "exec: \"nonexistent\": executable file not found in $PATH"
[root@dhcp-16-107 cri-o]# vim test/testdata/container_config.json # Change tty to false
[root@dhcp-16-107 cri-o]# crioctl ctr create --config test/testdata/container_config.json --pod d545
Creating container failed: rpc error: code = 2 desc = error reading container (probably exited) json message: EOF # We used to get error message similar to tty=false case here.


```

**Comment by mrunalp** [comment]
Should we redirect errors from container creation to a file for both cases and then read that file from cri-o?

**Comment by runcom** [comment]
> Should we redirect errors from container creation to a file for both cases and then read that file from cri-o?

I just fear tons of IO for this, but otherwise sounds good to me.

**Comment by mrunalp** [comment]
Another option would be to use the stderr pipe like terminal=false case to capture the error. runc will make sure that container process stdio is duped to new tty slave fd correctly.

**Comment by mrunalp** [comment]
We could handle that in a different PR and merge this one once the tests get back here.

**Comment by mrunalp** [comment]
Found an issue while testing this. 
I ran:
```
./cluster/kubectl.sh run myshell  -it --image=busybox:1.26 -- sh
```
I see this in the journal for conmon's scope and conmon doesn't appear to be in the scope either:
```
[root@home cri-o]# journalctl -fu crio-default-myshell-2377903282-hksmt-0-myshell-0.scope
-- Logs begin at Fri 2017-01-13 07:18:08 PST. --
Jun 16 10:03:34 localhost.localdomain systemd[1]: crio-default-myshell-2377903282-hksmt-0-myshell-0.scope: Failed to add PIDs to scope's control group: No such process
Jun 16 10:03:34 localhost.localdomain systemd[1]: Failed to start crio-default-myshell-2377903282-hksmt-0-myshell-0.scope.
Jun 16 10:03:34 localhost.localdomain systemd[1]: crio-default-myshell-2377903282-hksmt-0-myshell-0.scope: Unit entered failed state.


[root@home cri-o]# ps -ef | grep conmon
root     13930  1696  0 10:03 ?        00:00:00 /usr/local/libexec/crio/conmon -s -c default-myshell-2377903282-hksmt-0-infra -u fd37f49cf5f1897a0d856d11ad42a94540a2c2b16755364aebf74c19c563ae61 -r /usr/local/sbin/runc -b /var/run/containers/storage/overlay2-containers/fd37f49cf5f1897a0d856d11ad42a94540a2c2b16755364aebf74c19c563ae61/userdata -p /var/run/containers/storage/overlay2-containers/fd37f49cf5f1897a0d856d11ad42a94540a2c2b16755364aebf74c19c563ae61/userdata/pidfile -l /var/log/pods/baaf9117-52b5-11e7-a0fe-54ee75105a2b/fd37f49cf5f1897a0d856d11ad42a94540a2c2b16755364aebf74c19c563ae61.log
root     14284  1696  0 10:03 ?        00:00:00 /usr/local/libexec/crio/conmon -s -c default-myshell-2377903282-hksmt-0-myshell-0 -u 3cd4eb0efbb26f23eb3eee7766b8471ec10776449a028e57dac3ca5c254b2f05 -r /usr/local/sbin/runc -b /var/run/containers/storage/overlay2-containers/3cd4eb0efbb26f23eb3eee7766b8471ec10776449a028e57dac3ca5c254b2f05/userdata -p /var/run/containers/storage/overlay2-containers/3cd4eb0efbb26f23eb3eee7766b8471ec10776449a028e57dac3ca5c254b2f05/userdata/pidfile -l /var/log/pods/baaf9117-52b5-11e7-a0fe-54ee75105a2b/myshell_0.log -t
root     26459 18441  0 10:07 pts/4    00:00:00 grep --color=auto conmon
[root@home cri-o]# cat /proc/14284/cgroup 
11:freezer:/
10:hugetlb:/
9:memory:/
8:devices:/user.slice
7:blkio:/
6:cpu,cpuacct:/
5:net_cls,net_prio:/
4:perf_event:/
3:pids:/user.slice/user-1000.slice/user@1000.service
2:cpuset:/
1:name=systemd:/user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service

```

**Comment by mrunalp** [comment]
I thought systemd Type=forking will help here but it didn't work (perhaps because it is not supported for scopes):
```
Failed to add conmon to sandbox cgroup: Cannot set property Type, or unknown property.
```
diff:
```
diff --git a/utils/utils.go b/utils/utils.go
index 8494c02..72ad3af 100644
--- a/utils/utils.go
+++ b/utils/utils.go
@@ -68,6 +68,7 @@ func RunUnderSystemdScope(pid int, slice string, unitName string) error {
        properties = append(properties, systemdDbus.PropSlice(slice))
        properties = append(properties, newProp("PIDs", []uint32{uint32(pid)}))
        properties = append(properties, newProp("Delegate", true))
+       properties = append(properties, newProp("Type", "forking"))
        properties = append(properties, newProp("DefaultDependencies", false))
        _, err = conn.StartTransientUnit(unitName, "replace", properties, nil)
        return err
```
We may have to add the process to cgroups from conmon if forking doesn't work for scopes :/

**Comment by alexlarsson** [comment]
I have code in flatpak for creating a scope. Maybe we can use that.

**Comment by alexlarsson** [comment]
I don't understand why this is not working though. At the time we're creating the scope we have not forked yet...

**Comment by alexlarsson** [comment]
The fixup fixes the error reporting issue by always creating a stderr pipe, which we always read errors from. We then handle error reporting the same way as for the non-terminal case.

**Comment by alexlarsson** [comment]
Fixed lint and added signoff

**Comment by sameo** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by mrunalp** [comment]
Awesome! LGTM

**Pull request merged**
