### PR TITLE
oci: more grep'able interface name

### PR DESCRIPTION
**Pull request by vbatts**
`git grep -wi store` is not nearly useful enough. Taking steps for
readability.

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vbatts** [comment]
perhaps it should be `ContainerStater` instead, because the whole notion of only having an in-memory implementation of this confuses that it is stored at all.

**Comment by vbatts** [comment]
silly editor is not doing `gofmt` like it's supposed too :-\. fixed. PTAL

**Comment by runcom** [comment]
LGTM thanks for splitting the container type in its own file (I don't feel strongly about `Store->ContainerStorer` but it's alright)

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
