### PR TITLE
Vendor in latest containers/image

### PR DESCRIPTION
**Pull request by umohnani8**
Adds support for credential helpers
Need it to work on fix for https://github.com/containers/image/pull/333

Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM if it passes tests.

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by mheon** [comment]
Travis is failing, looks like a missing vendor

**Comment by runcom** [comment]
LGTM when Travis is good, we need to grab the changes for external stores

**Comment by umohnani8** [comment]
Do I need to add `github.com/docker/docker-credential-helpers` to the vendor.conf as well?

**Comment by runcom** [comment]
Yup, you do

**Comment by umohnani8** [comment]
Got it! Fixed.

**Comment by runcom** [comment]
[retest]

**Pull request merged**
