### PR TITLE
Stop container first if it is running on RemoveContainer

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by runcom** [comment]
@mrunalp worth adding  a test? :angel:

**Comment by mrunalp** [comment]
Sure, I'll add one to this PR.

**Comment by mrunalp** [comment]
@runcom Added a basic test for ctr remove.

**Comment by runcom** [comment]
Thanks @mrunalp

**Pull request merged**
