### PR TITLE
Release 1.9.7

### PR DESCRIPTION
**Pull request by mrunalp**
Release v1.9.7

@runcom @rhatdan We need new rpm builds.

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM. Merge when tests complete and I will create new builds.

**Comment by mrunalp** [comment]
@rhatdan No, it can go into the release-1.9 branch.

**Comment by rhatdan** [comment]
I meant a tag not a branch.

**Pull request merged**
