### PR TITLE
Pids limit

### PR DESCRIPTION
**Pull request by mrunalp**
This adds a crio daemon level setting for container pids limit. We will add container level support once CRI supports it.

### CODE REVIEW

**Comment by runcom** [comment]
:+1:

**Comment by mrunalp** [comment]
travis seems to be having issues.

**Comment by rhatdan** [comment]
:+1:

**Comment by runcom** [comment]
Why did centos fail though?

**Comment by mrunalp** [comment]
Looks like centos doesn't have the pids cgroup setup :/

**Comment by mrunalp** [comment]
Rebased and added a test.

**Comment by runcom** [comment]
@mrunalp is there any way to check pids cgroup in test and skip in centos for instance?

**Comment by TomSweeneyRedHat** [comment]
Code LGTM except the Centos test fun.  Just curious why you picked a default max of 1,000 instead of 1,024.  Powers of 2 seems more the norm for this kind of stuff.

**Comment by rhatdan** [comment]
Googling around, I also see powers of 2 (1024)

**Comment by mrunalp** [comment]
I can change that to 1024.

**Comment by mrunalp** [comment]
@runcom I think we should switch Centos image to 7.3 (It is 7.2 lIRC) and that should hopefully fix more test issues on Centos.

**Comment by runcom** [comment]
> @runcom I think we should switch Centos image to 7.3 (It is 7.2 lIRC) and that should hopefully fix more test issues on Centos.

Yes, there was an issue with that ~3 weeks ago though - basically, the OS images which go into the RH CI are _controlled_ and at that time no CentOS 7.3 was in CI image list. I'll ask Jhonny where we are on that.

**Comment by mrunalp** [comment]
Updated the default limit to 1024 and added code to skip setting this when the pids cgroup controller is not mounted.

**Comment by mrunalp** [comment]
retest

**Comment by runcom** [comment]
Awesome.

**Pull request merged**
