### PR TITLE
test: Add networking settings for critest

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@runcom This is ready.

**Comment by runcom** [comment]
LGTM but, you need to tag new amis after I merge right?

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
We can wait for nightly to pick this up. Merging.

**Pull request merged**
