### PR TITLE
kpod: make --debug work

### PR DESCRIPTION
**Pull request by nalind**
The --debug flag is a global CLI flag, so parse it like one.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM, only think I was thinking of changing was going back to the old behaviour where a failure on --debug would produce a stack trace.

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
[retest]

**Comment by mrunalp** [comment]
[retest]

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
