### PR TITLE
test: Skip image pull with signature

### PR DESCRIPTION
**Pull request by mrunalp**
The registry has some issues. We can re-enable this once the issues are fixed.
@runcom @rhatdan @mtrmac PTAL
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
i'm :+1: for now

**Comment by mtrmac** [comment]
ACK as long as an issue is filed to revert this eventually.

**Comment by mrunalp** [comment]
@stevekuznetsov @chavafg, There is some issue launching kata job. Also, can we make it not count towards the merge for now?

**Comment by runcom** [comment]
Kata is erroring, besides, we need this to unblock other PR

**Pull request merged**
