### PR TITLE
Install to /usr/local to avoid conflicts with vendor binaries

### PR DESCRIPTION
**Pull request by jawnsy**
Closes: #300

Signed-off-by: Jonathan Yu <jawnsy@cpan.org>

### CODE REVIEW

**Comment by jawnsy** [comment]
Tested overriding both `PREFIX` and `DESTDIR` as follows...

Default, overrided `DESTDIR` only, installs to `/usr/local` under the specified directory:

```
$ make install DESTDIR=/home/jawnsy/projects/cri-o/tmp 
install -D -m 755 kpod /home/jawnsy/projects/cri-o/tmp/usr/local/bin/kpod
install -D -m 755 ocid /home/jawnsy/projects/cri-o/tmp/usr/local/bin/ocid
install -D -m 755 ocic /home/jawnsy/projects/cri-o/tmp/usr/local/bin/ocic
install -D -m 755 conmon/conmon /home/jawnsy/projects/cri-o/tmp/usr/local/libexec/ocid/conmon
install -D -m 755 pause/pause /home/jawnsy/projects/cri-o/tmp/usr/local/libexec/ocid/pause
install -d -m 755 /home/jawnsy/projects/cri-o/tmp/usr/local/share/man/man{1,5,8}
install -m 644 docs/kpod.1 docs/kpod-launch.1 -t /home/jawnsy/projects/cri-o/tmp/usr/local/share/man/man1
install -m 644 docs/ocid.conf.5 -t /home/jawnsy/projects/cri-o/tmp/usr/local/share/man/man5
install -m 644 docs/ocid.8 -t /home/jawnsy/projects/cri-o/tmp/usr/local/share/man/man8
install -D -m 644 ocid.conf /home/jawnsy/projects/cri-o/tmp/etc/ocid/ocid.conf
install -D -m 644 seccomp.json /home/jawnsy/projects/cri-o/tmp/etc/ocid/seccomp.json
$ tree tmp
tmp
├── etc
│   └── ocid
│       ├── ocid.conf
│       └── seccomp.json
└── usr
    └── local
        ├── bin
        │   ├── kpod
        │   ├── ocic
        │   └── ocid
        ├── libexec
        │   └── ocid
        │       ├── conmon
        │       └── pause
        └── share
            └── man
                ├── man1
                │   ├── kpod.1
                │   └── kpod-launch.1
                ├── man5
                │   └── ocid.conf.5
                └── man8
                    └── ocid.8
```

You can override `PREFIX` as well, for building vendor packages (rpm & deb):

```
$ make install DESTDIR=/home/jawnsy/projects/cri-o/tmp PREFIX=/home/jawnsy/projects/cri-o/tmp/usr
install -D -m 755 kpod /home/jawnsy/projects/cri-o/tmp/usr/bin/kpod
install -D -m 755 ocid /home/jawnsy/projects/cri-o/tmp/usr/bin/ocid
install -D -m 755 ocic /home/jawnsy/projects/cri-o/tmp/usr/bin/ocic
install -D -m 755 conmon/conmon /home/jawnsy/projects/cri-o/tmp/usr/libexec/ocid/conmon
install -D -m 755 pause/pause /home/jawnsy/projects/cri-o/tmp/usr/libexec/ocid/pause
install -d -m 755 /home/jawnsy/projects/cri-o/tmp/usr/share/man/man{1,5,8}
install -m 644 docs/kpod.1 docs/kpod-launch.1 -t /home/jawnsy/projects/cri-o/tmp/usr/share/man/man1
install -m 644 docs/ocid.conf.5 -t /home/jawnsy/projects/cri-o/tmp/usr/share/man/man5
install -m 644 docs/ocid.8 -t /home/jawnsy/projects/cri-o/tmp/usr/share/man/man8
install -D -m 644 ocid.conf /home/jawnsy/projects/cri-o/tmp/etc/ocid/ocid.conf
install -D -m 644 seccomp.json /home/jawnsy/projects/cri-o/tmp/etc/ocid/seccomp.json
$ tree tmp
tmp
├── etc
│   └── ocid
│       ├── ocid.conf
│       └── seccomp.json
└── usr
    ├── bin
    │   ├── kpod
    │   ├── ocic
    │   └── ocid
    ├── libexec
    │   └── ocid
    │       ├── conmon
    │       └── pause
    └── share
        └── man
            ├── man1
            │   ├── kpod.1
            │   └── kpod-launch.1
            ├── man5
            │   └── ocid.conf.5
            └── man8
                └── ocid.8
```

**Comment by runcom** [comment]
LGTM

**Comment by mrunalp** [comment]
@cyphar PTAL

**Comment by feiskyer** [comment]
LGTM

**Comment by rhatdan** [comment]
What about these?
```
ETCDIR ?= ${DESTDIR}/etc
ETCDIR_OCID ?= ${ETCDIR}/ocid
```
Looks like these would override the system defaults.

**Comment by mrunalp** [comment]
@rhatdan Maybe we don't touch files under /etc on make install?

**Comment by rhatdan** [comment]
```
	install -D -m 644 ocid.conf $(ETCDIR_OCID)/ocid.conf
	install -D -m 644 seccomp.json $(ETCDIR_OCID)/seccomp.json
```
These commands would replace /etc/ocid/ocid.conf and /etc/ocid/seccomp.json including any changes made by an administrator.  Potentially replacing them could cause the default cri-o package to blow up.

**Comment by jawnsy** [comment]
Very good catch, @rhatdan, thanks!  Does the build cause cri-o to account for a change in the path? That is, if we install to /usr/local/etc/ocid/ocid.conf, do we want `ocid start` to read from there by default, or do we always default to `/etc/ocid/ocid.conf` and require the user to specify `--config` for any local config?

For best usability, I'd suggest designing cri-o to:

* Apply sane defaults if the config is missing (similar to what `openshift start` does)
  * Possibly with an option to write out the effective config using `--write-config` or similar, so that an admin can see what config is in effect
  * Mrunal tells me that `ocid` already does this, maybe the answer is to avoid generating/installing the config by default?
* Ignore unknown config options (or log them at a log level not normally printed, like "Unknown directive 'abc' ignored"
  * This makes backward compatibility easier (if we drop a directive, or if we use a config from a newer cri-o than the current version, then this won't cause any problems). This is similar to what makes HTTP extensible (unknown headers are simply ignored)
  * We may already get this "for free" from our config library, so just need to verify

**Comment by rhatdan** [comment]
I am fine moving these to something like a 

make install-config
Option.  And removing them from make install.

**Comment by cyphar** [comment]
My opinion on this topic is that this should really be handled by RPM not by us. For example, in our RPM packages:

```
%files
%config(noreplace) ${_sysconfdir}/ocid/ocid.conf
%config(noreplace) ${_sysconfdir}/ocid/seccomp.json
```

I don't think we should be re implementing all of the various parts of a package manager inside of a `Makefile`...

**Comment by jawnsy** [comment]
@cyphar I had read @rhatdan's comment as saying that:

1. `make install` would no longer install configs;
1. `make install-config` would be provided as a convenience for developers ("overwrite my system config with defaults from ocid")
1. vendors (package maintainers) would use whatever configuration handling mechanism makes sense for their distro. deb-based distros would use `ucf`, rpm-based distros would use the mechanism you describe.

So, `make install-config` is just a convenience. Am I misunderstanding either of you here?

**Comment by cyphar** [comment]
@jawnsy I don't have a problem with `make install-config`. Sorry, I was making a note that nobody is expected to use this except developers (who should be able to figure out when they've overridden their system defaults). Just trying to make sure we don't overengineer a Makefile. :wink:

**Comment by rhatdan** [comment]
My idea was just to avoid mistakes.  The idea of /usr/local is to allow developers and testers to play with the code without screwing up their hosts.  By making the code work without config, and not installing default config on make install, we can achieve this.  Adding make install-config helps packagers to allow them to install a default config during the package build.

But I agree with @cyphar that the rpm.spec file is the best play to handle the config.

**Comment by jawnsy** [comment]
Heh, I've been learning all sorts of random GNU trivia. Here's how some [GNU docs](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html#Directory-Variables)
describe the variable (they're referring to autoconf/configure scripts, but the same concept applies here):

> **prefix**
>A prefix used in constructing the default values of the variables listed below. The default value of prefix should be /usr/local. When building the complete GNU system, the prefix will be empty and /usr will be a symbolic link to /. (If you are using Autoconf, write it as ‘@ prefix@’.)

It also says that we should install config to ${PREFIX}/etc by default:

> **sysconfdir**
>The directory for installing read-only data files that pertain to a single machine–that is to say, files for configuring a host. Mailer and network configuration files, /etc/passwd, and so forth belong here. All the files in this directory should be ordinary ASCII text files. This directory should normally be /usr/local/etc, but write it as $(prefix)/etc. (If you are using Autoconf, write it as ‘@ sysconfdir@’.)

I dunno if we can extrapolate these suggestions to Makefiles, but it seems reasonable? On the other hand, I think just installing to ${DESTDIR}/etc as we're doing today makes sense, given that we're going to move it to a new `install-config` target that isn't run by default. _shrug_

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
