### PR TITLE
build: Allow overwrite of BUILDTAGS variable

### PR DESCRIPTION
**Pull request by mikkeloscar**
This allows modifying the `BUILDTAGS` variable as documented in the README.

### CODE REVIEW

**Comment by rhatdan** [comment]
@mikkeloscar Thanks for this patch, but you have to sign your contribution.

**Comment by mikkeloscar** [comment]
@rhatdan fixed.

**Comment by TomSweeneyRedHat** [comment]
LGTM, thanks for the PR!

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
