### PR TITLE
contrib,test: bump cri-tools

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

bump cri-tools and adapt our code to it

**- How I did it**

vim

**- How to verify it**

CI

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
@mrunalp this is ready and picks up latest changes in crictl and new tests for critest

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
