### PR TITLE
sandbox: Force netns unmount and removal when restoring

### PR DESCRIPTION
**Pull request by sameo**
ns.Close() will not remove and unmount the networking namespace
if it's not currently marked as mounted.
When we restore a sandbox, we generate the sandbox netns from
ns.GetNS() which does not mark the sandbox as mounted.

Fix https://github.com/kubernetes-incubator/cri-o/issues/273

There currently is a PR open to fix that in the ns package:
https://github.com/containernetworking/cni/pull/342

but meanwhile this patch fixes a netns leak when restoring a pod.

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
👎 @runcom PTAL

**Comment by mrunalp** [comment]
Sorry I meant upvote 👍 :)

**Comment by runcom** [comment]
looks good, I'll test this out soon, meanwhile, @sameo would you add a comment or open an issue to track https://github.com/containernetworking/cni/pull/342 and revert this or fix this PR to take into account cni changes in that PR (so we don't forget)?

**Comment by sameo** [comment]
@runcom See issue #278.

**Comment by mrunalp** [comment]
LGTM

**Comment by runcom** [comment]
LGTM (no more leak after tests)

**Pull request merged**
