### PR TITLE
*: minor repo cleanups

### PR DESCRIPTION
**Pull request by cyphar**
Change the Makefile to properly require `OCID_LINK`, as well as moving `ocid.service` to `contrib/` (where it belongs).

Fixes: #145.
Signed-off-by: Aleksa Sarai asarai@suse.com

### CODE REVIEW

**Comment by cyphar** [comment]
Yeah. SUSE has signed the CLA, but they still need to link my email (and I'm not sure which one I'm meant to use). Should be sorted next week.

**Comment by rhatdan** [comment]
@cyphar Could you quickly create a man page to install and remove the systemd unit file.

**Comment by cyphar** [comment]
@rhatdan What do you mean by "create a man page to install"? Did you mean a make target?

**Comment by rhatdan** [comment]
Meant Makefile, but brain and fingers were not connected.

**Comment by mrunalp** [comment]
@cyphar I had to add my redhat email address to my github profile and then had to sign in through the details link on the CLA check on a PR for it to work for me.

**Comment by cyphar** [comment]
@mrunalp I was mistaken. SUSE hasn't signed the CLA, I'm working on it though.

**Comment by cyphar** [comment]
CLA has been fixed. Rebased. Also add an `install.systemd` target.

**Comment by rhatdan** [comment]
LGTM

**Comment by cyphar** [comment]
Merging.

**Pull request merged**
