### PR TITLE
Fix calico

### LINKED ISSUE #595: Cannot delete pods
CentOS 7.3
Kubernetes 1.6.4
runc 1.0.0-6.gite800860.el7
cri-o (83b33e826720bbf61929fed7e1a998cb728ba08f)

All installation works and `kubeadm init` finishes. Deploying the Calico network fails.

To clean things up, I deleted Calico's deployment but the pods could not be deleted.

Trying to delete them manually has no impact, same errors. Pods go into "Terminating" status and back to "Running" and "CrashLoopBackOff".

```
Jun 13 15:43:32 master kubelet: I0613 15:43:32.242582    2064 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/1dbd5307-504e-11e7-828b-020000000346-calico-cni-plugin-token-fbq8k" (spec.Name: "calico-cni-plugin-token-fbq8k") pod "1dbd5307-504e-11e7-828b-020000000346" (UID: "1dbd5307-504e-11e7-828b-020000000346").
Jun 13 15:43:32 master kubelet: I0613 15:43:32.521555    2064 kuberuntime_manager.go:458] Container {Name:calico-node Image:quay.io/calico/node:v1.3.0 Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:ETCD_ENDPOINTS Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:etcd_endpoints,Optional:nil,},SecretKeyRef:nil,}} {Name:CALICO_NETWORKING_BACKEND Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:calico_backend,Optional:nil,},SecretKeyRef:nil,}} {Name:CALICO_DISABLE_FILE_LOGGING Value:true ValueFrom:nil} {Name:FELIX_DEFAULTENDPOINTTOHOSTACTION Value:ACCEPT ValueFrom:nil} {Name:CALICO_IPV4POOL_CIDR Value:192.168.0.0/16 ValueFrom:nil} {Name:CALICO_IPV4POOL_IPIP Value:always ValueFrom:nil} {Name:FELIX_IPV6SUPPORT Value:false ValueFrom:nil} {Name:FELIX_LOGSEVERITYSCREEN Value:info ValueFrom:nil} {Name:IP Value: ValueFrom:nil}] Resources:{Limits:map[] Requests:map[cpu:{i:{value:250 scale:-3} d:{Dec:<nil>} s:250m Format:DecimalSI}]} VolumeMounts:[{Name:lib-modules ReadOnly:true MountPath:/lib/modules SubPath:} {Name:var-run-calico ReadOnly:false MountPath:/var/run/calico SubPath:} {Name:calico-cni-plugin-token-fbq8k ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Jun 13 15:43:32 master kubelet: I0613 15:43:32.521647    2064 kuberuntime_manager.go:458] Container {Name:install-cni Image:quay.io/calico/cni:v1.9.1 Command:[/install-cni.sh] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:ETCD_ENDPOINTS Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:etcd_endpoints,Optional:nil,},SecretKeyRef:nil,}} {Name:CNI_NETWORK_CONFIG Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:cni_network_config,Optional:nil,},SecretKeyRef:nil,}}] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:cni-bin-dir ReadOnly:false MountPath:/host/opt/cni/bin SubPath:} {Name:cni-net-dir ReadOnly:false MountPath:/host/etc/cni/net.d SubPath:} {Name:calico-cni-plugin-token-fbq8k ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Jun 13 15:43:32 master crio: time="2017-06-13 15:43:32.532282159Z" level=warning msg="requested logPath for ctr id d7325cf2019b95364c96aea784bfe96e440fa7fa2086e86f568300e8d57dbd42 is a relative path: install-cni_0.log"
Jun 13 15:43:32 master conmon: conmon <ninfo>: about to waitpid: 24175
Jun 13 15:43:32 master crio: [conmon:i]: about to waitpid: 24175
Jun 13 15:43:32 master crio: time="2017-06-13 15:43:32.919716790Z" level=info msg="Running conmon under slice kubepods.slice-kubepods_burstable.slice-kubepods_burstable_pod1dbd5307_504e_11e7_828b_020000000346.slice.slice and unitName crio-kube-system-calico-node-f15vz-1-install-cni-0.scope"
Jun 13 15:43:32 master systemd: Started crio-kube-system-calico-node-f15vz-1-install-cni-0.scope.
Jun 13 15:43:32 master systemd: Starting crio-kube-system-calico-node-f15vz-1-install-cni-0.scope.
Jun 13 15:43:32 master systemd: Scope libcontainer-24175-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Jun 13 15:43:32 master systemd: Scope libcontainer-24175-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Jun 13 15:43:32 master systemd: Created slice libcontainer_24175_systemd_test_default.slice.
Jun 13 15:43:32 master systemd: Starting libcontainer_24175_systemd_test_default.slice.
Jun 13 15:43:32 master systemd: Removed slice libcontainer_24175_systemd_test_default.slice.
Jun 13 15:43:32 master systemd: Stopping libcontainer_24175_systemd_test_default.slice.
Jun 13 15:43:32 master systemd: Started libcontainer container d7325cf2019b95364c96aea784bfe96e440fa7fa2086e86f568300e8d57dbd42.
Jun 13 15:43:32 master dockerd-current: time="2017-06-13T15:43:32.974758986Z" level=error msg="Handler for GET /containers/d7325cf2019b95364c96aea784bfe96e440fa7fa2086e86f568300e8d57dbd42/json returned error: No such container: d7325cf2019b95364c96aea784bfe96e440fa7fa2086e86f568300e8d57dbd42"
Jun 13 15:43:32 master systemd: Starting libcontainer container d7325cf2019b95364c96aea784bfe96e440fa7fa2086e86f568300e8d57dbd42.
Jun 13 15:43:32 master kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 13 15:43:33 master conmon: conmon <error>: Failed to create container: exit status 1
Jun 13 15:43:33 master crio: [conmon:e]: Failed to create container: exit status 1
Jun 13 15:43:33 master crio: time="2017-06-13 15:43:32.999284360Z" level=info msg="Received container pid: -1"
Jun 13 15:43:33 master kubelet: E0613 15:43:33.116258    2064 remote_runtime.go:181] CreateContainer in sandbox "d2b3066fa9fecb4cb4a1274e9ff6374f70c2fd1267a4ef62cfa73d089acf890f" from runtime service failed: rpc error: code = 2 desc = container create failed: container_linux.go:259: starting container process caused "chdir to cwd (\"/opt/cni/bin\") set in config.json failed: no such file or directory"
Jun 13 15:43:33 master kubelet: E0613 15:43:33.116361    2064 kuberuntime_manager.go:719] container start failed: rpc error: code = 2 desc = container create failed: container_linux.go:259: starting container process caused "chdir to cwd (\"/opt/cni/bin\") set in config.json failed: no such file or directory"
Jun 13 15:43:33 master kubelet: : Create Container Failed
Jun 13 15:43:33 master kubelet: I0613 15:43:33.116380    2064 kuberuntime_manager.go:742] checking backoff for container "calico-node" in pod "calico-node-f15vz_kube-system(1dbd5307-504e-11e7-828b-020000000346)"
Jun 13 15:43:33 master kubelet: I0613 15:43:33.116524    2064 kuberuntime_manager.go:752] Back-off 40s restarting failed container=calico-node pod=calico-node-f15vz_kube-system(1dbd5307-504e-11e7-828b-020000000346)
Jun 13 15:43:33 master kubelet: E0613 15:43:33.116562    2064 pod_workers.go:182] Error syncing pod 1dbd5307-504e-11e7-828b-020000000346 ("calico-node-f15vz_kube-system(1dbd5307-504e-11e7-828b-020000000346)"), skipping: [failed to "StartContainer" for "install-cni" with rpc error: code = 2 desc = container create failed: container_linux.go:259: starting container process caused "chdir to cwd (\"/opt/cni/bin\") set in config.json failed: no such file or directory"
Jun 13 15:43:33 master kubelet: : "Create Container Failed"
Jun 13 15:43:33 master kubelet: , failed to "StartContainer" for "calico-node" with CrashLoopBackOff: "Back-off 40s restarting failed container=calico-node pod=calico-node-f15vz_kube-system(1dbd5307-504e-11e7-828b-020000000346)"
Jun 13 15:43:33 master kubelet: ]
```

### PR DESCRIPTION
**Pull request by runcom**
Fix #595 

Together with https://github.com/kubernetes-incubator/cri-o/pull/598 this should fix calico

ref: https://github.com/projectcalico/calico/issues/852

### CODE REVIEW

**Comment by runcom** [comment]
@sameo @mrunalp PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by runcom** [comment]
@sameo just got calico fully working with mine and his patch :)

**Comment by sameo** [comment]
The sidecar DNS pod container is still failing, but this patch fixes the calico policy controller one.

**Comment by sameo** [comment]
LGTM

**Comment by runcom** [comment]
> The sidecar DNS pod container is still failing, but this patch fixes the calico policy controller one.

let's tackle this down!

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
