### PR TITLE
oci: pass through error output from runc

### PR DESCRIPTION
**Pull request by vbatts**
From http://pastebin.com/6qWez2aM you can see the old behavior on line 19, and the new behavior on line 23

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by runcom** [comment]
Looks good to me. Possible to add a basic smoke test?

**Comment by vbatts** [comment]
How do I do that?

**Comment by runcom** [comment]
Like running something which was usually failing with that cryptic "exit status 1" and now shows a prettier error. (unless that's get printed in the logs and not in the terminal output after a command ofc)

**Comment by mrunalp** [comment]
It may be hard to add a test for this without deliberately messing up the state from outside. There could be bugs of course which should be fixed but we can't rely on them for a test.

**Comment by vbatts** [comment]
Yeah. This error is due to getting into a partial and weird state.

**Comment by mrunalp** [comment]
LGTM

**Comment by runcom** [comment]
Fair enough :)

**Pull request merged**
