### PR TITLE
Use png for logo as github doesn't display the svg

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@runcom @rhatdan PTAL
cc: @mairin

**Comment by feiskyer** [comment]
@mrunalp Maybe update the link to ``, e.g.

**Comment by rhatdan** [comment]
I am fine with either fix.

**Comment by runcom** [comment]
yup, same here (and LGTM once fixed)

**Comment by mrunalp** [comment]
okay, updated to use rawgit cdn.

**Comment by runcom** [comment]
COOL!

**Comment by jawnsy** [comment]
96d5704f0c4d01ec7ac8617692c29cc3becc08f1c836e279570408f9bb63cde5

This makes me happy! However I think we should set a max width as well to match the PNG width we had before (presumably @mairin chose that because it looks best)

Looks like there's some example Markdown to do it here: https://gist.github.com/uupaa/f77d2bcf4dc7a294d109

**Pull request merged**
