### PR TITLE
Report error when arguments given to crio command

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://github.com/kubernetes-incubator/cri-o/issues/1088

**Comment by runcom** [comment]
Can we have a test  for this? Also, is this working with "crio config" subcommand?

**Comment by rhatdan** [comment]
Ok I will add and check.

**Comment by runcom** [comment]
LGTM we may want this in 1.0 branch as well

**Comment by rhatdan** [comment]
Passes all tests. I am going to merge.

**Pull request merged**
