### PR TITLE
Migrate integration tests task-list to an Ansible role

### PR DESCRIPTION
**Pull request by cevich**
This is a completely non-urgent, non-critical, mostly superficial change.  It should not alter any existing behaviors with one exception:

I added assertions to the playbook that formally validate the mentioned in this comment:

```
 ## This playbook expects --extra-vars "commit=<commit>"
 ## and either --extra-vars "pullrequest=<PR #>" or
 ## --skip-tags pr
```

Otherwise, there's no rush to merge.  My primary motivation here is to allow me to write an alternate playbook but re-use the same testing behaviors.  For example, the other playbook might perform VM provisioning/setup and result preparation/conditioning (hint, hint, wink, wink).  These additions aren't possible if all the key behaviors exist as tasks at the playbook level.

P.S.  I'm actually attempting to write an alternate playbook.  Having all this in a PR is good enough for me to move that effort forward.  Though even if it fails, moving toward using roles like this is generally considered a good practice (in general).

### CODE REVIEW

**Comment by cevich** [comment]
**N/B:** No PR testing is needed here at this time.

**Comment by cevich** [comment]
develretest

**Comment by cevich** [comment]
``--force`` push after ``rebase`` against master.  "Accidentally" tested this on my laptop (to confirm the provisioning playbook is working).  Surprise, it seems to work quite well.  Anyone care to '[retest]' (I wrote myself out of the list to protect myself from my big-mouth)? 😀

**Comment by rhatdan** [comment]
[retest]

**Comment by cevich** [comment]
Dropping this in favor of #927

**Pull request closed without merging**
