### PR TITLE
Fix ctr stop

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom PTAL. First commit is vendoring, the other two have the actual fixes.

### CODE REVIEW

**Comment by runcom** [comment]
@mrunalp awesome, thanks for taking care of that race

LGTM I'll wait tests to merge this

**Comment by runcom** [comment]
Travis seems a flaky one though, I've restarted it

**Comment by mrunalp** [comment]
@runcom Yeah, let's see if it passes. This works for me locally.

**Comment by runcom** [comment]
@mrunalp something wrong with apt-get on go1.6:

> W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  Hash Sum mismatch

I think it's just a network flake though - let's see if go1.7 passes

**Comment by runcom** [comment]
Green, merging

**Comment by mrunalp** [comment]
@runcom Thanks! :)

**Pull request merged**
