### PR TITLE
Max log size config

### PR DESCRIPTION
**Pull request by mrunalp**
This PR adds configuration for max log size.

### CODE REVIEW

**Comment by rhatdan** [comment]
What happens when the user specifies the log max size?  Should we document this in the man crio.conf man page?

**Comment by mrunalp** [comment]
@rhatdan We will truncate the file and start adding the newer entries. I will document this better.

**Comment by rhatdan** [comment]
[retest]

**Comment by runcom** [comment]
> [retest]

CI is broken Dan, do not retest till @cevich figures the error out

**Comment by rhatdan** [comment]
[retest]

**Comment by mrunalp** [comment]
Pushed code to update conmon to handle this.

**Comment by runcom** [comment]
Travis's failing.

**Comment by runcom** [comment]
@mrunalp for the sake of coverage, could you add a basic smoke test for this feature by using a small size?

**Comment by mrunalp** [comment]
Travis is green. I'll add a test.

**Comment by rhatdan** [comment]
[retest]

**Comment by mrunalp** [comment]
@stevekuznetsov Seeing some issue in e2e_rhel before the tests are run.

**Comment by stevekuznetsov** [comment]
Looks like EC2 dropped the other end of an `ssh` connection... unfortunately not much we can do about that other than retest.

**Comment by mrunalp** [comment]
Okay cool!

**Comment by runcom** [comment]
all good here

**Pull request merged**
