### PR TITLE
Bump containers/image vendored copy

### PR DESCRIPTION
**Pull request by rhatdan**
This pulls in the OCI v1.0 specification code allow us to support
1.0 images.

Signed-off-by: Dan Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
will wait for the tests to pass.

**Comment by rhatdan** [comment]
@nalind does this need some of the changes you have been adding for handling of aufs?

**Comment by rhatdan** [comment]
https://github.com/kubernetes-incubator/cri-o/pull/680

**Comment by mrunalp** [comment]
#680 is merged. This can be rebased now.

**Comment by mrunalp** [comment]
Closing in favor of the updated #687

**Pull request closed without merging**
