### PR TITLE
Add support cgroup config and systemd cgroups

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom PTAL

### CODE REVIEW

**Comment by mrunalp** [comment]
The library is too old in our Dockerfile (debian/ubuntu) and doesn't have function that I am using :/

**Comment by cyphar** [comment]
And this is where the fun begins. :wink:

**Comment by mrunalp** [comment]
@cyphar I added own macro to get past that :wink:

**Comment by runcom** [comment]
LGTM tests fine on my end :)

**Pull request merged**
