### PR TITLE
release v1.10.4

### PR DESCRIPTION
**Pull request by runcom**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
@mrunalp @rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM 
Will merge once travis passes.

**Comment by mrunalp** [comment]
We need to wait for #1642

**Comment by mrunalp** [comment]
#1642 is merged. We also need #1648

**Pull request merged**
