### PR TITLE
Make network namespace lifecycle management optional

### PR DESCRIPTION
**Pull request by mrunalp**
Port of #1378 to master.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
Passed first time. Trying integration rhel again.

**Comment by mrunalp** [comment]
@rhatdan @wking @runcom Looks like this PR does indeed workaround the RHEL issue. two successful runs in a row :)

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Pull request merged**
