### PR TITLE
vendor: Update godbus dependency to a389bd

### PR DESCRIPTION
**Pull request by mrunalp**
This should fix a race condition in godbus library where it tries to write to a closed channel causing a panic.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
Fingers crossed

**Comment by sjug** [comment]
Based on my testing the panic has been resolved with this PR.

**Comment by mrunalp** [comment]
@runcom This is ready.

**Pull request merged**
