### PR TITLE
CI: drop git-validation as it's never used

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
For the reference, just `master` branch is affected by this

**Comment by mrunalp** [comment]
LGTM

**Comment by nalind** [comment]
LGTM given https://github.com/kubernetes-incubator/cri-o/pull/1162#issuecomment-347561151

**Pull request merged**
