### PR TITLE
conmon: Remove info logs

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

Apply https://github.com/kubernetes-incubator/cri-o/pull/1436
  to master

### CODE REVIEW

**Comment by rhatdan** [comment]
@wking @mrunalp @runcom PTAL

**Comment by wking** [comment]
> @wking I also added a patch to remove the comments from constants.

That looks orthogonal to me, but they're all small, so I don't think having them grouped in a single PR is a big deal.  And both changes look good to me.

**Comment by rhatdan** [comment]
Yes, I am trying to avoid integration_rhel hell...

**Comment by mrunalp** [comment]
@rhatdan I see a merge commit in the PR. Added by mistake?

**Comment by wking** [comment]
> @rhatdan I see a merge commit in the PR. Added by mistake?

[He's batching][1] so he can get both changes in on a single lucky dice roll around #1424 ;).

[1]: https://github.com/kubernetes-incubator/cri-o/pull/1438#issuecomment-371642346

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
Green tests merging.

**Pull request merged**
