### PR TITLE
expand limits for tests

### PR DESCRIPTION
**Pull request by lsm5**
Borrowed from:
https://github.com/projectatomic/atomic-system-containers/pull/136

From: Antonio Murdaca <runcom@redhat.com>
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@runcom @mrunalp PTAL

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by lsm5** [comment]
changing the commit title a bit ...

**Comment by rhatdan** [comment]
Should this be back ported to v1.0?

**Comment by runcom** [comment]
Yeah, we would need this for the release-1.0 branch as well

**Comment by mrunalp** [comment]
LGTM @lsm5 Please cherry pick and make a PR for release-1.0 branch. Thanks!

**Comment by lsm5** [comment]
do we need backport to 1.0.0 if we're using 1.0.1 everywhere?

**Comment by rhatdan** [comment]
@lsm5 Make it for release-0 and then it will end up in 1.0.2

**Comment by lsm5** [comment]
yup, opened a PR on release-1.0

**Pull request merged**
