### PR TITLE
Improve error messages on missing runtime

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, does this fix #1215?

**Comment by rhatdan** [comment]
Not sure it fixes it, but does make it a bit easier to diagnose.

**Comment by mrunalp** [comment]
restarted travis

**Comment by rhatdan** [comment]
@mrunalp @runcom Ok to merge?

**Pull request merged**
