### PR TITLE
make conmon process's env configurable

### PR DESCRIPTION
**Pull request by Crazykev**
Signed-off-by: HaoZhang <crazykev@zju.edu.cn>

### CODE REVIEW

**Comment by cyphar** [comment]
Can you explain why this is necessary / what does it fix?

**Comment by Crazykev** [comment]
@cyphar Sure I should explain this. Some env value is very necessary for runtime, such as $PATH. For example, runc exec an external tool, this would fail if can't get the path of that tool without default $PATH.

**Comment by rhatdan** [comment]
Do we need to also keep cmd.Env?  Should we exec fully PATHd runc rather then taking a random runc off of the system?

**Comment by cyphar** [comment]
As a separate point, we need to switch away from `system`. But i'm doing that as part of the conmon logging PR I'm working on.

**Comment by mrunalp** [comment]
@Crazykev we should probably pass the full path to runc.

**Comment by runcom** [comment]
We do pass a full path if runc path is specified through --runtime flag in ocid

**Comment by Crazykev** [comment]
For now, it's true that we can pass the full path to runc, I can only find `runc ps` will invoke `ps` under $PATH, and in cri-o, we don't need that cmd. Actually I found this need when I try to integrate cri-o with runv (we will throw a proposal later). runv will invoke some tools(like `qemu`, `virsh`, `iptables`) that did not pass the full path to it.

**Comment by Crazykev** [comment]
@rhatdan I drop cmd.Env because I think it is empty at first.

**Comment by mrunalp** [comment]
I have no strong objections to this. It shouldn't really affect how runc is handled. Does anyone have any arguments against merging?

**Comment by rhatdan** [comment]
I am worried about information leak from the host into the containers.  We perhaps want to setup a clean environment to hand to the container.

**Comment by cyphar** [comment]
`cmd.Env` won't leak into the container, but my main worry is if someone did something silly like set `LISTEN_FDS` or similarly lovely env options that runC would pick up. I'd prefer if we explicitly copied the environment variables that we want to preserve, not copy all of them.

**Comment by mrunalp** [comment]
@cyphar Fair enough. @Crazykev could you update the PR accordingly?

**Comment by Crazykev** [comment]
@cyphar @mrunalp agreed. What else env variables do we need except for $PATH?

**Comment by Crazykev** [comment]
@mrunalp updated.

**Comment by rhatdan** [comment]
I still think this should be a hard coded path.  The PATH environment could be very different between running the service in systemd versus an administrator running it manually.  If we explicitly want the PATH to be variable versus just set to a default PATH like the following, I am fine with it.

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
or better
PATH=/usr/bin:/usr/sbin

**Comment by Crazykev** [comment]
@rhatdan I was wondering why not add /bin and /sbin in our default PATH, thay are the most common ones and many distro package will install there. 
Just like sudo user's PATH in my local environment is `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

**Comment by cyphar** [comment]
Why can't we just make it configurable. Add another field to `ocid.conf` which is the PATH that we're passing. In fact, you could go even further and provide a `conmon_env` option which specifies the list of environment variable settings you wish to apply. This would be better IMO than arguing about what a sane hard-coded value is.

**Comment by Crazykev** [comment]
@cyphar Yeah, I think this is really a good idea.

**Comment by laijs** [comment]
making it configurable does increase flexible, I don't think it will add any significant value.
I suggest the maintainers just choose a value for it.

**Comment by cyphar** [comment]
@laijs My reasoning for wanting it to be configurable is because different runtimes might want different environment variables set. I can tell you what the runC defaults should be, but I don't know what other runtimes expect. Making it configurable makes life easier for everyone involved. Not to mention that an administrator might want to explicitly change `$PATH` for `conmon` -- if we hardcode it then there's nothing they can do about it.

**Comment by rhatdan** [comment]
I am fine with what ever path you choose, as long as it is constant, and not influenced by the callers environment.  Making it flexible and configurable is also fine, but unlikely to be used by many.

/bin and /sbin are Ok, but on my systems they are the same as /usr/bin and /usr/sbin.

**Comment by Crazykev** [comment]
Updated.

**Comment by rhatdan** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
