### PR TITLE
test: Test for OOM condition in a loop

### PR DESCRIPTION
**Pull request by mrunalp**
@rhatdan @runcom PTAL
This should take care of the integration_rhel failures.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
Hmm, this failed in CI again despite increasing the timeout to 300 seconds effectively. Logging in and looking.

**Comment by mrunalp** [comment]
and when I start the tests manually in the VM, they don't fail :/

**Comment by runcom** [comment]
@kargakis @stevekuznetsov we get all jenkins job not found

**Comment by runcom** [comment]
The oom passed here, I'm about to merge this once CI finishes!

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
With happy tests, LGTM

**Comment by runcom** [comment]
Come on!!

**Comment by mrunalp** [comment]
@stevekuznetsov Could you take a look? Looks like we can't find the jenkins job in CI.

**Comment by stevekuznetsov** [comment]
Hrm. I'm not seeing any failures to list those jobs on our end. I'll dig more -- this is weird.

**Pull request merged**
