### PR TITLE
1.9: Ensure ctl file is closed

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

#1288 for 1.9 branch.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM, but e2e_rhel isn't happy.

**Comment by mrunalp** [comment]
@runcom This is ready.

**Pull request merged**
