### PR TITLE
Update to latest version of kubernetes CRI API

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mpatel@redhat.com>

### CODE REVIEW

**Comment by feiskyer** [comment]
@mrunalp Maybe add another update to include streaming APIs (https://github.com/kubernetes/kubernetes/pull/35008)?

**Comment by mrunalp** [comment]
@feiskyer Pushed an update to the PR with those changes included. Thanks!

**Comment by mrunalp** [comment]
It seems to be picking up a wrong commit here, too @runcom :/ make lint worked for me fine locally.

**Comment by runcom** [comment]
@mrunalp probably you need a rebase? because that make lint failure is coming from https://github.com/kubernetes-incubator/cri-o/pull/170 - I wrongly merged it because it showed green, but it was a false green since GH was slow to reply to hooks probably :(

**Comment by mrunalp** [comment]
@runcom Ah, okay. Do we want to fix that up first? cc: @cyphar

**Comment by runcom** [comment]
I guess so, @cyphar ?

**Comment by cyphar** [comment]
Because of CLA you probably couldn't merge a fix I wrote (I'm working on it, sorry about that). The dumb thing is that `golint` is wrong... Here is the patch, but because of the CLA presumably you couldn't merge it.

```
diff --git a/oci/oci.go b/oci/oci.go
index 1b125f17fbd0..138103229ea7 100644
--- a/oci/oci.go
+++ b/oci/oci.go
@@ -192,8 +192,7 @@ func (r *Runtime) UpdateStatus(c *Container) error {
                if err != nil {
                        return fmt.Errorf("failed to find container exit file: %v", err)
                }
-               st := fi.Sys().(*syscall.Stat_t)
-               c.state.Finished = time.Unix(int64(st.Ctim.Sec), int64(st.Ctim.Nsec))
+               c.state.Finished = utils.StatCtime(fi)

                statusCodeStr, err := ioutil.ReadFile(exitFilePath)
                if err != nil {
diff --git a/utils/utils_32bit.go b/utils/utils_32bit.go
new file mode 100644
index 000000000000..02555116a710
--- /dev/null
+++ b/utils/utils_32bit.go
@@ -0,0 +1,14 @@
+// +build 386 ppc
+
+package utils
+
+import (
+       "os"
+       "syscall"
+       "time"
+)
+
+func StatCtime(fi os.FileInfo) time.Time {
+       st := fi.Sys().(*syscall.Stat_t)
+       return time.Unix(int64(st.Ctim.Sec), int64(st.Ctim.Nsec))
+}
diff --git a/utils/utils_64bit.go b/utils/utils_64bit.go
new file mode 100644
index 000000000000..7401bf254c5d
--- /dev/null
+++ b/utils/utils_64bit.go
@@ -0,0 +1,14 @@
+// +build !386,!ppc
+
+package utils
+
+import (
+       "os"
+       "syscall"
+       "time"
+)
+
+func StatCtime(fi os.FileInfo) time.Time {
+       st := fi.Sys().(*syscall.Stat_t)
+       return time.Unix(st.Ctim.Sec, st.Ctim.Nsec)
+}
```

**Comment by mrunalp** [comment]
okay finally green! @runcom PTAL

**Comment by runcom** [comment]
LGTM

**Pull request merged**
