### PR TITLE
Fix a couple of bugs in our use of containers/storage and containers/image

### PR DESCRIPTION
**Pull request by nalind**
* Switch to using storage APIs that don't bypass locking and synchronization.
* Properly close `Image` objects in a couple of places that we weren't.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
:+1:  will wait for jenkins.

**Comment by rhatdan** [comment]
@mrunalp Jenkins looks like it never finished.  :^(

**Comment by mrunalp** [comment]
retest

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
