### PR TITLE
test: Add task to enable xfs pquota support

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@stevekuznetsov @rhatdan PTAL

**Comment by mrunalp** [comment]
This is safe to run every time because adds the arguments only if it can't find them.

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
@stevekuznetsov Did the ami job pass on this?

**Comment by stevekuznetsov** [comment]
Doesn't look like it triggered. Hm.

**Comment by cevich** [comment]
Tentative NAK (can be fixed later).  I'll send an e-mail b/c it's likely non-obvious...

**Comment by stevekuznetsov** [comment]
EC2 API timeout on AMI creation again ... 

/test ami

**Comment by mrunalp** [comment]
The changes in this PR need a reboot. I started with the 7.4 ami we had discussed, applied this change and was able to reboot successfully.

**Comment by mrunalp** [comment]
Hmm, looking at the ami_rhel logs, it doesn't look like we are starting from a RHEL 7.4 AMI. We need that to ensure that rootfs is formatted correctly.

**Comment by mrunalp** [comment]
Rebased.

**Comment by stevekuznetsov** [comment]
/lgtm
for Ansible

**Comment by rhatdan** [comment]
I thought this was causing issues with Fedora systems running ext4?

**Pull request merged**
