### PR TITLE
kpod: avoid digging into unpublished formats

### PR DESCRIPTION
**Pull request by nalind**
* Now that the storage library provides a public field for storing an image's creation date, use that instead of trying to parse metadata that's in a format that only the image library really knows.  It's still not the right value, but once we merge #654 or something like it, it will be correctly populated.
* Since we're already parsing the image's configuration blob in `GetImageCopyData()`, don't try to do it a second time in `GetImageData()`, which calls it.
* Calculate an image's digest by digesting its manifest instead of trying to parse metadata that's in a format that only the image library really knows.

### CODE REVIEW

**Comment by rhatdan** [comment]
@14rcole PTAL

**Comment by nalind** [comment]
For reference, this switches us to using some newer API features that weren't there back when we were looking at merging similar logic into `buildah` in https://github.com/projectatomic/buildah/pull/155.

**Comment by mrunalp** [comment]
retest

**Comment by 14rcole** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
