### PR TITLE
Vendor in files for runc/libcontainer

### PR DESCRIPTION
**Pull request by 14rcole**
vndr was previously removing .go files in runc/libcontainer since they weren't used anywhere in cri-o, but kpod stats will use them

Signed-off-by: Ryan Cole <rcyoalne@gmail.com>

### CODE REVIEW

**Comment by 14rcole** [comment]
@rhatdan @mrunalp

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mrunalp** [comment]
This should come in as part of the kpod stats PR so we don't have to work around vndr.

**Comment by 14rcole** [comment]
It looks like libcontainer has some dependencies not listed in cri-o's vendor.conf.  If I vendor them in, is there a particular version I should specify or can I just stick with HEAD?

**Comment by mrunalp** [comment]
vndr should pull in whatever we are importing in the code. Are we missing any libcontainer vendors right now?

**Comment by 14rcole** [comment]
libcontainer wasn't used in the code previously, so the code wasn't pulled in.  kpod stats, which I am working on now though, does import libcontainer

**Comment by 14rcole** [comment]
I can vendor it in as a part of kpod stats, but I thought that vendors were supposed to go in separate PRs

**Comment by mrunalp** [comment]
Let us vendor it with the PR that needs it otherwise it breaks vndr.

**Pull request closed without merging**
