### PR TITLE
vendor: update c/image to handle text/plain from registries

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

same as  #1351 but for master

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
@mrunalp @rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM
/test all

**Comment by TomSweeneyRedHat** [comment]
@runcom fyi, travis ci isn't happy here either.  Do you need the version change here too?

**Pull request merged**
