### PR TITLE
Bump up version to rc 1

### PR DESCRIPTION
**Pull request by mrunalp**
Closes #861

### CODE REVIEW

**Comment by mrunalp** [comment]
[retest]

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
:tada:

**Comment by mrunalp** [comment]
@runcom @rhatdan Can one of you please merge? :)

**Comment by runcom** [comment]
I'll merge after Travis :)

**Pull request merged**
