### PR TITLE
makefile: add make arguments

### PR DESCRIPTION
**Pull request by cyphar**
This simplifies installation and building on various architectures and distributions. For example, openSUSE doesn't have a separate `%{_libexecdir}` so we need to keep that in mind.

Signed-off-by: Aleksa Sarai asarai@suse.de

### CODE REVIEW

**Comment by rhatdan** [comment]
:+1:

**Comment by runcom** [comment]
@cyphar you need to sign CLA, LGTM otherwise

**Comment by cyphar** [comment]
@runcom I'm working on the SUSE side of things to get a CLA signed. Hopefully it'll be sorted soon.

**Comment by runcom** [comment]
> @runcom I'm working on the SUSE side of things to get a CLA signed (since I don't think that we've signed the CLA for kubernetes). Hopefully it'll be sorted soon.

ack, just ping me to merge this after you figure that out, thx

**Comment by mikebrow** [comment]
LGTM

**Comment by cyphar** [comment]
CLA fixed @runcom.

**Comment by runcom** [comment]
@cyphar need rebase

**Comment by cyphar** [comment]
Rebased :P

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
