### PR TITLE
1.9: container_status: expose LogPath as requested by the CRI

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

Backport to 1.9

@runcom @rhatdan PTAL

### CODE REVIEW

**Comment by runcom** [comment]
LGTM, silly us

**Comment by vrothberg** [comment]
We are currently running into issues using `crictl logs` in our deployments and this ultimately seems to fix the issue. Are there plans to release a new 1.9.x? (we need that fix quite soon and I am considering to just patch our package for a given time)

**Comment by runcom** [comment]
> We are currently running into issues using crictl logs in our deployments and this ultimately seems to fix the issue. Are there plans to release a new 1.9.x? (we need that fix quite soon and I am considering to just patch our package for a given time)

we  will tag a new 1.9.x release after we merge this for sure :)

**Comment by mrunalp** [comment]
Looks like we are hitting https://github.com/kubernetes/kubernetes/issues/58956 in the tests.

**Comment by mrunalp** [comment]
I have added a commit to update the k8s deps.

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
This can be merged.

**Comment by feiskyer** [comment]
👍

**Pull request merged**
