### PR TITLE
travis: bump up go versions

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by wking** [comment]
Yeah, still has the same [1.10 lint error][1] we [saw][2] when #1296 tried to bump to 1.10.

[1]: https://travis-ci.org/kubernetes-incubator/cri-o/jobs/344073685#L1113
[2]: https://github.com/kubernetes-incubator/cri-o/pull/1296#issuecomment-361782530

**Comment by rhatdan** [comment]
Are there new versions of Go that we should test against?  Or is this a bug in our code?

**Comment by rhatdan** [comment]
@mrunalp needs a rebase.

**Comment by rhatdan** [comment]
@mrunalp Needs a rebase.

**Comment by mrunalp** [comment]
Rebased.

**Comment by mrunalp** [comment]
@rhatdan @runcom green now. This is travis only so we don't need to run other tests.

**Comment by rhatdan** [comment]
LGTM.
Merging.

**Pull request merged**
