### PR TITLE
Conmon should not be installed in /usr/bin.

### PR DESCRIPTION
**Pull request by rhatdan**
This pull request includes the man page pull, will rebase when that gets merged.

### CODE REVIEW

**Comment by runcom** [comment]
+1 but we'll need a flag to ocid like `--conmon` to be able to specify another custom path to conmon (e.g. while developing), I guess a follow up it's fine though

LGTM

**Comment by mrunalp** [comment]
Looks fine, but needs rebase.

**Comment by runcom** [comment]
make lint failed:
```
$ make lint
mkdir -p /home/travis/gopath/src/github.com/kubernetes-incubator/cri-o/vendor/src/github.com/kubernetes-incubator
ln -sfn /home/travis/gopath/src/github.com/kubernetes-incubator/cri-o /home/travis/gopath/src/github.com/kubernetes-incubator/cri-o/vendor/src/github.com/kubernetes-incubator/cri-o
checking lint
oci/oci.go:23:7:warning: don't use ALL_CAPS in Go names; use CamelCase (golint)
oci/oci.go:23:7:warning: exported const CONMON_PATH should have comment or be unexported (golint)
make: *** [lint] Error 1
```

**Comment by rhatdan** [comment]
Update conmon change to include option. Not that familiar with the code, so hopefully I did it correctly.

**Comment by runcom** [comment]
LGTM

**Pull request merged**
