### PR TITLE
don't gzip the manpages

### PR DESCRIPTION
**Pull request by laijs**
let the package builders of the distros do it

Signed-off-by: Lai Jiangshan <jiangshanlai@gmail.com>

### CODE REVIEW

**Comment by cyphar** [comment]
We should just remove `gzip` from the Makefile entirely -- `rpm` will automatically gzip man pages for us, and I'm fairly sure other package builders have similar features.

Also, you need to sign the CLA to contribute.

**Comment by laijs** [comment]
I had signed the CLA, how long will it take effect?

**Comment by laijs** [comment]
> We should just remove gzip from the Makefile entirely 

yes, we need at least one pr(a new one or just use this workaround) to do it and make it work in my centos box.

**Comment by runcom** [comment]
I'd remove gzip entirely

**Comment by cyphar** [comment]
Sorry, I should've clarified. I'm asking if rather than adding this workaround we just drop our use of `gzip` entirely -- so we install uncompressed man pages. There was some post-merge discussion in #141 which I agree with -- it's not our job to compress man pages -- that's `rpm`'s job.

**Comment by laijs** [comment]
I just updated the pr to remove the gzip directly.

**Comment by cyphar** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by laijs** [comment]
sorry, I forgot the clean/uninstall part.

**Comment by runcom** [comment]
apparently we did as well :disappointed:

**Comment by cyphar** [comment]
@laijs Yeah, whoops. Can you open another PR to fix that?

**Comment by laijs** [comment]
there is still a problem which was introduced by #141.
although my prs almost revert #141, the problem still exists.

```
make clean   # remove the docs/*.[58]
make install # failed, stderr:
             # install -m 644  /usr/share/man/man8
             # install: missing destination file operand after ‘/usr/share/man/man8’
make install # success. (the above make install provided the docs/*.[58])
```

The reason is that `$(wildcard docs/*.5)` is calculated when the makefile is loaded, not when the install-shell-script is executed.

we should use `$(wildcard docs/*.5.md)` and calculate docs/%.5 from it.
maybe we should introduce `make install-docs`.

**Comment by rhatdan** [comment]
Yes lets do that.

**Comment by cyphar** [comment]
Did it in #161.

**Comment by rhatdan** [comment]
Excellent.

**Pull request merged**
