### PR TITLE
Modified namespace field in json struct

### PR DESCRIPTION
**Pull request by umohnani8**
The namespace field was not being omitted when empty in the json

Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@rhatdan @mheon PTAL

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
Can you add a test?

**Comment by umohnani8** [comment]
There is already a test for the --ns case. Unless you want me to add a different kind of test?

**Comment by rhatdan** [comment]
I want you to make sure that the json test without the ns does not return ns data.

**Comment by umohnani8** [comment]
Added test

**Comment by umohnani8** [comment]
[retest]

**Comment by umohnani8** [comment]
@rhatdan tests passed

**Pull request merged**
