### PR TITLE
test: Switch to go 1.11

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@rhatdan @runcom This is ready.

**Comment by vrothberg** [comment]
LGTM

You were super fast :) I think we can update Travis as well.

**Comment by runcom** [comment]
should we move this as well https://github.com/kubernetes-incubator/cri-o/blob/master/Dockerfile#L1?

**Comment by mrunalp** [comment]
Can we get this in? I'll open a follow-on to fixup the Dockerfile and travis.

**Comment by runcom** [comment]
> Can we get this in? I'll open a follow-on to fixup the Dockerfile and travis.

ack ack ack

**Pull request merged**
