### PR TITLE
Fix install of unit file and configuration file

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Dan Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Sorry these are still broken.  The ocid.config file is being installed in /usr/etc/ocid.conf and the systemd unit file was being created as the directory name.

**Comment by mrunalp** [comment]
LGTM

**Comment by cyphar** [comment]
IMO `$(PREFIX)/lib/systemd/system/` should be a makefile argument like the others...

**Comment by rhatdan** [comment]
Sure, if this is installed in different directories in different distributions.

**Comment by rhatdan** [comment]
I was also debating removing this altogether from the Makefile and moving it to contrib/systemd/Makefile.

**Pull request merged**
