### PR TITLE
Block use of /proc/acpi from inside containers

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by rhatdan** [comment]
Note this is currently blocked by SELinux.

**Comment by cyphar** [comment]
It's also blocked by AppArmor.

**Comment by mrunalp** [comment]
@runcom Let us get this backported to other branches as well.

**Comment by wking** [comment]
containerd/containerd#2443 also blocks `/proc/keys`.  Do we want to do that as well?

**Comment by runcom** [comment]
Why are they blocking keys as well? We can do that, @wking would you open a PR?

**Comment by cyphar** [comment]
Because keys aren't namespaced and you can see all of the host's keys (though permissions and seccomp profiles mean you can't do much with them). Personally I think our masking implementations are pretty busted -- we should be whitelisting stuff in `/proc` we know is safe (this is what the AppArmor profile does).

**Pull request merged**
