### PR TITLE
oci: Use container ID as ID instead of container name

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mpatel@redhat.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
cc: @rhatdan 
We still need to wait for the jenkins CI on this one.

**Comment by runcom** [comment]
Tests failed on this

**Comment by mrunalp** [comment]
Updated.

**Comment by runcom** [comment]
Looks ok

**Comment by runcom** [comment]
retest

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
