### PR TITLE
Fix typo in crictl environment variable export

### PR DESCRIPTION
**Pull request by marcov**
I corrected the wrong export command and the env variable name for the crictl tool.

### CODE REVIEW

**Comment by rhatdan** [comment]
@marcov Need to sign the Kuernetes CLA.
LGTM

**Comment by marcov** [comment]
CLA signed

**Comment by runcom** [comment]
LGTM, thanks for this!

**Comment by rhatdan** [comment]
Will merge when travis passes.

**Comment by TomSweeneyRedHat** [comment]
and we have happy green tests now.

**Pull request merged**
