### PR TITLE
Remove VERSION file

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fix https://github.com/kubernetes-incubator/cri-o/issues/1102

**Comment by rhatdan** [comment]
Looks like we only removed version file from Release-1.0 not from Master.

**Comment by TomSweeneyRedHat** [comment]
LGTM with happy tests.

**Comment by runcom** [comment]
LGTM thanks Dan

**Comment by rhatdan** [comment]
Passes tests no reason to do E2E merging.

**Pull request merged**
