### PR TITLE
Fix clone k8s

### PR DESCRIPTION
**Pull request by cevich**
Fix e2e test dependency on building k8s
    
    These two should not be tightly-coupled.  e.g. for RPM testing, the
    packages will be built/installed, then e2e tests will run.  Having k8s
    secondarily built/installed will seriously screw with rpm-building and
    testing.
    
    Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
We need that to support different branches, where is that failing for you? @mrunalp ptal

**Comment by mrunalp** [comment]
@cevich What problem are we trying to solve here? It is the way it is because we want to cache kube build for faster bug fixes into 1.0 branch but still allow newer fixes to go into master at the expense of building kube in e2e. 

What we would really really like is a way to tag the ami on the basis of target branch.

**Comment by cevich** [comment]
>We need that to support different branches, where is that failing for you.

Aye, I hopefully moved this task in such a way that should still work...

**Comment by cevich** [comment]
> What problem are we trying to solve here?

Mmm, I mentioned y'all in the commit that introduced this.

>  It is the way it is because we want to cache kube build for faster bug fixes into 1.0 branch

Ahh okay, maybe then we should just set ``force: true`` on the ``git`` task?

**Comment by cevich** [comment]
> Mmm, I mentioned y'all in the commit that introduced this.

ofc I can't find it now...oh here it is: https://github.com/kubernetes-incubator/cri-o/commit/4dce8e12a0ca0770df3bfb1ae42c106912669365

I'm affraid I ran into this by accident, so no idea if it'll reproduce again...it may be due to some clash between AMI-state?.  I think @mrunalp is right, we need some better ami/cache tagging magic 😖  Would you mind prioritizing [that on my trello card](https://trello.com/c/Uexpad3K)?  

...okay I'll pick this up again next week..for now, just FYI in case y'all reproduce this anywhere else.

**Comment by runcom** [comment]
We can close this then, anyone can search the github repo ;)

**Comment by cevich** [comment]
@runcom oh no, this is an actual problem that needs fixing.The playbook must only make necessary changes, no matter what combination of tags is used.  Remember, declarative *not* imperative.

The problem is cloning of the k8s repo task happens **twice**.  Hence the second one will fail any time after k8s(?) is built (which changes the cloned repo).  Tasks should not be duplicated in this way, it's asking for trouble.

**Comment by cevich** [comment]
@runcom  uggg, I cannot re-open this PR *and* it's necessary *and* it passed all the tests.  

@rhatdan please help.  Things are steaming forward way too fast, without actually considering the big picture or others experience / input.  I feel disinclined to participate in a community where both my contributions and good-intentions are ignored.  it's not playing nice in the sandbox 😞

**Comment by mrunalp** [comment]
Reopening. I am a bit confused as tests are passing on PRs going in to master despite the two clones. What we want to do is keep the clone in ami but override that in master in a safe manner.

**Comment by runcom** [comment]
Alright, nothing is broken right now, so hold on merging this till we actually see and understand that something IS broken somewhere in the flow. As it doesn't seem, I don't want to risk in the following week.

**Comment by runcom** [comment]
It seems from the comments test ami was broken but I can't see where it's actually failing in the CI. When we merged my PR everything was working just fine with slash test ami.

**Comment by cevich** [comment]
> Reopening. I am a bit confused as tests are passing  on PRs going in to master despite the two clones.
> What we want to do is  keep the clone in ami but override that in master in a safe manner.

Thanks @mrunalp and also for the 'desired goal' info.  Yes, safety is my goal as well...hence this PR 😀  -  I've stumbled across trouble once, and maybe it's reproducible.  Do you know off-hand, about how long the kube build takes?  Are we talking about saving 30-seconds or 10-minutes?

> Alright, nothing is broken right now, so hold on  merging this till we actually see and understand that
> something IS  broken somewhere in the flow. As it doesn't seem, I don't want to risk  in the following week.

Yes @runcom , hence " I'll pick this up again next week..for now, just FYI in case y'all reproduce this anywhere else." (and the source of my frustration).


All,

Just Generally speaking...doing the same thing twice (the same way) in one playbook run is a asking for insanity.  Remember that these tasks (given same input) are suppose to *not* make any changes that aren't required (hence the failure).

That said, do we ever care about preserving the cached build of kube?  If not, then a really simple solution here is to add the ``--force`` option.  With that on the second run, we've changed the inputs, so any differing results are to be expected.

it also means I don't need to investigate the actual cause (because we don't care about what the repo-change was, as it's being force-clobbered).

What y'all think?

**Comment by cevich** [comment]
BTW: I think that ``No handlers could be found for logger "dnf"`` is caused by a missing package (memory is a little fuzzy-though).

**Comment by cevich** [comment]
```
    "changed": false, 
    "failed": true, 
    "item": "libguestfs-tools"
}

MSG:
---
async task did not complete within the requested time
```

Probably a networking-related issue...and a reminder that someone should take some time to prune that list of RPMs.  I doubt we really actually need ``libguestfs-tools`` (eh?)

**Comment by cevich** [comment]
...answering some of my own questions...I have a theory of how it broke for me...

> ***we want to cache kube build*** for faster bug fixes into 1.0 branch...

There's a cache-state "non-sequitur" produced by @runcom 's change.  The include-file doesn't only **build** kube.  It also **installs** (and changes other aspects of the system).  Therefor, any future changes in a later run, which **omits** some aspect of those changes, will also fail to invalidate the cache.

For example:

*  AMI caches "kube-past" installation and configuration, along with ``/etc/critical/snafu`` - which causes some horrible bug.
*  An unrelated CI run for some random PR, clones "kube-future" with a fix for that bug:  Don't install ``/etc/critical/snafu``.
*  Random PR author jumps off 16th story, because he/she can't figure out how a supposedly fixed bug seemingly re-appeared.
*  Just before the engineer-splatters, they remember to look at the JFM playbook, but sadly...it's too late.  All they can do is curse Ansible 😀 

Short of being able to tag the AMI cache for a specific branch (seems more and more critical).  I think maybe there's a simple short-term fix here:

* Separate the "building" from the "installing and configuring".
* Only cache the "building" part.
* For the test-time run, ``--force`` clone "future-kube", retaining identical cached output but **not** changes to the system.
* Build ``future-kube`` (gets speed boost), then do the install/configure part.

Does that sound good?

Anyone know off-hand what make target I need to use to avoid installing?

**Comment by runcom** [comment]
> ...answering some of my own questions...I have a theory of how it broke for me...

I'd love to see where it broke for you, was it in the CI or your own VM? I haven't seen any failure in the CI so far actually.

**Comment by cevich** [comment]
> I'd love to see where it broke for you, was it in the CI or your own VM? I haven't seen any failure in the CI so far actually.

@runcom Follow the link in this comment: https://github.com/kubernetes-incubator/cri-o/commit/4dce8e12a0ca0770df3bfb1ae42c106912669365#commitcomment-25387341

Though if my theory is correct, it will be very hard to reproduce this in k8s or any other build+install+configure include.  It's going to depend on way more variables than we should be worrying about.  In any case, separating the clone+build tasks from the install+configure tasks should prevent any possibility of hitting this problem, specially tagged AMI's or otherwise.

(Did I mention that I don't like using cache for CI?) 😀

**Comment by cevich** [comment]
@runcom @mrunalp That last commit is completely speculative, dotted with FIXME's and TODOs.  It's just a brute-force (I'm the dumb brute in this case) attempt to see if it's possible to separate the build, from the install tasks.

Though my feeble attempt may simply implode, the overall-idea should be sound:  Cache the artifacts from building.  Later, force-clone and re-build only any changed artifacts before testing.  This should allow us to avoid any cached-vs-reality inconsistencies (because a repo. changed out of sync with cache-generation).

Does this make any sense at all?

I guess maybe a fall-back is, do the same thing, but only for the kube tasks (instead of everything).  

Oh, also, would it make sense to also cache a CRI-O build using this technique?

**Comment by cevich** [comment]
(woops, forgot to do the pre-test re-building tasks)

**Comment by cevich** [comment]
(/me presses enter, then runs away...fast!)

/test all

**Comment by cevich** [comment]
okay, wow, that's surprising...both slash-test-ami's have successfully past all the speculative build/install changes and are now running the integration tests...

/me looks away in case it implodes

**Comment by cevich** [comment]
@runcom @mrunalp Could I have some help [investigating why the ``ami_fedora`` e2e tests failed](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/kubernetes-incubator_cri-o/1119/test_pull_request_crio_ami_fedora/179/)?

It's certainly related to changes I made in ``DO NOT MERGE: TEST SEPARATION OF BUILD VS INSTALL``.  I marked all the ones I suspect with a ``#TODO`` in the code.  Hopefully one will stand out to you like a sore thumb 😬 (and be easy to fix).

Esp. [This one](https://github.com/kubernetes-incubator/cri-o/pull/1119/files#diff-266df845a86ff85334a3227d44bcac50R8) and [this related one](https://github.com/kubernetes-incubator/cri-o/pull/1119/files#diff-cf3a83a57ca4e9c1eb12ebfc5853c218R21).

**Pull request closed without merging**
