### PR TITLE
sandbox_run: Do not run net plugin in host namespace

### PR DESCRIPTION
**Pull request by jjlakis**
For host network pod there's no need to prepare interfaces to let namespaces communicate - so there's no need to execute plugins. 
Found it while working on kubernetes. Kubelet spawns 2 pods with host networking (kube-proxy, flannel) and networking plugin tried to create 2 veth pairs (1 for each pod) with the same `eth0` name in the host namespace that causes a crash.
@lukasredynk Could you provide some additional information? 

cc @mrunalp @runcom @sameo 

BTW. Right now, kubelet starts with all services, and my kubernetes cluster works fine, I am still debugging problem with image pulling that seems to be the last one before running CRI e2e.

### CODE REVIEW

**Comment by sameo** [comment]
@jjlakis @lukasredynk So If I'd be to create a set of pods on the host ns, would I have to strictly on localhost to have them seeing each others ?
IMHO the correct fix would be to generate a more random interface name than `eth0`, but I may be missing some details.

**Comment by jawnsy** [comment]
@sameo Wouldn't a random interface name make it harder for applications to bind a specific interface? That seems like it could have the potential to break some applications, though I guess it's a more advanced use case than most images.

**Comment by sameo** [comment]
@jawnsy Maybe, although applications should not assume anything about interface names if they want to bind to a specific one.

**Comment by mrunalp** [comment]
@rajatchopra could you chime in here?

**Comment by rajatchopra** [comment]
As an after-thought, we will have to do something more complicated when we start supporting multiple networks for a pod.

**Comment by jjlakis** [comment]
@sameo @jawnsy If we will generate random interface name, we won't get conflict but 2 useless veth pairs will be created.
@rajatchopra We don't create namespace for host network already.

**Comment by lukasredynk** [comment]
@sameo Try running: `docker run --net=host alpine ash` and then in container `ip a`: you'll see all interfaces on your host machine. I think "host network" by definition don't run additional network configuration, it just uses host's. I don't know though what IP should container report as main one.

**Comment by sameo** [comment]
@lukasredynk I think `host` means do not run in a specific networking namespace. But if I want to run my pod in the host ns and I still want to use e.g. flannel as an overlay, I think we would have to run a CNI plugin.
Don't take me wrong, this is probably the saner short term solution, but in the long term we need to be able to so support host networking in a better way.

**Comment by mrunalp** [comment]
@sameo Are we okay merging this for now?

**Comment by sameo** [comment]
@mrunalp Yes, fine with me.

@jjlakis @lukasredynk If you agree the CNI pluging should still be run in the host netns, could we create an issue for that ?

**Comment by sameo** [comment]
LGTM

**Pull request merged**
