### PR TITLE
conmon: close extra files before exit

### PR DESCRIPTION
**Pull request by giuseppe**
Podman will inject fd's into conmon so that open TCP/UDP ports will be
kept busy while the container is running.  This introduces a race
condition as conmon could notify the container exited but these fd's
are still kept busy.  Close them before notifying the container
exited.

Required by: https://github.com/projectatomic/libpod/pull/1100

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

**- What I did**
close extra fd's before conmon terminates

**- How I did it**
cycle through the fds 3-... until we find an unused fd

**- How to verify it**
strace conmon and verify there are a bunch of close(..) before it exits

**- Description for the changelog**
conmon closes extra files before it exits

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
Would this cause any issues with SocketActivation?

**Comment by runcom** [comment]
LGTM
/test all

**Comment by giuseppe** [comment]
> Would this cause any issues with SocketActivation?

There should be no difference.  The Socket Activation fds were already propagated and used by the  OCI runtime that at this time is already terminated.

**Comment by mrunalp** [comment]
We should backport this to 1.11 and 1.10

**Comment by giuseppe** [comment]
@mrunalp this is useful only for podman, do we still need the backport?

**Pull request merged**
