### PR TITLE
fix "docker run" command in Makefile

### PR DESCRIPTION
**Pull request by mountkin**
Signed-off-by: Shijiang Wei <mountkin@gmail.com>

**- What I did**
Make `make dbuild` really works.
**- How I did it**

**- How to verify it**
Type `make dbuild` to see if it builds the binaries successfully. 
**- Description for the changelog**

### CODE REVIEW

**Comment by mountkin** [comment]
CLA signed

**Comment by mrunalp** [comment]
Thanks for your PR. The travis build should be fixed in #1114 and then you can rebase on top of it once it is merged.

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mrunalp** [comment]
Can you rebase to master? (That will fix the travis build.). Thanks!

**Comment by mountkin** [comment]
rebased

**Comment by rhatdan** [comment]
Passes tests. Merging.

**Pull request merged**
