### PR TITLE
fix link in tutorial.md

### PR DESCRIPTION
**Pull request by carlory**
Signed-off-by: carlory <baofa.fan@daocloud.io>

```
➜ wget https://github.com/opencontainers/runc/releases/download/v1.0.0-rc4/runc-linux-amd64

--2017-10-25 12:19:52--  http://github.com/opencontainers/runc/releases/download/v1.0.0-rc4/runc-linux-amd64
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-25 12:19:55 ERROR 404: Not Found.
```

### CODE REVIEW

**Comment by carlory** [comment]
Hi @rhatdan 

Could you take a quick look at this?  Thanks for your time.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.  @mheon PTAL at the libpod change. 

@carlory TYVM for the contribution!

**Comment by carlory** [comment]
@TomSweeneyRedHat thanks for your review.

I don't really know how to rebase it in the situation.   Could you give me some guide? 

delete this branch and redo it?

**output of git log**

```
commit fe873e370df14a88e4e1918d1e1e9e20916e838e (HEAD -> fix_tutorial, origin/fix_tutorial)
Merge: cd04b455 499b2fa1
Author: Mrunal Patel <mrunal@me.com>
Date:   Tue Oct 24 21:02:36 2017 -0700

    fix link

    Signed-off-by: carlory <baofa.fan@daocloud.io>

commit cd04b45540d7d29e17986e707eedd0fab0304492
Merge: 5a4ffef9 a4676154
Author: Mrunal Patel <mrunal@me.com>
Date:   Tue Oct 24 21:01:56 2017 -0700

    Merge pull request #1067 from nalind/secrets-test

    Fixups for crio_secrets.bats
```

**Comment by rhatdan** [comment]
Commands like the following should get you to a rebase.
git pull origin master
git commit -a 
git rebase -i origin
git push --force

**Comment by carlory** [comment]
so sorry, this issue is closed after  I run those commands.

**Comment by TomSweeneyRedHat** [comment]
@carloy No problem at all.  It was just circumstance that someone else spotted the issue in libpod that you did and go the PR in before you.  We thank you very much for your contribution and look forward to seeing more from you in the future!

**Comment by rhatdan** [comment]
@carlory Looks like part of your code was merged.  if not create a new PR.

**Comment by carlory** [comment]
thanks

**Pull request closed without merging**
