### PR TITLE
Do not merge: Bump containers/storage and containers/image

### PR DESCRIPTION
**Pull request by nalind**
Bump the versions of containers/storage and containers/image that we use, and add ostree-go, which is now required by containers/image.

### CODE REVIEW

**Comment by runcom** [comment]
retest

**Comment by runcom** [comment]
If CI passes we could bring image-spec v1 here as well (https://github.com/containers/image/pull/311)

**Comment by runcom** [comment]
wtf

**Comment by runcom** [comment]
So here are the errors:
```
03:14:06 TASK [make and install CRI-O] **************************************************
03:14:59 fatal: [10.8.169.188]: FAILED! => {"ansible_job_id": "578087597862.7941", "changed": true, "cmd": "make install.tools && make && make install && make install.systemd && make install.config", "delta": "0:00:47.512641", "end": "2017-07-20 07:14:53.272756", "failed": true, "finished": 1, "rc": 2, "start": "2017-07-20 07:14:05.760115", "stderr": "ls: cannot access '/root/src/github.com/kubernetes-incubator/cri-o/pkg/storage]/*.go': No such file or directory\nhack/find-godeps.sh: line 26: cd: /root/src/github.com/kubernetes-incubator/cri-o/pkg/storage]: No such file or directory\nNote: checking out '23261fa046586808612c61da7a81d75a658e0814'.\n\nYou are in 'detached HEAD' state. You can look around, make experimental\nchanges and commit them, and you can discard any commits you make in this\nstate without impacting any branches by performing another checkout.\n\nIf you want to create a new branch to retain commits you create, you may\ndo so (now or later) by using -b with the checkout command again. Example:\n\n  git checkout -b <new-branch-name>\n\nHEAD is now at 23261fa... Update README.md\nls: cannot access '/root/src/github.com/kubernetes-incubator/cri-o/pkg/storage]/*.go': No such file or directory\nhack/find-godeps.sh: line 26: cd: /root/src/github.com/kubernetes-incubator/cri-o/pkg/storage]: No such file or directory\n# pkg-config --cflags ostree-1 ostree-1 ostree-1 ostree-1 ostree-1 ostree-1\nPackage ostree-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `ostree-1.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'ostree-1' found\nPackage ostree-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `ostree-1.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'ostree-1' found\nPackage ostree-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `ostree-1.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'ostree-1' found\nPackage ostree-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `ostree-1.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'ostree-1' found\nPackage ostree-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `ostree-1.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'ostree-1' found\nPackage ostree-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `ostree-1.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'ostree-1' found\npkg-config: exit status 1\nmake: *** [crio] Error 2", "stdout": "if [ ! -x \"/root/bin/git-validation\" ]; then \\\n\tgo get -u github.com/vbatts/git-validation; \\\nfi\nif [ ! -x \"/root/bin/gometalinter\" ]; then \\\n\tgo get -u github.com/alecthomas/gometalinter; \\\n\tcd /root/src/github.com/alecthomas/gometalinter; \\\n\tgit checkout 23261fa046586808612c61da7a81d75a658e0814; \\\n\tgo install github.com/alecthomas/gometalinter; \\\n\t/root/bin/gometalinter --install; \\\nfi\nInstalling:\n  gas\n  interfacer\n  safesql\n  unconvert\n  unused\n  gosimple\n  megacheck\n  structcheck\n  unparam\n  staticcheck\n  deadcode\n  goimports\n  golint\n  lll\n  misspell\n  gotype\n  ineffassign\n  varcheck\n  aligncheck\n  dupl\n  errcheck\n  goconst\n  gocyclo\nif [ ! -x \"/root/bin/go-md2man\" ]; then \\\n\tgo get -u github.com/cpuguy83/go-md2man; \\\nfi\ngo build -ldflags '-X main.gitCommit=9d72621 -X main.buildInfo=1500534859' -tags \"selinux seccomp  \" -o crio github.com/kubernetes-incubator/cri-o/cmd/crio\nMakefile:77: recipe for target 'crio' failed", "stdout_lines": ["if [ ! -x \"/root/bin/git-validation\" ]; then \\", "\tgo get -u github.com/vbatts/git-validation; \\", "fi", "if [ ! -x \"/root/bin/gometalinter\" ]; then \\", "\tgo get -u github.com/alecthomas/gometalinter; \\", "\tcd /root/src/github.com/alecthomas/gometalinter; \\", "\tgit checkout 23261fa046586808612c61da7a81d75a658e0814; \\", "\tgo install github.com/alecthomas/gometalinter; \\", "\t/root/bin/gometalinter --install; \\", "fi", "Installing:", "  gas", "  interfacer", "  safesql", "  unconvert", "  unused", "  gosimple", "  megacheck", "  structcheck", "  unparam", "  staticcheck", "  deadcode", "  goimports", "  golint", "  lll", "  misspell", "  gotype", "  ineffassign", "  varcheck", "  aligncheck", "  dupl", "  errcheck", "  goconst", "  gocyclo", "if [ ! -x \"/root/bin/go-md2man\" ]; then \\", "\tgo get -u github.com/cpuguy83/go-md2man; \\", "fi", "go build -ldflags '-X main.gitCommit=9d72621 -X main.buildInfo=1500534859' -tags \"selinux seccomp  \" -o crio github.com/kubernetes-incubator/cri-o/cmd/crio", "Makefile:77: recipe for target 'crio' failed"], "warnings": []}
```
First is this warning, I get it locally on my laptop as well:
```
 "stderr": "ls: cannot access '/root/src/github.com/kubernetes-incubator/cri-o/pkg/storage]/*.go': No such file or directory\nhack/find-godeps.sh: line 26: cd: /root/src/github.com/kubernetes-incubator/cri-o/pkg/storage]: No such file or directory\nNote: checking out '23261fa046586808612c61da7a81d75a658e0814'.\n\
```
While the actual failure is here:
```
pkg-config --cflags ostree-1 ostree-1 ostree-1 ostree-1 ostree-1 ostree-1\nPackage ostree-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `ostree-1.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'ostree-1' found\nPackage ostree-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `ostree-1.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'ostree-1' found\nPackage ostree-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `ostree-1.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'ostree-1' found\nPackage ostree-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `ostree-1.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'ostree-1' found\nPackage ostree-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `ostree-1.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'ostree-1' found\nPackage ostree-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `ostree-1.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'ostree-1' found\npkg-config: exit status 1\nmake: 
```
so I guess we're just missing ostree-dev?

**Comment by rhatdan** [comment]
@runcom @14rcole Put out a patch to fix this yesterday.

https://github.com/kubernetes-incubator/cri-o/pull/672

**Comment by runcom** [comment]
mmm @rhatdan was #672 for this? if so, @nalind could you rebase?

**Comment by rhatdan** [comment]
@runcom @14rcole found this in his patches, I believe, but if @nalind needs to rebase that is fine.

**Comment by runcom** [comment]
@nalind where are we on this? we need it in #1048 according to @baude

**Comment by nalind** [comment]
We're still doing the prerequisite work in https://github.com/containers/image/pull/305.

**Comment by runcom** [comment]
@nalind isn't there an easy way i can work on to have image ID from the config blog digest w/i requiring all that?

**Comment by nalind** [comment]
@runcom https://github.com/containers/image/pull/363 might do it.

**Comment by nalind** [comment]
Disk was full on that failed jenkins run.
/retest

**Comment by runcom** [comment]
@nalind this is not fixing https://github.com/kubernetes-incubator/cri-o/issues/1048
```
ID: 073ab47a2f7e22207d94ea04f65432b4386cedaebe3ed16b57d315386c3f4b11
Tag: docker.io/library/busybox:1-uclibc
Size: 1131313
ID: 49ba2bda8e16c7b4fce66084a66781cffb0c74cf4792d2abe8a04911deec575c
Tag: docker.io/library/busybox:1
Size: 1131313
```
I can still see two different images IDs when the config blob sha should be the same for both

**Comment by runcom** [comment]
In docker they both have the same Image IDs:
```
docker.io/busybox                  1-uclibc            54511612f1c4        6 weeks ago         1.13 MB
docker.io/busybox                  latest              54511612f1c4        6 weeks ago         1.13 MB
```

**Comment by nalind** [comment]
That's not what I'm seeing here.  Starting with empty storage, I get this after pulling both by name:
 ID: 54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971
 Tag: docker.io/library/busybox:1-uclibc
 Tag: docker.io/library/busybox:1
 Size: 1339880

**Comment by runcom** [comment]
> That's not what I'm seeing here. Starting with empty storage, I get this after pulling both by name:
> ID: 54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971
> Tag: docker.io/library/busybox:1-uclibc
> Tag: docker.io/library/busybox:1
> Size: 1339880

let me re-test :)

**Comment by runcom** [comment]
Alright I can see it's working now:
```
$ sudo ./crioctl image list
ID: 54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971
Tag: docker.io/library/busybox:1-uclibc
Tag: docker.io/library/busybox:1
Size: 1339880
```
but with old storage I get:
```
$ sudo ./crioctl image pull busybox:1-uclibc       
FATA[0004] pulling image failed: rpc error: code = 2 desc = Error checking for blob sha256:03b1be98f3f9b05cb57782a3a71a44aaf6ec695de5f4f8e6c1058cd42f04953e at destination: Error looking for compressed layers with digest "sha256:03b1be98f3f9b05cb57782a3a71a44aaf6ec695de5f4f8e6c1058cd42f04953e": layer not known
```
Isn't there any way to workaround this issue in code? We can't really ship this to the v1.0.x release otherwise as it's breaking people.

**Comment by nalind** [comment]
@runcom Yeah, that's a bug in how `HasBlob()` was interpreting results from `LayersByUncompressedDigest()` and `LayersByCompressedDigest()` (should be fixed in https://github.com/containers/image/pull/305 now), and how those methods were handling read-only storage locations (https://github.com/containers/storage/pull/132).  This should fix that.

**Comment by runcom** [comment]
> @runcom Yeah, that's a bug in how HasBlob() was interpreting results from LayersByUncompressedDigest() and LayersByCompressedDigest() (should be fixed in containers/image#305 now), and how those methods were handling read-only storage locations (containers/storage#132). This should fix that.

alright, I'll re-test this out :)

**Comment by runcom** [comment]
> @runcom Yeah, that's a bug in how HasBlob() was interpreting results from LayersByUncompressedDigest() and LayersByCompressedDigest() (should be fixed in containers/image#305 now), and how those methods were handling read-only storage locations (containers/storage#132). This should fix that.

@nalind alright, it's working fine, except  that removing a tag, removes all tags and image ID :(
```
17:11:52 [github.com/kubernetes-incubator/cri-o] ‹pr/origin/654› sudo ./crioctl image list
ID: 54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971
Tag: docker.io/library/busybox:1-uclibc
Tag: docker.io/library/busybox:1
Size: 2024
17:13:36 [github.com/kubernetes-incubator/cri-o] ‹master› sudo ./crioctl image remove --id busybox:1-uclibc17:13:40 [github.com/kubernetes-incubator/cri-o] ‹master› sudo ./crioctl image remove --id busybox:1
FATA[0000] removing the image failed: rpc error: code = 2 desc = identifier is not an image
```

**Comment by runcom** [comment]
> @nalind alright, it's working fine, except that removing a tag, removes all tags and image ID :(

the behavior should be: "only remove the whole image IFF the tag I'm removing is the last one, otherwise we need that image cause other tags are referencing it"

**Comment by nalind** [comment]
Okay, I think we've got an `UntagImage()` that does that correctly, though CRI not having a "force" flag in `RemoveImageRequest` means that I still want to treat requests that specify an ID rather than a name as though "force" is set, in order to keep the "pipe a list of IDs through xargs crictl rmi" idiom working.

**Comment by runcom** [comment]
I'll re-test everything in a moment. Thanks @nalind

**Comment by runcom** [comment]
> Okay, I think we've got an UntagImage() that does that correctly, though CRI not having a "force" flag in RemoveImageRequest means that I still want to treat requests that specify an ID rather than a name as though "force" is set, in order to keep the "pipe a list of IDs through xargs crictl rmi" idiom working.

working ok now:
```
18:17:08 [github.com/kubernetes-incubator/cri-o] ‹pr/origin/654› sudo ./bin/crioctl image list                 
ID: 54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971
Tag: docker.io/library/busybox:1
Tag: docker.io/library/busybox:1-uclibc
Size: 1339880
18:17:10 [github.com/kubernetes-incubator/cri-o] ‹pr/origin/654› sudo ./bin/crioctl image remove --id busybox:1
18:17:17 [github.com/kubernetes-incubator/cri-o] ‹pr/origin/654› sudo ./bin/crioctl image list                 
ID: 54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971
Tag: docker.io/library/busybox:1-uclibc
Size: 1339880
```

**Comment by runcom** [comment]
This is also fixing the critest failure:
```
18:27:08 [github.com/kubernetes-incubator/cri-o] ‹master*› sudo PATH=$PATH GOPATH=$GOPATH /home/amurdaca/go/bin/critest -c --runtime-endpoint /var/run/crio.sock --image-endpoint /var/run/crio.sock --focus="listImage should get exactly 2 repoTags" validation
Running Suite: E2ECRI Suite
===========================
Random Seed: 1509470907 - Will randomize all specs
Will run 1 of 55 specs

SSSS
------------------------------
[k8s.io] Image Manager 
  listImage should get exactly 2 repoTags in the result image [Conformance]
  /home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/image.go:105
[BeforeEach] [k8s.io] Image Manager
  /home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:50
[BeforeEach] [k8s.io] Image Manager
  /home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/image.go:46
[It] listImage should get exactly 2 repoTags in the result image [Conformance]
  /home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/image.go:105
STEP: Pull image : busybox:1-uclibc
STEP: Pull image : busybox:1
STEP: Remove image : busybox:1-uclibc
STEP: Remove image by ID : 54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971
STEP: Remove image : busybox:1
[AfterEach] [k8s.io] Image Manager
  /home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:51

• [SLOW TEST:14.158 seconds]
[k8s.io] Image Manager
/home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:72
  listImage should get exactly 2 repoTags in the result image [Conformance]
  /home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/image.go:105
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 55 Specs in 14.159 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 54 Skipped PASS
```

**Comment by runcom** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
