### PR TITLE
Fix pull-by-digest

### PR DESCRIPTION
**Pull request by nalind**
Fix https://github.com/kubernetes-incubator/cri-o/issues/349

This PR attempts to resolve issues when pulling and referring to images using sha256 references.  It includes some changes to the vendored copy of containers/image to make it easier to test together.

Images should now be getting tagged with the fully-expanded name and tag, and also with the name and tag and digest when they're pulled using a digest identifier.

### CODE REVIEW

**Comment by runcom** [comment]
testing this out a bit

**Comment by runcom** [comment]
Alright this is fixing #349 !!!

you can test this out with this PR and:
```
$ k run nginx --image=nginx@sha256:4aacdcf186934dcb02f642579314075910f1855590fd3039d8fa4c9f96e48315
```
W/o this patch, the command above fails to run an nginx pod

**Comment by runcom** [comment]
while we wait for c/image and c/storage PR to be merged, I'll run k8s's Conformance tests with this (after the weekend probably)

**Comment by runcom** [comment]
images related tests are failing though https://travis-ci.org/kubernetes-incubator/cri-o/jobs/221839248#L2665

**Comment by mrunalp** [comment]
Any updates here?

**Comment by mrunalp** [comment]
@nalind ping :)

**Comment by runcom** [comment]
sorry, meant to get back with results from e2e, I'll test this out asap.

**Comment by nalind** [comment]
Image-related integration tests should be passing again.

**Comment by mrunalp** [comment]
@nalind Thanks! Is this also rebased?

**Comment by runcom** [comment]
Re-running k8s tests now, thanks @nalind

**Comment by nalind** [comment]
@mrunalp Yup!

**Comment by runcom** [comment]
@nalind could you add a smoke test using the command in https://github.com/kubernetes-incubator/cri-o/pull/450#issuecomment-293991060 to https://github.com/kubernetes-incubator/cri-o/blob/master/test/image.bats#L26?

**Comment by runcom** [comment]
k8s tests are busted for me after some have run...not sure why. @mrunalp could you try running k8s tests as well? The issue with k8s isn't related to this PR specifically though so we can merge this w/o blocking on k8s tests.

**Comment by mrunalp** [comment]
@runcom Yeah, I'll run the tests.

**Comment by nalind** [comment]
@runcom Added those tests, and fixed a bit of confusion in ListImages().  Also added some checks in other image-related tests, to ensure that "ocic image list" output is actually empty when we expect to have removed all local images, and that it isn't empty when we expect to have images.

**Comment by mrunalp** [comment]
I am seeing this error when e2e tests pull images before they start running:
```
ser "root", retrying in 1s (1 of 5): rpc error: code = 2 desc = Error committing the finished image: that ID is already in use
E0425 11:35:50.829173   14614 remote_image.go:102] PullImage "gcr.io/google_containers/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff" from image service failed: rpc error: code = 2 desc = Error committing the finished image: that ID is already in use
W0425 11:35:50.829205   14614 image_list.go:150] Failed to pull gcr.io/google_containers/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff as user "root", retrying in 1s (2 of 5): rpc error: code = 2 desc = Error committing the finished image: that ID is already in use
E0425 11:35:54.829089   14614 remote_image.go:102] PullImage "gcr.io/google_containers/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff" from image service failed: rpc error: code = 2 desc = Error committing the finished image: that ID is already in use
W0425 11:35:54.829119   14614 image_list.go:150] Failed to pull gcr.io/google_containers/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff as user "root", retrying in 1s (3 of 5): rpc error: code = 2 desc = Error committing the finished image: that ID is already in use
E0425 11:35:58.728813   14614 remote_image.go:102] PullImage "gcr.io/google_containers/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff" from image service failed: rpc error: code = 2 desc = Error committing the finished image: that ID is already in use
W0425 11:35:58.728842   14614 image_list.go:150] Failed to pull gcr.io/google_containers/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff as user "root", retrying in 1s (4 of 5): rpc error: code = 2 desc = Error committing the finished image: that ID is already in use
E0425 11:36:02.607793   14614 remote_image.go:102] PullImage "gcr.io/google_containers/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff" from image service failed: rpc error: code = 2 desc = Error committing the finished image: that ID is already in use
W0425 11:36:02.607836   14614 image_list.go:150] Failed to pull gcr.io/google_containers/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff as user "root", retrying in 1s (5 of 5): rpc error: code = 2 desc = Error committing the finished image: that ID is already in use
W0425 11:36:02.607849   14614 image_list.go:153] Could not pre-pull image gcr.io/google_containers/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff rpc error: code = 2 desc = Error committing the finished image: that ID is already in use output: 
Failure [25.501 seconds]
[BeforeSuite] BeforeSuite 
/root/gosrc/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:163

  Expected error:
      <*grpc.rpcError | 0xc420d6cbc0>: {
          code: 2,
          desc: "Error committing the finished image: that ID is already in use",
      }
      rpc error: code = 2 desc = Error committing the finished image: that ID is already in use
  not to have occurred

```

**Comment by runcom** [comment]
apart from @mrunalp comment above to be fixed, k8s tests seem to be running fine (even if I reported some tests started to fail on master as well in https://github.com/kubernetes-incubator/cri-o/issues/441)

**Comment by nalind** [comment]
@mrunalp That's the error we'll get now when we try to pull an image that's already present, since we can check for duplicate IDs.  I'll tweak cri-o's PullImage() to check for the presence of the image with the ID and just return a success result, unless you think we should have the image library do that instead.

**Comment by mrunalp** [comment]
@nalind Yeah, it makes sense to return a success result if it is already present and it should probably be fixed in the image library. Thanks!

**Comment by nalind** [comment]
@mrunalp Okay, made that change, and some other simplifications to the patches we're testing here that are part of https://github.com/containers/image/pull/261 based on feedback there.

**Comment by mrunalp** [comment]
Is this rebased on https://github.com/containers/image/pull/261 which was merged?

**Comment by nalind** [comment]
There was an additional error check and a partial refactor in the version which was merged to the image library.  I've just rebased this PR and switched to vendoring the versions of the storage and image libraries which contain the changes we wanted.

**Comment by runcom** [comment]
:+1:

**Comment by mrunalp** [comment]
I'll run the e2e on this. Thanks!

**Comment by mrunalp** [comment]
e2e passed fine :+1:

**Comment by runcom** [comment]
:tada:

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
