### PR TITLE
Fixes to use of bats in integration tests

### PR DESCRIPTION
**Pull request by nalind**
The bats `run` helper function sets `$status`, so there's no point to checking the value of `$status` in an integration test when we haven't used the `run` helper to run a command.  We almost always want to be sure to check the value after we _have_ used the helper.  Fixing that turned up that the test for `kpod stop` expected the container that it attempted to stop by name to have a different name than it was getting, so it now looks up the name using the ID first.

There's no need to run commands like `sleep` or `rm -f` with the helper, since they're not expected to fail, and if they do, it's probably indicative of a larger problem that we want to allow to cause tests to
fail.

Helper functions like `start_crio` already check `$status` when they call `run`, so we don't need to check it again after they return.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Do we need to run e2e on this? I don't think we are running these tests in anything but travis?

**Comment by TomSweeneyRedHat** [comment]
Does @nalind win a prize for PR #1000?

**Comment by mheon** [comment]
@rhatdan The integration tests do run in the Jenkins CI, so it might be worth running them. Maybe not doing all the tests though, just the integration ones?

**Comment by rhatdan** [comment]
@mrunalp Yes I realized I was being dumb. 
/test all

**Comment by TomSweeneyRedHat** [comment]
LGTM with happy CI

**Comment by nalind** [comment]
That's all we're changing here -- everything's confined to the `tests` directory, except for the part where we add a package to the list in the playbook and the integration test Dockerfile.

**Comment by mrunalp** [comment]
We could have run just the integration tests but no harm in running everything now that it is already started :)

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
