### PR TITLE
Return image digests in ImageStatus()

### PR DESCRIPTION
**Pull request by nalind**
The image's digest is defined as the digest of the image's configuration blob, so return that value as the image's digest in the ImageStatus().

### CODE REVIEW

**Comment by mrunalp** [comment]
Looks fine to me. @runcom PTAL.

**Comment by nalind** [comment]
Hmm, this won't be enough to fix #531.

**Comment by runcom** [comment]
Looks ok if Travis is happy

**Comment by nalind** [comment]
This one's been revised since I opened it, and I don't expect it to pass in its current form.

**Comment by rhatdan** [comment]
@nalind should this be closed?

**Comment by rhatdan** [comment]
@nalind What should we do with this?

**Comment by nalind** [comment]
At this point we should probably close it in favor of #654.

**Pull request closed without merging**
