### PR TITLE
Hooks from ctr annotations

### PR DESCRIPTION
**Pull request by runcom**
**- What I did**

Fix https://github.com/kubernetes-incubator/cri-o/issues/1319 @RenaudWasTaken PTAL, we now read container's annotations as well

The other commits are fixups
@mrunalp PTAL

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by RenaudWasTaken** [comment]
Also LGTM

**Comment by rhatdan** [comment]
@mrunalp PTAL

**Pull request merged**
