### PR TITLE
Add support for partial IDs for exec and attach

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@adelton This should make crictl exec work with partial IDs.

**Comment by mrunalp** [comment]
@wking Yeah, I think at some point that function got changed from taking a request object to id. We can rename it.

**Comment by TomSweeneyRedHat** [comment]
LGTM, function name change would be nice, otherwise LGTM.

**Comment by rhatdan** [comment]
Lets rename the function and then we can merge.

**Comment by mrunalp** [comment]
Pushed update with function renamed.

**Comment by mrunalp** [comment]
@rhatdan @runcom This is ready.

**Comment by rhatdan** [comment]
All Green
Merging.

**Pull request merged**
