### PR TITLE
integration-playbook: Don't re-swap

### PR DESCRIPTION
**Pull request by cevich**
If the playbook is run multiple times, it can result in the in-use swap
file being truncated.  A decidedly bad thing that can be avoided by
checking for it's existence first.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
This is non-urgent.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Should we be calling

 swapon $SWAPDEV && \
+      swapon --show

In either case.  Just because the file exists does not mean it is being used for swap.  Of course this will only work if you can call swapon on the same device multiple times, without causing failures.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by cevich** [comment]
@rhatdan Good idea.

**Comment by rhatdan** [comment]
My comment did not quite come out correctly.  I was suggesting that you break out 
```
swapon $SWAPDEV  
```
Also. since just because /root/swap exists, does not mean someone set it up for swap.

**Comment by cevich** [comment]
Ya, and for sure there's a more intelligent way to do these things.  I'll come back here once the race to #927 and #928 finish.

**Pull request closed without merging**
