### PR TITLE
Btrfs build

### PR DESCRIPTION
**Pull request by mrunalp**
Alternative to #968 

cc: @stevekuznetsov @rhatdan @nalind

### CODE REVIEW

**Comment by mrunalp** [comment]
RHEL ami is now onto integration tests.

**Comment by mrunalp** [comment]
okay, need to pass the buildtag to make localintegration as well.

**Comment by stevekuznetsov** [comment]
Might be simpler to have `make` figure this stuff out at build-time instead of having to pass the flags in buty that's up to you

**Comment by mrunalp** [comment]
@stevekuznetsov Yeah, I am open to that. It should be very simple to add to the existing hack scripts. 
I will see if this latest run is any better or will change it.

**Comment by stevekuznetsov** [comment]
@mrunalp you're not changing anything in the AMI here -- the CRI-O builds are done per-PR

**Comment by mrunalp** [comment]
@stevekuznetsov Yep, you're right. I've been on autopilot running the ami builds today. I will put a /test all here.

**Comment by mrunalp** [comment]
@stevekuznetsov Actually I did mark the rhel ami from 968 as ready so we will need to retag it.

**Comment by mrunalp** [comment]
I have tagged the rhel ami from this PR as it passed the integration and is onto e2e.

**Comment by mrunalp** [comment]
@stevekuznetsov We probably need to run ami tests again as the nightly build must have overwritten the one I marked ready?

**Comment by stevekuznetsov** [comment]
Ah, yeah, that could be the case

**Comment by stevekuznetsov** [comment]
We could remove those jobs if you think amis will continue to be in flux for a while

**Comment by mrunalp** [comment]
@stevekuznetsov I am hoping it will be fixed today. We can decide by EOD today. Thanks!

**Comment by mrunalp** [comment]
@stevekuznetsov Packaging the AMI keeps on failing. Is that an AWS issue?

**Comment by mrunalp** [comment]
Marked rhel ami as ready so will run rhel tests next.

**Comment by mrunalp** [comment]
The RHEL tests have some SELinux issues. I just checked on the VM. We will need to disable it.

**Comment by mrunalp** [comment]
okay the e2e tests look good and travis failed on an image pull. Restarting it.

**Comment by mrunalp** [comment]
travis still hitting image pull flakes. Restarted.

**Comment by mrunalp** [comment]
Finally done! Merging.

**Pull request merged**
