### PR TITLE
vendor: remove dep and use vndr

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@sameo @mrunalp PTAL

**Comment by runcom** [comment]
This is needed to easily switch master back to kube 1.6.x and tag v0.4 from master (then move everything to kube-1.6.x branch again)

**Comment by mrunalp** [comment]
Let us get this in next so we can bump up containers/storage for some fixes.
cc: @rhatdan.

**Comment by runcom** [comment]
rebased

**Comment by mrunalp** [comment]
LGTM

**Comment by sameo** [comment]
LGTM

**Pull request merged**
