### PR TITLE
Disable compression by default.

### PR DESCRIPTION
**Pull request by rhatdan**
Picking up @14rcole patches, since he has gone back to school.
Added fix for @mtrmac comment on compression variable.
Replaces https://github.com/kubernetes-incubator/cri-o/pull/739

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon @runcom @mtrmac PTAL

**Comment by rhatdan** [comment]
[retest]

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but Travis isn't happy.

**Comment by mtrmac** [comment]
LGTM

**Comment by rhatdan** [comment]
[retest]

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Fixed tests. Travis is passing.

**Comment by rhatdan** [comment]
[retest]

**Comment by mrunalp** [comment]
[retest]

**Comment by rhatdan** [comment]
Tests are passing, I am going to merge.

**Pull request merged**
