### PR TITLE
Refactor kpod tests

### PR DESCRIPTION
**Pull request by umohnani8**
Move kpod tests from kpod.bats to kpod_[commandname].bats
Also make sure all status checks have a echo $output before them.

Signed-off-by: Ryan Cole <rcyoalne@gmail.com>

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
Taking over https://github.com/kubernetes-incubator/cri-o/pull/781

**Comment by umohnani8** [comment]
[retest]

**Comment by umohnani8** [comment]
[retest]

**Comment by umohnani8** [comment]
@rhatdan the clean up test for one of the kpod pull test keeps failing in jenkins
`
not ok 88 kpod pull from a non existent image
# (from function `cleanup_test' in file ./helpers.bash, line 350,
#  from function `teardown' in test file ./kpod_pull.bats, line 10)
#   `cleanup_test' failed
# error pulling image from "umohnani/get-started": error loading image "umohnani/get-started": Error initializing image from source docker://umohnani/get-started:latest: manifest unknown: manifest unknown
# main.pullCmd
# 	/root/src/github.com/kubernetes-incubator/cri-o/cmd/kpod/pull.go:53
# github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli.HandleAction
# 	/root/src/github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli/app.go:485
# github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli.Command.Run
# 	/root/src/github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli/command.go:193
# github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli.(*App).Run
# 	/root/src/github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli/app.go:250
# main.main
# 	/root/src/github.com/kubernetes-incubator/cri-o/cmd/kpod/main.go:99
# runtime.main
# 	/usr/local/go/src/runtime/proc.go:185
# runtime.goexit
# 	/usr/local/go/src/runtime/asm_amd64.s:2197
# rm: cannot remove â€˜/tmp/tmp.spn0wgPqa4/crio/overlay2â€™: Device or resource busy
`
Should I remove this pull test? I don't get why it is failing...

**Comment by rhatdan** [comment]
The big difference is that you changed the storage, the tests previously ran on --storage_driver=vfs. now you are running it with Overlay, and it looks like there is still a process running on the system, which is preventing overlay from being umounted?  If you want to get this merged, change kpod_tests to use vfs and then see if it passes.  Then we can continue looking at the issue a future pull request.

**Comment by rhatdan** [comment]
@umohnani8 Also does this fail if you run it locally or only in the E2e tests?

**Comment by umohnani8** [comment]
@rhatdan it fails locally also. But when I remove the cleanup test, it works fine. So should I change the storage driver back to vfs or get rid of the cleanup test?

**Comment by rhatdan** [comment]
Lets change it back to VFS get this merged and then open a pull request to change kpod_pull.bats to use the default and we will look into it.

**Comment by umohnani8** [comment]
fixed

**Comment by umohnani8** [comment]
[retest]

**Comment by rhatdan** [comment]
[retest]

**Comment by umohnani8** [comment]
[retest]

**Comment by rhatdan** [comment]
@cevich Tests are not running?

**Comment by umohnani8** [comment]
@rhatdan I think Jenkins hates me :(

**Comment by rhatdan** [comment]
@umohnani8 It hates us all.

**Comment by umohnani8** [comment]
[retest]

**Comment by umohnani8** [comment]
@rhatdan @cevich any reason why Jenkins is not getting triggered?

**Comment by cevich** [comment]
> @umohnani8 It hates us all.

Ain't that the truth, damn thing just can't get along with anyone 😖 

*sigh* I'll investigate...though it may be more generally broke.  @mrunalp mailed me on a failure that looks infrastructure related...

**Comment by cevich** [comment]
@umohnani8 looking at the comment-timestamps...

> @rhatdan I think Jenkins hates me :(

This literally seems to be the case, as in, you're not on the whitelist and @rhatdan or @mrunalp or @runcom  didn't say the magic-word recently.

**Comment by umohnani8** [comment]
@cevich oh darn sigh. Could I please be added to the whitelist?

**Comment by cevich** [comment]
@umohnani8 yes, I'll take care of it.  For future reference, here's how it's done (internal link): https://hurl.corp.redhat.com/5e22799

**Comment by cevich** [comment]
@umohnani8 okay, the deed is done.  It'll take an average of 15-minutes for the change to go live, worst-case is 30-minutes.  It _should_ automatically trigger since you already said the magic word.  If not, please let me know (b/c then there's a different problem).

**Comment by umohnani8** [comment]
@cevich great! Thank you :)

**Comment by cevich** [comment]
@umohnani8 NP.  But...there's a bigger problem due to clouds moving around...the experts are engaged on fixing that.

**Comment by umohnani8** [comment]
[retest]

**Comment by umohnani8** [comment]
[retest]

**Comment by rhatdan** [comment]
Sadly it looks like certain tests are not running.  @cevich ideas?

**Comment by umohnani8** [comment]
@rhatdan any reason why RHEL is showing 0/0?

**Comment by umohnani8** [comment]
[retest]

**Comment by cevich** [comment]
> any reason why RHEL is showing 0/0?

@umohnani8  This means the playbook broke.  The naive result-analysis that produces the silly 0/0 message doesn't account for the number of actually executed tests.  Fix here: https://hurl.corp.redhat.com/a9b22d4

> certain tests are not running. @cevich ideas?

@rhatdan  Does 'certain tests' mean anything other than what my fix addresses?  (just wanna be sure)

**Comment by rhatdan** [comment]
Your fix looks good, but it just tells us the test failed when we see 0/0 test passed. Why is the ansible script failing, and consistently for certain PRs?

**Comment by cevich** [comment]
> tells us the test failed

@rhatdan We can make the message say whatever you like.  Would it be more helpful if it read something like " the playbook failed, see the log for more info." ?

> consistently for certain PRs?

Well consistency is at least welcome 😀 For sure I'd rather see it fail, than report a false-success.  It doesn't help much that Ansible output/log analysis is an art unto itself.  These things can be really difficult to pin-down.  Looking at the fullresults.txt logs, do you see any patterns around particular times (e.g. several jobs failing network-related operations)?

I'll help keep an eye-out as well, but please keep pointing them out to me just in case.

**Comment by umohnani8** [comment]
@rhatdan @cevich is there something I need to do to get the tests passing?

**Comment by cevich** [comment]
@umohnani8 sorry for confusing the actual problem with so many details...All you've gotta do is [retest] (hopefully) 😀   If it does the samn-damn-thing, let me know right away.  However other builds ran fine previously, so it should be okay.

**Comment by rhatdan** [comment]
@cevich [retest] never seemed to have run.

**Comment by cevich** [comment]
@rhatdan you're mentioning it just then should have triggered it 😀 

investigating...

**Comment by cevich** [comment]
it's running: https://hurl.corp.redhat.com/6b3c738

**Comment by cevich** [comment]
@rhatdan @umohnani8 @mrunalp "Which job is for this pr?!?!?!?" Fishing lesson:

1. Go to here: https://hurl.corp.redhat.com/80879c2
2. Look at 'TESTING_PR'
3. If it's not the one you want, click 'Previous Build' (on the left)
4. Repeat  3rd step 32,767 times, or until your clicking-finger gets sore 😀 

Seriously, I think only about 10-jobs can be running, so no need to go further than that 😀 

(yes this sucks and needs fixing...anyone care to open a trello card for it?)

**Comment by rhatdan** [comment]
@cevich I see jobs start and stop quickly in https://atomic-e2e-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cri-o-integration-tests-prs/
But none of these tests are ever completing.  In this case this test is not running and never reported any status here.

**Comment by cevich** [comment]
@rhatdan okay, looking...

**Comment by cevich** [comment]
...I see the problem in the console log @rhatdan: https://hurl.corp.redhat.com/db01d87

That highlighted line corresponds with line 183: https://hurl.corp.redhat.com/9475b7e

That called script is intended to make sure the sub-builds (one per VM) used the same inputs, and if so comment in the PR.  If not, well...you get nothing - because that's useful 😦 

SO!  That means someone (*sigh* probably me) needs to check the ``*.properties`` files in the top-level directory and under ``PLATFORM/*``.  And see WTF isn't matching. *whew*

Mind if I do that after lunch?

**Comment by cevich** [comment]
(wondering if failing-to-post results problem is connected with playbook failures...that seems to be the pattern recently)

**Comment by umohnani8** [comment]
@rhatdan @mheon please trigger e2e

**Comment by umohnani8** [comment]
rebased /test all

**Comment by mheon** [comment]
I think the test command needs to be on a new line, like:

/test all

**Comment by umohnani8** [comment]
oh okay, thanks @mheon

**Comment by rhatdan** [comment]
Tests are now passing.  I am going to merge.

**Pull request merged**
