### PR TITLE
Add support for label filtering

### PR DESCRIPTION
**Pull request by mrunalp**
With this we can filter containers by labels
ocic ctr list --label tier=backend

I'll add a test.

@runcom @mikebrow PTAL

### CODE REVIEW

**Comment by runcom** [comment]
LGTM, waiting for the test and then merge

**Comment by mikebrow** [comment]
LGTM works great!

**Comment by runcom** [comment]
@mrunalp feel free to add the test and merge yourself (or defer the test but I would like to have it as part of this PR if you don't mind)

**Comment by mrunalp** [comment]
@runcom Yeah, I am adding the tests. will update the PR shortly.

**Comment by mrunalp** [comment]
Added a test.

**Comment by runcom** [comment]
LGTM

**Pull request merged**
