### PR TITLE
Release 1.0.1

### PR DESCRIPTION
**Pull request by mrunalp**
@rhatdan @runcom @sameo PTAL

### CODE REVIEW

**Comment by runcom** [comment]
LGTM :tada:

**Comment by mrunalp** [comment]
cc: @giuseppe @lsm5 for rpms and new system container when this is merged. Also, note that this has two commits and we need to build from the first commit.

**Comment by rhatdan** [comment]
:+1:

**Comment by giuseppe** [comment]
@lsm5 please poke me once the RPMs are done

**Comment by mrunalp** [comment]
@jwhonce FYI

**Pull request merged**
