### PR TITLE
Make ignore patterns absolute

### PR DESCRIPTION
**Pull request by apilloud**
Git ignore lines without a leading slash can ignore any part of the path. This PR updates the ignore patterns of build artifacts to be absolute. As an example, without this change the rule for the 'ocid' binary also ignores new files created under 'cmd/ocid'.

### CODE REVIEW

**Comment by jawnsy** [comment]
LGTM! Could you also sort the lines?

**Comment by apilloud** [comment]
Sorted and added leading slash to '.artifacts' (which I missed before).

**Comment by apilloud** [comment]
Updated commit messages with the super secret handshake so tests will pass.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
